### ISSUE TITLE
Header/footer options.

### ISSUE THREAD

**Issue by struchkov** [mikehaertl/phpwkhtmltopdf#100]
When I try to add the footer or header of the previously prepared html page, I get an error:

[error] [php] is_file(): File name is longer than the maximum allowed path length on this platform

Error is_file() checking:

Pdf.php line 284
```
if ($urlRequired && !(is_file($val) || preg_match('/^(https?:)?\/\//i',$val) || $val===strip_tags($val))) {
    $options[$key] = new File($val, '.html', self::TMP_PREFIX, $this->tmpDir);
}
```

**Comment by mikehaertl** [comment]
Can you modify that line to this:

```
if ($urlRequired && !(preg_match('/^(https?:)?\/\//i',$val) || is_file($val) || $val===strip_tags($val))) {
```

Changing the order should not have any impact (details here: https://github.com/mikehaertl/phpwkhtmltopdf/pull/38).

**Comment by struchkov** [comment]
I already did that. Thank you.

**Comment by mikehaertl** [comment]
So does this fix your problem? I'll supply this as a fix then.

**Comment by struchkov** [comment]
Yes, of course it has solved the problem. Thanks.

**Comment by struchkov** [comment]
```
if ($urlRequired && !(preg_match('/^(https?:)?\/\//i',$val) || is_file($val) || $val===strip_tags($val))) {
```
I was wrong, this method does not work ...

I solved the problem as follows:
```
$isFile = (strlen($val) <= PHP_MAXPATHLEN) ? is_file($val) : false;
if ($urlRequired && !($isFile || preg_match('/^(https?:)?\/\//i',$val)  || $val===strip_tags($val))) {
    $options[$key] = new File($val, '.html', self::TMP_PREFIX, $this->tmpDir);
}
```

**Comment by mikehaertl** [comment]
@struchkov Great, thanks, I was thinking about a similar solution. Modified your solution a little and updated the code. Maybe you want to help testing?

**Comment by struchkov** [comment]
I tested your modified solution - everything works fine!

**Comment by mikehaertl** [comment]
Cool. I think this deserves a new release: https://github.com/mikehaertl/phpwkhtmltopdf/releases/tag/2.0.4

Thanks for your help!
