### ISSUE TITLE
Get PDF file as string

### ISSUE THREAD

**Issue by lexakozakov** [mikehaertl/phpwkhtmltopdf#102]
Hello Mike, 
Could I get PDF content as string? I have to put generated PDF into email.

Thanks.

**Comment by mikehaertl** [comment]
No, but you can save it as file locally. If you do that, you can do with that file whatever you want (read in, attach to email, etc). Actually the `Pdf` class already uses a [tmp file](https://github.com/mikehaertl/php-tmpfile) internally. So if all you need is a temporary file that gets deleted automatically after processing, you can its filename with `$pdf->getPdfFilename()`.
