### ISSUE TITLE
It would be nice to have your own exception, instead of default one - Exception 

### ISSUE THREAD

**Issue by lexakozakov** [mikehaertl/phpwkhtmltopdf#103]
Hey, I'm talking about that part
```
if (!$pdf->send()) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
}
```

**Comment by mikehaertl** [comment]
That code ist not part of the class, i.e. something *you* have to write in *your* code. So it's up to you, which exception you throw.

**Comment by lexakozakov** [comment]
True, it's my fuck up.
