### ISSUE TITLE
command params with the only one "-"

### ISSUE THREAD

**Issue by lexakozakov** [mikehaertl/phpwkhtmltopdf#104]
wkhtmltopdf has the params with the only one "-" symbol. For example -B or -L. 

There is no ability to set a such param. "--" is added instead.

**Comment by mikehaertl** [comment]
The single dash variants are only shortcuts to the params with double dash. E.g. `-q` is the same as `--quiet`. So you can set all available option as far as I can see.

**Comment by lexakozakov** [comment]
Thanks, I didn't found the alternative way for set the params.
