### ISSUE TITLE
Class 'File' not found - CodeIgniter

### ISSUE THREAD

**Issue by kishorkurian123** [mikehaertl/phpwkhtmltopdf#106]
Hey mate,

I am trying to use this as a library in CodeIgniter. I get this error as the Class 'File' not found.

Can you just point me in the right direction?

**Comment by mikehaertl** [comment]
Are you sure, the composer autoloader is included?

https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by kishorkurian123** [comment]
I figured it out. You can close the issue :)
