### ISSUE TITLE
Can I pass some custom variables to the header/footer html?

### ISSUE THREAD

**Issue by newpen** [mikehaertl/phpwkhtmltopdf#107]
I know I can get the variables like page, section etc on the footer.html through Javascript, but can I also pass some custom variables from the PAP that calls the phpwkhtmltopdf to the footer.html, so that I can display the strings (that is a variable) that I want on the footer? Thank you!

**Comment by mikehaertl** [comment]
See the `replace` option in the example here:

https://github.com/mikehaertl/phpwkhtmltopdf#setting-options

**Comment by newpen** [comment]
The replace option doesn't seem to be working on my footer html file.

$mypage = 'www.example.com';

$options = array(
		'replace' => array(
			'{webpage}' => $mypage,
		),
		'footer-html' => 'footer.html',		
	);	

$pdf = new Pdf($options);	

On the footer.html, the <span class="webpage"></span> still prints out the old value.

**Comment by mikehaertl** [comment]
What is the generated command string? You can check with `echo (string) $pdf->getCommand()`

**Comment by newpen** [comment]
Where should I put the code? I only get `wkhtmltopdf` when I `echo (string) $pdf->getCommand(); `

**Comment by mikehaertl** [comment]
Put it right after you created the pdf.

**Comment by newpen** [comment]
I see this (I replaced some personal information) : 

`wkhtmltopdf --encoding 'UTF-8' --header-left 'My Document' --header-right '[page]/[toPage]' --header-spacing '15' --enable-toc-back-links --margin-top '3cm' --margin-right '0cm' --margin-bottom '2cm' --margin-left '0' --replace '{webpage}' 'http://www.mysite.com' --footer-html 'footer.html' cover 'www.mysite.com/cover' toc --disable-dotted-lines 'www.mysite.com/page' '/tmp/tmp_wkhtmlto_pdf_LSrPwG.pdf'`

But the <td class="webpage"></td> on my footer.html still prints out the old value

**Comment by mikehaertl** [comment]
The command is correctly generated, so it's not a problem with this library. You should probably first try to make it work with `wkhtmltopdf` on the command line. I'm not sure, that the `replace` feature works with a header like this.

**Comment by newpen** [comment]
I can do it now, but by setting a whole new variable, and print it out on the footer.html

`'replace' => array(
	'myvar' => 'My String'
),`

**Comment by siddiqlm** [comment]
I updated the javascript on the footer.html as mentioned [here](https://stackoverflow.com/a/38625082/1591338)

```
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <script>
      function substitutePdfVariables() {

          function getParameterByName(name) {
              var match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
              return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
          }

          function substitute(name) {
              var value = getParameterByName(name);
              var elements = document.getElementsByClassName(name);

              for (var i = 0; elements && i < elements.length; i++) {
                  elements[i].textContent = value;
              }
          }

          ['username'/*, 'topage', 'page',.. etc and any variable you would want to replace */]
              .forEach(function(param) {
                  substitute(param);
              });
      }
  </script>
  </head>
  <body onload="substitutePdfVariables()">
    <span class="username"></span>
  </body>
</html>
```
and the options array like this

```
$options = array(
        'header-html' => $header_url, // new File(file_get_contents($header_url), '.html'),
        'footer-html' => $footer_url, //new File(file_get_contents($footer_url), '.html'),
        'replace' => array(
          'username' => 'My username'
        ),
);
```

With this javascript, it is working fine with the command also. 

`"wkhtmltopdf" --header-html http://yourwebsite/header.html --footer-html http://yourwebsite/footer.html --replace username 'My username' "http://yourwebsite/ur" "test.pdf"`
