### ISSUE TITLE
Header with wkhtmltopdf but not with phpwkhtmltopdf

### ISSUE THREAD

**Issue by melino** [mikehaertl/phpwkhtmltopdf#110]
When adding a header-html or footer.html (string, URL or file) it is not included in the PDF.

When pasting the output of ```$pdf->getCommand()->getExecCommand()``` to the command line, everything works as expected.

After copying the project to another Windows environment, the header was included there somehow.
Using OS X, the header-html was only included when using the command line again.

```'header-right' => 'Page [page] of [toPage]',``` works on all machines, it's the html that is ignored in 2 of 3 environments.

There is no error message. That's why we are lost now and kindly asking you to suggest the next step to debug.

**Comment by chavdamahesh** [comment]
I have faced the same issue, I setup wkhtmltopdf in my Windows 8 environment. But when I use php script to generate PDF, it doesn't do anything. Through command line it works fine.

Here is the code snippet,

require __DIR__.'/vendor/autoload.php';
require_once(__DIR__.'/vendor/mikehaertl/phpwkhtmltopdf/src/Pdf.php');
use mikehaertl\wkhtmlto\Pdf;

$outFile = __DIR__.'/tmp/test.pdf';

$pdf = new Pdf(array(
	// 'print-media-type',
	// 'no-outline',		 // Make Chrome not complain
	// 'margin-top'	=> 0,
	// 'margin-right'  => 0,
	// 'margin-bottom' => 0,
	// 'margin-left'   => 0,
	'orientation' => 'landscape',
	// 'header-html' => '<h1>Header</h1>',
	// 'binary' => $binary,

	//'header-html' => __DIR__.'/tmp/test.html',
	// 'footer-html' => '/Users/Sebastian/test.html',
	// 'header-right' => 'Page [page] of [toPage]',

	// Default page options
	// 'disable-smart-shrinking',
	// 'user-style-sheet' => 'pdf.css',
));
$pdf->tmpDir = __DIR__.'/tmp/';
$pdf->binary = 'C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf';

$pdf->addPage('http://google.com');
$pdf->saveAs($outFile);
$pdf->send();

**Comment by mikehaertl** [comment]
@melino Can you show some code? What are you adding as `header-html`, is it raw HTML, a URL or some filename?

**Comment by melino** [comment]
@mikehaertl I have tried them all, string, URL or file. For testing I now use a html file with nothing than the word ```Test```.

```
$pdf = new Pdf(array(
	'header-html' => __DIR__.'/tmp/test.html',
));
$pdf->tmpDir = __DIR__.'/tmp/';
$pdf->binary = __DIR__.'/vendor/wkhtmltopdf';
$pdf->addPage('http://wkhtmltopdf.org/usage/wkhtmltopdf.txt');
$pdf->send();
```
also tried:
```
$pdf->saveAs(__DIR__.'/tmp/test.pdf');
```

This is how the the PDF looks using PHP:
![php](https://cloud.githubusercontent.com/assets/4263666/8391770/d3bfa23e-1cce-11e5-8c67-c57a38380bc3.png)


using ```error_log($pdf->getCommand()->getExecCommand());``` the php_error.log gives:
```/Users/Sebastian/Websites/git/turbine/api/statement/vendor/wkhtmltopdf --header-html '/Users/Sebastian/Websites/git/turbine/api/statement/tmp/test.html' 'http://wkhtmltopdf.org/usage/wkhtmltopdf.txt' '/Users/Sebastian/Websites/git/turbine/api/statement/tmp/tmp_wkhtmlto_pdf_Hs6MB7.pdf'```

Pasting this in the OS X Terminal, the PDF looks like:
![command](https://cloud.githubusercontent.com/assets/4263666/8391771/dc6f58f2-1cce-11e5-9064-f39cd9468517.png)

**Comment by mikehaertl** [comment]
Sorry, I don't really have an idea. If the command works on the command line, it should also work from PHP. Have you tried to set the `useExec` option in the `commandOptions`? It sometimes helps to solve misterious issues on Win.

**Comment by melino** [comment]
Thanks to you reply, I investigated even deeper and found out, that setting a margin-top on the machines that did not show the header-html in php, let it be there.
So somehow in some environment the built in margin-top (when not set) leads to different results in regards to the header-html.
On those machines ```margin-top => 1```, shows exactly 1px of the header. So in those environments the ```margin-top``` musst be set to the hight of the header-html, or more if you want some additional white space.
Strange, but happy to be able to work further with phpwkhtmltopdf again.

**Comment by mikehaertl** [comment]
@melino Ok, so I'm closing this. You can reopen it, if you think there's still something to fix here.

**Comment by ahmedfahmy2003** [comment]
Same Issue , but didn't solve by setting the top margin
