### ISSUE TITLE
Cannot generate pdf - The exit status code '139'

### ISSUE THREAD

**Issue by bemon** [mikehaertl/phpwkhtmltopdf#114]
Hi,

Im trying to generate pdf from valid HTML, no php warnings, everything is OK at html side. But wkhtml throws: 
something went wrong "The exit status code '139'
What is interesting to me is: Printing pages (6/6) .... Page 4 of 3 and then segmentation fault.

Any idea what is going on ? On ubuntu 14 error occurs, on windows all is ok. Lib version is 12.2.1.

**Comment by mikehaertl** [comment]
Hmm, I'm afraid I can't help much with segementation faults. Can you describe what you're doing? how many pages, etc? maybe some example code to reproduce?

**Comment by mikehaertl** [comment]
Also what is the command generated (`echo $pdf->getCommand()`) and does it work on the command line?

**Comment by mikehaertl** [comment]
Closing this for now as I can't really help much if `wkhtmltopdf` fails with a segmentation fault. It's probably related to some system specific setup.
