### ISSUE TITLE
use updated URL for wkhtmltopdf downloads

### ISSUE THREAD

**Issue by ashkulz** [mikehaertl/phpwkhtmltopdf#115]
Hello,

wkhtmltopdf has [moved the downloads provider](https://groups.google.com/d/msg/wkhtmltopdf-general/wZwTUol3mXI/GNVeyrKDdqIJ) from SourceForge to gna.org. As mentioned in the linked message, all earlier downloads have been removed from SourceForge and you are strongly advised to migrate to the new URLs. The following files in your repository will need to be updated:

* .travis.yml

It is recommended to either subscribe to the [mailing list](https://groups.google.com/forum/#!forum/wkhtmltopdf-general) or [Twitter feed](https://twitter.com/wkhtmltopdf) to receive updates on new releases and further changes.

Thanks,
wkhtmltopdf maintainer

**Comment by mikehaertl** [comment]
That's really good news. All I can say is: Finally ;). I had some hard time to find a persistent download URL for wkhtmltopdf. Fixed now.

BTW I didn't know, that the wkhtmltopdf team has an eye on my little project here. Thanks for letting me know!

**Comment by ashkulz** [comment]
Well, I did submit a PR (#89) a while back. TBH, this issue (and many others) were auto-reported by a script which detected usage of the SourceForge URLs at github -- spent a day or two for it. There was no announce-only forum to get the message out previously, hence the twitter link.

I've been meaning to get off SourceForge for a long time now, but had to find a good provider beforehand :smile:
