### ISSUE TITLE
Could not find package for installation

### ISSUE THREAD

**Issue by alec-w** [mikehaertl/phpwkhtmltopdf#117]
Despite having a completely fresh install of composer with no defaults changed I get the following message when running `composer require mikehaert1/phpwkhtmltopdf` (in a completely empty directory)

    [InvalidArgumentException]
    Could not find package mikehaert1/phpwkhtmltopdf at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by mikehaertl** [comment]
I can't reproduce that. There are many stable releases. You can verify this also on packagist:

https://packagist.org/packages/mikehaertl/phpwkhtmltopdf

I've also tried again locally and it works. Maybe your connection was down or some problem with packagist. But nothing I can fix here.

**Comment by mikehaertl** [comment]
Oh, and is this a `1` instead of an `l` on the end of `mikehaertl`? ;)

**Comment by alec-w** [comment]
The `1` instead of `l` was it! Thanks, I obviously just can't read...
