### ISSUE TITLE
Just... a blank page

### ISSUE THREAD

**Issue by Popoliito** [mikehaertl/phpwkhtmltopdf#118]
Hello,
So, I'm using archlinux, I've installed wkhtmltopdf on my system and it's working correctly.
I've installed composer, and executed the following commands : 
    
    composer init
    composer require mikehaertl/phpwkhtmltopdf

And there is my php code  : 
````
 <?php
ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(E_ALL);

require __DIR__ . '/vendor/autoload.php';

ob_start();
require('fichier.htm');

$content = ob_get_clean();

// You can pass a filename, a HTML string or an URL to the constructor
$pdf = new Pdf($content);

// On some systems you may have to set the binary path.
// $pdf->binary = 'C:\...';

$pdf->send();
````

But Firefox doesn't display anything. The only thing I get is a blank page.
It even does not change the header type of the page (stay text//html).

Any idea what is going on (or what is not going on...) ?

**Comment by mikehaertl** [comment]
https://github.com/mikehaertl/phpwkhtmltopdf#error-handling

**Comment by Popoliito** [comment]
Oh thank you, I managed to solve my problem, I had to install xvfb on my machine.
I'm really sorry, I missed this part of the readme...

**Comment by ZAJDAN** [comment]
Hello,
now I am facing same problem even I have add into my code:

if (!$pdf->send()) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
}

$content = $pdf->toString();
if ($content === false) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
}
