### ISSUE TITLE
Stuck at Loading pages (1/6) [> ] 0% [======> ] 10% in browser

### ISSUE THREAD

**Issue by markosalkovic** [mikehaertl/phpwkhtmltopdf#120]
Hi,

I'm using 'Single page PDF' example with adjusted paths and autoloader added, it works when run from console but when I run it in a browser it returns "Loading pages (1/6) [> ] 0% [======> ] 10%" and generates no pdf files. I tried $pdf->send and $pdf->saveAs same issue.

Any ideas?

**Comment by mikehaertl** [comment]
You could try to set `'useExec' => true` in the [`commandOptions`](https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options). If that doesn't help, I'm sorry, but there's nothing else I can do. `wkhtmltopdf` sometimes behaves strange, especially when loading content from a remote URL.

**Comment by crgrove** [comment]
I'm having the exact same problem.  I tried setting useExec to true and it didn't help.

**Comment by markosalkovic** [comment]
setting useExec didn't work for me either, but I tried running wkhtmltopdf trough browser in multiple different ways and got the same error every single time, so this is not a phpwkhtmltopdf
 issue

**Comment by seanick39** [comment]
Spent hours looking up the solution to this. For anyone still facing this problem, give this shot: I'd been trying to convert a simple local html file to pdf with wkhtmltopdf in cmd, but it used to freeze at Loading 10% for at least two minutes. Transferred the executable and html files to another machine, and it worked without problems. I proceeded to uninstall wkhtmltopdf from 'Add or remove programs', delete the folder in Program Files, and delete its binary path from %PATH%, and then used just the wkhtmltopdf.exe without installation, and it started working again.
Hope this helps someone.

**Comment by fmonts** [comment]
Same issue on a Ubuntu 20.04, days ago it was working, but now it broke without any change made. 

reinstalling didn't work, it still get stuck at 
`Loading pages (1/6)
[===========>                                                ] 19%`

If I run a strace:

``` strace /usr/local/bin/wkhtmltopdf --encoding utf-8 --images knp_snappy63b41bd8de5ba3.36685105.html knp_snappy63b40f25efde63.13123325.pdf ```

it blocks here:

```
lstat("/usr/share/fonts/opentype/urw-base35/NimbusSans-Regular.otf", {st_mode=S_IFREG|0644, st_size=82264, ...}) = 0
openat(AT_FDCWD, "/usr/share/fonts/opentype/urw-base35/NimbusSans-Regular.otf", O_RDONLY) = 14
fcntl(14, F_SETFD, FD_CLOEXEC)          = 0
fstat(14, {st_mode=S_IFREG|0644, st_size=82264, ...}) = 0
mmap(NULL, 82264, PROT_READ, MAP_PRIVATE, 14, 0) = 0x7fedf9f7d000
close(14)                               = 0
brk(0x555994081000)                     = 0x555994081000
lstat("/usr/share/fonts/opentype/urw-base35/NimbusSans-Bold.otf", {st_mode=S_IFREG|0644, st_size=83264, ...}) = 0
openat(AT_FDCWD, "/usr/share/fonts/opentype/urw-base35/NimbusSans-Bold.otf", O_RDONLY) = 14
fcntl(14, F_SETFD, FD_CLOEXEC)          = 0
fstat(14, {st_mode=S_IFREG|0644, st_size=83264, ...}) = 0
mmap(NULL, 83264, PROT_READ, MAP_PRIVATE, 14, 0) = 0x7fedf9f68000
close(14)                               = 0
brk(0x5559940a2000)                     = 0x5559940a2000
brk(0x5559940c3000)                     = 0x5559940c3000
select(4, [3], [], [], NULL)            = 1 (in [3])
read(3, "\0", 16)                       = 1
read(3, 0x7ffeeb9242d0, 16)             = -1 EAGAIN (Resource temporarily unavailable)
select(4, [3], [], [], NULL

```

Any idea? That odf file exists and is readable...

**Comment by mikehaertl** [comment]
@fmonts It seems you also have this problem if you use `wkhtmltopdf` without our library, right? In that case you should better send your report to the wkhtmltopdf project. This here is only a PHP wrapper around the CLI tool.
