### ISSUE TITLE
Failed without error message

### ISSUE THREAD

**Issue by charlie-lk** [mikehaertl/phpwkhtmltopdf#121]
The following test code fails without an error:

I have the same issue. Here is my test code.

```php
<?php

require_once __DIR__.'/../vendor/autoload.php';

use mikehaertl\wkhtmlto\Pdf;

// You can pass a filename, a HTML string or an URL to the constructor
$pdf = new Pdf('<html><head></head><body>Hello pdf</body></html>');

// On some systems you may have to set the binary path.
 $pdf->binary = 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe';

if (!$pdf->saveAs('user/page.pdf')) {
    echo $pdf->getError();
}
?>
```
I have the "write" access to the "/user" directory and I can write a test file to it in the same script.

I'm on Windows 8.1 32 bit
PHP 5.5.12
Apache 2.4.9

What could be the reason?

**Comment by mikehaertl** [comment]
Your problem here seems to be related to the Windows OS. I'm sorry, that I can't really help much with this: I don't use Windows. You could try to set the `'useExec' => true` option in the `commandOptions`. This will use a different method to execute `wkhtmltopdf`. For more options, check: https://github.com/mikehaertl/php-shellcommand

If you can locate the problem and supply a fix, I'm happy to include it.

**Comment by alec-w** [comment]
Does `wkhtmltopdf` have write access to that directory? When using `wkhtmltopdf` from the command line and trying to save the PDF it appeared to not exist - but it was saving to `Uses/MyUser/AppData/Roaming/....` Perhaps it failed silently because it succeeded in writing to there instead?

**Comment by mikehaertl** [comment]
Also notice, that during PDF generation a temporary file is written to disk (see https://github.com/mikehaertl/php-tmpfile). By default this will use the return value of [`sys_get_temp_dir`](http://php.net/manual/en/function.sys-get-temp-dir.php). So make sure you also have write access there.

**Comment by evandroprogram** [comment]
I solved this problem uninstalling `wkHtmlToPdf MSVC 2013` and using the version `MinGW-w64` of the wkHtmlToPdf. I recommend to edit the README.md to include this information for Windows users. Btw, congratulations for the project!

**Comment by radmax** [comment]
I had same issue. Switch `'useExec' => true` helped me to track down bad URL for CSS file.

**Comment by dagulo** [comment]
I was able to make this work on Windows by setting the full path of the binary

`$pdf = new Pdf('http://www.google.com');
  $pdf->setOptions(['binary' => 'C:\wk\bin\wkhtmltopdf.exe' ]);`
