### ISSUE TITLE
Could not create PDF: sh: wkhtmltopdf: command not found'

### ISSUE THREAD

**Issue by salluri27** [mikehaertl/phpwkhtmltopdf#122]
Hi Mike,
When I am trying to create a pdf using phpwkhtmltopdf I am getting this below mentioned error.

Fatal error: Uncaught exception 'Exception' with message 'Could not create PDF: sh: wkhtmltopdf: command not found' 

I have wkhtmltopdf installed on my linux redhat server. I tried to create sample pdf using commanline. It worked.

Should I have Xvfb installed on the linux server for this wrapper to work?

Thanks,
Sri

**Comment by mikehaertl** [comment]
You have to set the path to `wkhtmltopdf` in the `binary` option:
https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options

**Comment by salluri27** [comment]
Thanks a lot Mike. It worked.

**Comment by salimakhtar786** [comment]
I am facing the following issue with my ubantu-16.04
```
Error: /bin/bash: wkhtmltopdf: command not found 
```

I used the `which wkhtmltopdf` command and got the following:
```
/usr/local/bin/wkhtmltopdf
```

And I also checked the $PATH variable using `echo $PATH` its giving the following output:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

How to fix this?

**Comment by mikehaertl** [comment]
@salimakhtar786 Please check my comment above about setting the `binary` option.

**Comment by salimakhtar786** [comment]
I am using `MeteorJS` Framework

**Comment by davidiwezulu** [comment]
Hello get the error "This site can’t be reached" when calling the wkhtmltopdf. I'm currently using larvel server - artisan serve

**Comment by plashenkov** [comment]
For those who gets "sh: wkhtmltopdf: command not found". Try to stop and start apache (or other server you use).

**Comment by alejandromartincruz** [comment]
Not sure how to set the path to wkhtmltopdf in the binary option. can you write an example please?

**Comment by Error-freeIT** [comment]
@alejandromartincruz 

To obtain the binary path on macOS open Terminal and run: which wkhtmltopdf

`<?php
require __DIR__ . '/vendor/autoload.php';

use mikehaertl\wkhtmlto\Pdf;

$options = array(
	'binary' => '/usr/local/bin/wkhtmltopdf'
);

// You can pass a filename, a HTML string, an URL or an options array to the constructor
$pdf = new Pdf('https://google.com');
$pdf->setOptions($options);

// On some systems you may have to set the path to the wkhtmltopdf executable
// $pdf->binary = 'C:\...';
if (!$pdf->saveAs('output/page.pdf')) {
    $error = $pdf->getError();
    // ... handle error here
    echo($error);
}
?>`
