### ISSUE TITLE
How to correctly change path to execute

### ISSUE THREAD

**Issue by amylashley** [mikehaertl/phpwkhtmltopdf#124]
Not an issue but a question. I've installed this library using composer but need to update the path to the command. How can I do this properly without editing your actual code?  The actual wkhtmltopdf is installed in /usr/local/bin. Adding this to the include_path in php.ini doesn't seem to do it. Thanks!

**Comment by mikehaertl** [comment]
Please check the `binary` option:

https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options

**Comment by amylashley** [comment]
Perfect! Thanks for the speedy reply!
