### ISSUE TITLE
commandOptions either not working or under-documented

### ISSUE THREAD

**Issue by Wasaabi404** [mikehaertl/phpwkhtmltopdf#128]
Whenever I call 
`$image = new Image('http://' . $url . '/');`
`$image->binary = '/usr/local/bin/wkhtmltoimage';`
`$image->commandOptions = array('height' => 100);`

I receive: 

`Uncaught exception 'Exception' with message 'Unknown configuration option 'height'' in [..]includes/vendor/mikehaertl/php-shellcommand/src/Command.php:130`
`Stack trace:`
`#0 [..]/includes/vendor/mikehaertl/php-shellcommand/src/Command.php(108): mikehaertl\\shellcommand\\Command->setOptions(Array)`
`#1 [..]/includes/vendor/mikehaertl/phpwkhtmltopdf/src/Image.php(169): mikehaertl\\shellcommand\\Command->__construct(Array)`
`#2 [..]/includes/vendor/mikehaertl/phpwkhtmltopdf/src/Image.php(220): mikehaertl\\wkhtmlto\\Image->getCommand()`
`#3 [..]/includes/vendor/mikehaertl/phpwkhtmltopdf/src/Image.php(132): mikehaertl\\wkhtmlto\\Image->createImage()`
`#4 [..]/imagemaker.php(13): mikehaertl\\wkhtmlto\\Image->send()`
`#5 {main}
  thrown in [..]/includes/vendor/mikehaertl/php-shellcommand/src/Command.php on line 130`

I have tried many formation of the "commandOptions" suche as `--height` etc... but it gives me the same stack trace.  I cannot find any example of correct usage for these options ... and all I want is to set a maximum height/width of the generated thumbnail...

Is this is a problem, or am I just using it all wrong?

**Comment by mikehaertl** [comment]
`commandOptions` are the options passed to https://github.com/mikehaertl/php-shellcommand. You should use `setOptions()` instead. 

Please carefully read these two sections again:

https://github.com/mikehaertl/phpwkhtmltopdf#setting-options
https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options

**Comment by Wasaabi404** [comment]
Thank you... it was unclear that `setOptions()` would handle a width or height declaration.  As it stands, the two declarations within `setOptions()` act more like a "crop" function rather than an image sizing command - but I am able to deal with that better than trying to manage a full site capture.

I appreciate the information, Thank you again.
