### ISSUE TITLE
is composer needed?

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#129]
Hello,
I would like to use on my project your library, but I am not sure if is need to install composer
now when I am trying install it I get error:
root@debian-zdenek:/home/zdenek# php composer.phar require /mnt/databox/www//pdf/phpwkhtmltopdf-master/
                                                                            
  [InvalidArgumentException]                                                   
  Could not find package /mnt/databox/www/pdf/phpwkhtmltopdf-master/ at any version for your minimum-stability (stable). Check the  
   package spelling or your minimum-stability

**Comment by mikehaertl** [comment]
Not sure what you try to do here. The correct command to install a composer package is `composer require mikehaertl/phpwkhtmltopdf`. I'm sorry, but I can not assist you with basic composer usage. Please check the composer manual or some tutorials to learn how to use composer.

**Comment by ZAJDAN** [comment]
ok thank You and without composer is not a way to use your library? I ask because now I am playing on my own server, but in future on public hosting is not possible to make such similar steps.

**Comment by mikehaertl** [comment]
You can install with composer locally and then upload the complete `vendor/` directory to your host. Then you don't need composer there.

**Comment by ZAJDAN** [comment]
Thank You...good to know for future
and now composer correctly done:
Using version ^2.1 for mikehaertl/phpwkhtmltopdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mikehaertl/php-shellcommand (1.2.0)
    Downloading: 100%         

  - Installing mikehaertl/php-tmpfile (1.0.0)
    Downloading: 100%         

  - Installing mikehaertl/phpwkhtmltopdf (2.1.1)
    Downloading: 100%         

Writing lock file
Generating autoload files
root@debian-zdenek:/home/zdenek#
