### ISSUE TITLE
Warning: tempnam(): open_basedir restriction in effect.

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#130]
please what I have wrong?
do I need to allow some such directory?
Warning: tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/mnt/databox/www/myweb) in /mnt/databox/www/myweb/pdf/vendor/mikehaertl/php-tmpfile/src/File.php on line 38

in virtualhost config I have:
php_admin_value open_basedir /mnt/databox/www/myweb

**Comment by ZAJDAN** [comment]
I have add new row into virtualhost config:
php_admin_value open_basedir /mnt/databox/www/myweb/pdf/vendor/mikehaertl/php-tmpfile/src

and looks that the problem disappears

**Comment by ZAJDAN** [comment]
but now in appache2 log I see:
[Tue Nov 10 12:36:14.547387 2015] [:error] [pid 23308] [client 192.168.6.122:50496] PHP Warning:  Unknown: open_basedir restriction in effect. File(/mnt/databox/www/myweb/pdf/test.php) is not within the allowed path(s): (/mnt/databox/www/myweb/pdf/vendor/mikehaertl/php-tmpfile/src) in Unknown on line 0

**Comment by mikehaertl** [comment]
This problem has nothing to do with my library. PHP is configured to not let you write to the PDF output directory. Please use Google to solve this kind of problems, for example here:

http://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths
