### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#132]
Hello,
please do you have any tip for reliable way to render QR code?
I am trying to use phpqrcode, now I just prepare a variable:

``` $svgCode = QRcode::svg('PHP QR Code :)');  ```

but the problem is, that the QRcode image is rendered even i do not use the variable or echo
and unfortunately is rendered the QR image only without my html

Thank You

**Comment by mikehaertl** [comment]
Sorry, this has nothing to do with my library. Please use google for this kind of questions.

**Comment by ZAJDAN** [comment]
I am sorry, I just thought, that You have some experience in similar use.
