### ISSUE TITLE
Parse error: syntax error, unexpected 'use' (T_USE)

### ISSUE THREAD

**Issue by juliogtz** [mikehaertl/phpwkhtmltopdf#133]
I have this code:
require_once '../vendor/autoload.php';

				use mikehaertl\wkhtmlto\Pdf;
				
				$pdf = new Pdf('/path/to/page.html');

				// On some systems you may have to set the binary path.
				// $pdf->binary = 'C:\...';

				$pdf->addPage('<p>Que onda!!!!</p>');

				if (!$pdf->saveAs("../".$ruta.".pdf")) {
				    echo $pdf->getError();
				}

This is the result:
Parse error: syntax error, unexpected 'use' (T_USE) in /home/nitico5/public_html/facturacion/niticolor-facturacion/3.php on line 529

Do you have an idea? How can I fix that?
Thanks.

**Comment by mikehaertl** [comment]
Sorry, this is not really related to my library. Please use google to solve this kind of problems.
