### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#135]
Hello
I insert QR code into my html which I render via phpwkhtlto pdf
The PDF is not rendered and browser just show me QR code and source code of the final page contains a few errors.
```
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /mnt/databox/www/myweb/pdf/phpqrcode-master/qrvect.php:147) in <b>/mnt/databox/www/myweb/pdf/wkhtmltopdf/mikehaertl/php-tmpfile/src/File.php</b> on line <b>64</b><br />
<br />
```
please what do You think?   the problems depends on wkhtmltopdf or phpqrcode or phpwkhtmltopdf?

**Comment by mikehaertl** [comment]
Sorry, but the problem you have is not directly related to my library and I can not assist you building your app. The error you see is usually generated if a  `header()` (this happens when you call `send()` on the PDF) but there already was some output to the browser. That's all I can say.
