### ISSUE TITLE
php page as src in <img>

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#136]
is possible use php page as src in ```<img>``` tag ...?
in my case I try to get picture of QR code which is generated from another page, but unfortunately in PDF is rendered blank frame only:
```
$pdf = new Pdf;
$pdf->addPage('
<html>
<head>
</head>
<body>
<div id="qr-picture">
<img src="/myweb/pdf/qrcode.php?type=TEST&format=TEST2"/>
</div>
</body>
</html>
');
```
```
<?php
require_once ('phpqrcode-master/qrlib.php');
$type = $_GET['type'];
$format = $_GET['format']
header("Content-Type: image/svg");
$svg_QR_Code = QRcode::svg($product, $format);
echo $svg_QR_Code;
?>
```

**Comment by mikehaertl** [comment]
Sorry, I can't help you here. Try if it works with `wkhtmltopdf` on the command line. If it does, it also should work in my library.

**Comment by ZAJDAN** [comment]
You have true, 
I Have tried to render such page from command line and result is same, so this is a problem in wkhtmltopdf.
Thank You
