### ISSUE TITLE
header-html and footer-html

### ISSUE THREAD

**Issue by snagytx** [mikehaertl/phpwkhtmltopdf#137]
If I have:

    'header-html' =>  $r->headerHTML,
    'footer-html' =>  $r->headerHTML

in the options and this is html code, not an html filename, the footer-html is added to the PDF while the header-html is not added to the PDF.

**Comment by mikehaertl** [comment]
I'm pretty sure, that the header HTML is there. It's probably just a problem with styling. So the header is maybe rendered outside the page area and thus not visible in the PDF. Try a very simple header HTML first.

**Comment by snagytx** [comment]
I'm not sure what can be more simple than:

    <html><head></head><body>123</body></html>

plus I have :

            $options = array(
                'no-outline',         // Make Chrome not complain
                'margin-top'    => 25,
                'margin-right'  => 0,
                'margin-bottom' => 5,
                'margin-left'   => 0,
                'disable-smart-shrinking',
                'header-html' =>  $r->headerHTML,
                'footer-html' =>  $r->headerHTML
            );
            $pdf->setOptions($options);

**Comment by mikehaertl** [comment]
The library does nothing complex here: If you pass a HTML string to `header-html` it will generate a temporary file for it and pass this to `wkhtmltopdf`. Maybe you can try it on the command line? Also try without any page options (margins, etc.)
