### ISSUE TITLE
Warning: rename(,.pdf) / unlink(.pdf): No such file or directory

### ISSUE THREAD

**Issue by tschmidt01** [mikehaertl/phpwkhtmltopdf#138]
Warning:
    
    Warning: rename(,.pdf): No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/p/vendor/mikehaertl/php-tmpfile/src/File.php on line 41
    Warning: unlink(.pdf): No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/p/vendor/mikehaertl/php-tmpfile/src/File.php on line 52

Code:

    <?php

    // load Composer
    require __DIR__ . '/vendor/autoload.php';

    use mikehaertl\wkhtmlto\Pdf;

    $options = array(
        "binary" => "/usr/local/bin/wkhtmltopdf",
        'no-outline'
    );

    $pdf = new Pdf($options);
    $pdf->addPage('/index.html');
    $pdf->send();

    ?>

**Comment by mikehaertl** [comment]
Weird. Can you do some debugging? The relevant lines are in `vendor/mikehaertl/php-tmpfile/src/File.php` here:

https://github.com/mikehaertl/php-tmpfile/blob/master/src/File.php#L30

This line is called from here:
https://github.com/mikehaertl/phpwkhtmltopdf/blob/master/src/Pdf.php#L239

As you see, there is a call to `tmpfile()` in the constructor of `File`. Something seems to go wrong in your setup.

**Comment by mikehaertl** [comment]
Ok, it's probably that you don't have write permission to the tmp directory that `sys_get_temp_dir()` returns. Check the output of `echo \mikehaertl\php-tmpfile\File::getTempDir()` and if PHP has write permission to that directory.

**Comment by tschmidt01** [comment]
Sadly im not really familiar with PHP, usually developing in Java. Other infos to my setup: OSX 10.11, Apache running under XAMPP, CHMOD 777 set to the whole htdocs folder.

**Comment by tschmidt01** [comment]
Where's the temp directory located, which is used by PHP?

**Comment by tschmidt01** [comment]
> Check the output of echo \mikehaertl\php-tmpfile\File::getTempDir() and if PHP has write permission to that directory.

Ok, i'll try that and update the issue with the relevant information a litte later.

**Comment by mikehaertl** [comment]
Please check the documentation of `tempnam()` here: http://de2.php.net/manual/en/function.tempnam.php

> Creates a file with a unique filename, with access permission set to 0600, in the specified directory. If the directory does not exist or is not writable, tempnam() may generate a file in the system's temporary directory, and return the full path to that file, including its name.

So usually this method should never fail. Because if the provided directory is not writeable, it will fall back to the system's temp dir, which should *always* be writeable. So something must be wrong with your setup. Unfortunately I can not help you with that.

I'm closing this for now. Feel free to reopen, if you still think, this is a bug in this library.
