### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by babeuloula** [mikehaertl/phpwkhtmltopdf#141]
Hello, 

The accented characters does not appear in header or footer.

Ex: Jérémy => Jrmy

**Comment by mikehaertl** [comment]
There are some notes on how to use UTF-8 in the README in this section:
https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options

You can find the full discussion in this issue: https://github.com/mikehaertl/phpwkhtmltopdf/issues/108

Please also let me know, if this fixed your problem.

**Comment by babeuloula** [comment]
Its works, I use this `setlocale(LC_CTYPE, "fr_FR.UTF-8");`

Thanks

**Comment by C-Duv** [comment]
I had issues with:
* PHP's `escapeshellarg()` breaking path that have an accented character
* AND `wkhtmltopdf` failing to process HTML files using paths (for images, CSS, JavaScript, ...) with accented character.

Used `setlocale(LC_CTYPE, "xx_YY.UTF-8")` to fix the first issue, and the following to fix the second
```PHP
$pdf = new Pdf([
    'binary' => ...,
    'commandOptions' => [
        'procEnv' => [
            'LANG' => setlocale(LC_CTYPE, 0),
        ],
    ],
]);
```

Hop that helps
