### ISSUE TITLE
PDF Generation Slow in Production Environment

### ISSUE THREAD

**Issue by matthewbeasley** [mikehaertl/phpwkhtmltopdf#143]
In my local vagrant environment pdf generation takes only about 2 seconds:
![image](https://cloud.githubusercontent.com/assets/9603479/11819033/5b58dd70-a323-11e5-8d9f-e156027bcd3f.png)

We also have a development server which has similar results:
![image](https://cloud.githubusercontent.com/assets/9603479/11819369/1103ae10-a325-11e5-88ef-9f44ff388d9c.png)

However on the production server it takes over 40 secs. 
![image](https://cloud.githubusercontent.com/assets/9603479/11819227/562b4b7a-a324-11e5-8337-73d71f2763bd.png)

All servers use Ubuntu 14.04 and Apache 2.4.7. The only difference seems to be that the production server is behind a load balancer. 

This is the setup I am using:
```php
public function pdf(){
        $title = $this->input->post('export_title', TRUE);
        $data['title'] = preg_replace('/_/', ' ', $title);

        $templateID = $this->input->post('export_template_id', TRUE);
        $answerID   = $this->input->post('export_answer_id', TRUE);
        $data['form'] = $this->getAnsweredForm($templateID, $answerID);

        $html =  $this->load->view('pdf/header', '', true);
        $html .= $this->load->view('pdf/view_custom_form', $data, true);

        $pdf = new mikehaertl\wkhtmlto\Pdf(array(
            // Explicitly tell wkhtmltopdf that we're using an X environment
            'use-xserver',

            // Enable built in Xvfb support in the command
            'commandOptions' => array(
                'enableXvfb' => true,
        )));

        $pdf->addPage($html);
        
        if(!$pdf->send("$title.pdf")){
            echo $pdf->getError();
        }
    }
```

I've also tried just passing in 'google.com' with similar results. We use CodeIgniter and I tried passing in the URI of a page which resulted in it being generated appropriately on my vagrant but 'Failure without error message' on the production server. 

Any debugging tips would be greatly appreciated. I've looked and haven't found anyone with similar issues, so I was hoping you could help here.

**Comment by mikehaertl** [comment]
Sorry, no idea. I also don't think, that this is a bug or something we could fix here. So I'm closing this.
