### ISSUE TITLE
Set filename of rendered pdf?

### ISSUE THREAD

**Issue by 7immy** [mikehaertl/phpwkhtmltopdf#144]
Is there any way to set the file name of the rendered pdf? Currently, if I view the output in a browser and go file>save it just has a generic file filename called "download". I'd like to be able to customise this so something like "myFileName.pdf".

I know I can do something like `$pdf->send("myFileName.pdf")` but with this method it sets the page to auto download instead of previewing the page in the browser.

Is there any feature for this?
Thanks in advance :)

**Comment by mikehaertl** [comment]
Try `$pdf->send('bla.pdf', true)`. Also see here: https://github.com/mikehaertl/phpwkhtmltopdf/blob/master/src/Pdf.php#L161

**Comment by 7immy** [comment]
Thanks @mikehaertl 👍
