### ISSUE TITLE
proc_open()  exit code 

### ISSUE THREAD

**Issue by AlbyFernandez** [mikehaertl/phpwkhtmltopdf#145]
```
                $this->_exitCode = proc_close($process);
                if ($this->_exitCode!==0) {
                    $this->_error = $this->_stdErr ? $this->_stdErr : "Failed without error message: $command";
                    return false;
                }
```

in the php docs says : 
The proc_close() 
Returns the termination status of the process that was run. In case of an error then -1 is returned.

so, should be  
 if ($this->_exitCode < 0) {

**Comment by mikehaertl** [comment]
Usually a program exits with exit code 0 if there was no error. Anything else indicates an error. So the current implementation is correct. Do you have a use case, where this is not the case?

**Comment by prabhat2505** [comment]
If it tells about error then it should be like  "error message: $command"; not like $this->_stdErr : "Failed without error message: $command";If it fails then should throw exact exception
