### ISSUE TITLE
--replace option doesn't work in a page.

### ISSUE THREAD

**Issue by iOsama** [mikehaertl/phpwkhtmltopdf#146]
Hey, 

I have an issue which is "replace" option doesn't work with me, i tried all the solutions and there's no effect!

I give this option to my page: 

    $options = array(
        'replace' => array(
            'hello'    =>  'world'
         )
     );
     $pdf->addPage('page.html', $options);

and the subset of my html code: 
<script>

            function subst() {
                var vars = {};

                var valuePairs = document.location.search.substring(1).split('&');
                for (var i in valuePairs) {
                    var valuePair = valuePairs[i].split('=', 2);
                    vars[valuePair[0]] = decodeURIComponent(valuePair[1]);
                }
                var replaceClasses = ['hello'];

                for (var i in replaceClasses) {
                    var hits = document.getElementsByClassName(replaceClasses[i]);

                    for (var j = 0; j < hits.length; j++) {
                        hits[j].textContent = vars[replaceClasses[i]];
                    }
                }
            }
        </script>
   
    <body onload="subst()">

            <h1 class="hello"></h1>

     </body>

What the mistake in the code?
and is there a way to make a 'page.php' instead of 'page.html'.

Thanks.

**Comment by mikehaertl** [comment]
That's not an issue of this library. For a similar issue see #91.
