### ISSUE TITLE
i don't know how to set this up

### ISSUE THREAD

**Issue by Kendysond** [mikehaertl/phpwkhtmltopdf#147]
Hello,
please i'm new to this, i've used a couple of php pdf libraries but they are all too slow, seeing this one works give me some hope, i think i have setup composer on my system but when i used your test demo the page returned is blank, no errors so please how can i fix it thanks

**Comment by mikehaertl** [comment]
Please check the big note on top of the main page:

> **The wkhtmltopdf and - optionally - wkhtmltoimage command must be installed and working on your system.**

If `wkhtmltopdf` is not in your search path, you may have to set the path to the executable in the `binary` option, see here: https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options
