### ISSUE TITLE
How to set different page margin on first page in wkhtmltopdf? 

### ISSUE THREAD

**Issue by kamalsamra** [mikehaertl/phpwkhtmltopdf#148]

**Comment by mikehaertl** [comment]
This is not a bug. Please check the README and the manual of wkhtmltopdf.

**Comment by kamalsamra** [comment]
I already saw it but i have not found any solution for this.

**Comment by mikehaertl** [comment]
I'm sorry, but I can't provide support for wkhtmltopdf itself. This library is just a wrapper to make it easier to use it from PHP.
