### ISSUE TITLE
Problem in footer.php

### ISSUE THREAD

**Issue by salehST** [mikehaertl/phpwkhtmltopdf#150]
how can i support utf-8 encoding in footer.php
this is the site : http://minoticia.net/
please help...

**Comment by mikehaertl** [comment]
Check the options example here: https://github.com/mikehaertl/phpwkhtmltopdf#setting-options. You may also want to set a wrapper option as shown in the example here: https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options.

If that doesn't help, I don't know either.

**Comment by salehST** [comment]
Thank you @mikehaertl  it worked.
