### ISSUE TITLE
Command not found on Mac OSX

### ISSUE THREAD

**Issue by rodrigoguerrasa** [mikehaertl/phpwkhtmltopdf#151]
I am trying to use your wkthmltopdf wrapper but I am
getting the error:

sh: wkhtmltopdf: command not found

Wkhtmltopdf is surely installed since I can run it from anywhere (any
directory) using the command line.  

I have also tried setting the options to binary but still no luck.
$options = array('binary');
$pdf->setOptions($options);

My localhost is installed on my Mac (OS X Yosemite 10.10.5).

Can anyone help?

**Comment by mikehaertl** [comment]
You're using it wrong:

```
$options = array(
    'binary' => '/path/to/your/wkhtmltopdf',
);
```

**Comment by rodrigoguerrasa** [comment]
This may sound silly, but I can¹t find the path to wkhtmltopdf  I¹m sure
its installed since I run it on the command line (bash).  Any ideas?

From:  Michael Härtl <notifications@github.com>
Reply-To:  mikehaertl/phpwkhtmltopdf
<reply+0103dd3f7155c488101910cdf1d4c5b732930c767fdbb19a92cf0000000112e586f59
2a169ce081c7524@reply.github.com>
Date:  quarta-feira, 24 de fevereiro de 2016 11:57
To:  mikehaertl/phpwkhtmltopdf <phpwkhtmltopdf@noreply.github.com>
Cc:  Rodrigo Guerra <rodrigo.guerra@aleah.com.br>
Subject:  Re: [phpwkhtmltopdf] Command not found on Mac OSX (#151)


You're using it wrong:
$options = array(
    'binary' => '/path/to/your/wkhtmltopdf',
);

Reply to this email directly or view it on GitHub
<https://github.com/mikehaertl/phpwkhtmltopdf/issues/151#issuecomment-188290
961> .

**Comment by mikehaertl** [comment]
Try `whereis wkhtmltopdf` or `which wkhtmltopdf`.

**Comment by rodrigoguerrasa** [comment]
OK.  Got it to work.  On OS X the wkhtmltopdf is located in /usr/local/bin.

Even though the Terminal command line accepts the wkhtmltopdf from any directory, in php I found out that we must use the binary option set as:

`$options = array(
    'binary' => '/usr/local/bin/wkhtmltopdf',
);`

Thanks so much for your help.
