### ISSUE TITLE
Questions including css

### ISSUE THREAD

**Issue by cocomo** [mikehaertl/phpwkhtmltopdf#152]
Please: I am unhappy creating Image from Html containing one single external stylesheet (font-awesome). 

It seems that external css gets only included when I save the Html file inside a public directory of my web server AND give it a name with the postfix '.html'. I also have the impression it just doesn't matter if the Image gets instantiated from filename or url.

I would love to see Image generation 

- more dynamic: input html could be generated by a .php-file
- more secure or "in private": no source files in a publicly accessible folder of my website.

Can anyone confirm the limitations i'm facing? Or is there anything like a best practice for working with non trivial css? 

Here's the php code I'm currently using:

```
$image = new Image(
    '/path/to/public/some-generic-id.html'
    # also tried:
    # 'https://my.www/some-generic-id.html' # no change
    # 'https://my.www/some-generic-id.php' # no icons
    # 'https://my.www/some-generic-id/image/file.html' # tweaked image.php via mod rewrite to have an url ending with .html, but still: no icons
    # '/path/to/private/folder/some-generic-id.html' # no icons
); 
$image->setOptions(array(
    'width'    => 96,
    'format'   => 'png'
));
```

Html
```
<html>
    <head>
        <link rel="stylesheet" href="css/font-awesome.min.css">
        <!-- <link rel="stylesheet" href="https://my.www/css/font-awesome.min.css"> -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"> -->
    </head>
    <body>
        <div class="foo">
            <div class="content">
                <i class="fa fa-rocket"></i>
            </div>
            <div class="bar"></div>
        </div>
    </body>
</html>
```

**Comment by mikehaertl** [comment]
That's nothing we can fix here, because `wkhtmltopdf` doesn't support it.

**Comment by okneloper** [comment]
Hey, @mikehaertl 
Would this not work by embedding the fontawesome TTF into the PDF?

Thanks.

**Comment by mikehaertl** [comment]
@okneloper Again: This is a question for wkhtmltopdf itself. This library is just a wrapper around the command line tool.
