### ISSUE TITLE
HowTo install without compose

### ISSUE THREAD

**Issue by Dimas-sc** [mikehaertl/phpwkhtmltopdf#154]
Is there an easy way to install it without composer? I tried downloading src folder and I'm getting problems with dependences, the Use syntax, etc...

**Comment by mikehaertl** [comment]
Sorry, installation without composer is not supported. If you have problems with remote servers that only provide FTP access, you can always use composer to install it locally, then upload the `vendor/` directory to the server.

**Comment by james-bell** [comment]
It's a shame to have limitations like this.  Not everyone wants to use Composer and this looks like a great package.

**Comment by mikehaertl** [comment]
Some years ago I shared your concerns. Somehow I was adverse to composer and didn't like how it hides away things from we. I wanted to stay in control of things. And I didn't want to learn a new tool just to install software!

I've changed my mind and never will look back. (And so has has the large majority of PHP developers).

Of course you *can* install the library without composer. Here's what you have to do:

 * Download all dependencies of this library. You can find them out by looking at the included `composer.json`. Right now you have to download https://github.com/mikehaertl/php-tmpfile and https://github.com/mikehaertl/php-shellcommand. Make sure, you get the right versions!
 * Include all contained `.php` from all your downloads whereever you want to use `phpwkhtmltopdf` in your project.

Now it should work. If it doesn't ... well, you missed something, double check.

Now the tricky part: Whenever I release a new version, e.g. with an important bugfix you have to download manually again and also check the other libraries and use the correct versions again. I may have changed the version dependencies - you also need to re-check the versions of the other libraries! There may also be new files added now, so you have to update your includes, too.

This can become extremely tedious and error prone - a complete mess! `composer` does all this for you! It pulls in all dependencies and makes sure, that the versions match the requirement. And all this from one single command!  There's also no big mistery where your files end up: You can find all the files nicely organized in a `vendor/` directory. Very simple.

It also auto-includes all the necessary files whenever you want to use a library - you only need to include its autoloader once and you're done.

And it does that for 1000s of php libraries. It makes developers life easier and that's a good thing.

I really really recommend that you reconsider your aversion against `composer` and just give it a try for some time. You can still revert to your old workflow if you're not convinced.

**Comment by james-bell** [comment]
Okay but PHP is not my life right now, most of my work is in JS and the front end, also I don't have complete control over the server or what is installed or used there.  Philosophically I worry about a tool that updates and hides dependencies, because breaking changes happen.
