### ISSUE TITLE
Ignore some wkhtmltopdf exit codes ?

### ISSUE THREAD

**Issue by atomrc** [mikehaertl/phpwkhtmltopdf#156]
many wkhtmltopdf exit codes means that the PDF is ok but has encountered some minor problems (in my case an image that returns a 404 and a ContentNotFoundError after wkhtmltopdf execution). The PDF is still very usable. 

As suggested here: https://github.com/KnpLabs/snappy/issues/177#issuecomment-141008420I think it would be a good idea ignoring, at least, exit code 1

What do you think about that ?

**Comment by mikehaertl** [comment]
Did you check the `ignoreWarnings` option?

https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options

**Comment by atomrc** [comment]
Oh thanks, it works like a charm :)
Sorry for the noise and thanks a lot for your fast answer!!
