### ISSUE TITLE
Can't generate the PDF from PHP using this lib

### ISSUE THREAD

**Issue by JerryBels** [mikehaertl/phpwkhtmltopdf#157]
Hello,

I installed wkhtmltopdf, composer, and then the last release from this repo. Generating pdfs from the command line works great. From PHP with this lib it doesn't. 

    wkhtmltopdf http://google.com testfile.pdf

Works perfectly from the command line. But if I try to do the same in PHP, by using exec it works : 

    exec("/usr/local/bin/wkhtmltopdf http://google.com testfile.pdf");

By using phpwkhtmltopdf there is an issue : no PDF generated, no error displayed on the page.

Could this be rights issue ? On the executable or something ? I did 

    ln /opt/wkhtmltopdf/bin/wkhtmltopdf /usr/bin/wkhtmltopdf

and 

    ln /opt/wkhtmltopdf/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf

for the users to be able to use wkhtmltopdf, but I guess I'm missing something...

Thanks ahead !

**Comment by mikehaertl** [comment]
You can set the `useExec` option in the `commandOptions`. This will use `exec()` instead of `proc_open()`. Not sure, why the latter doesn't work for you.

**Comment by JerryBels** [comment]
Hey, thanks for your answer,

I tried and it doesn't work, but I guess it's not because of proc_open, I think it's more a path issue for the command. Indeed, if I try : 

    exec("wkhtmltopdf http://google.com testfile.pdf");

without `/usr/local/bin/` it doesn't work either (while it works in the command line, when logged as root user). So I tried to use `setExecCommand` but it gets me to an error 500.

**Comment by mikehaertl** [comment]
Are you on CentOS?

**Comment by JerryBels** [comment]
Yes, on our dev server (which is the one I test on right now). Our prod server is on Gentoo.

**Comment by mikehaertl** [comment]
Ok, then this is probably the same problem as (or at leas very similar to) #125. No one has found out yet, what exactly is the problem. If you find out, please let us know in #125. For now I'm closing this here.
