### ISSUE TITLE
.htm file extension

### ISSUE THREAD

**Issue by digitill** [mikehaertl/phpwkhtmltopdf#158]
I'm using phpwkhtmltopdf in a Drupal 7 install. I include a file name when I call the $pdf->send('test.pdf') function in order to get the browser to open the download dialog box. When I select "Open with: Firefox" in the Firefox download popup dialog box, the browser downloads the file to the temp folder on my computer, and then opens that file in a new browser window. The problem is that when Firefox downloads the file to the temp folder, it adds an .htm extension to the file. When test.pdf.htm is opened in a new browser window the user sees gibberish instead of a rendered pdf file. If I remove the .htm extension the file works as it should. Something in the file path or header info makes Firefox add the .htm extension, but I have no idea what prompts Firefox to do this. Any insight into this matter would be greatly appreciated.

**Comment by mikehaertl** [comment]
For downloads we use the example implementation from the PHP manual for `readfile()`:

http://php.net/manual/en/function.readfile.php

It's implemented here: https://github.com/mikehaertl/php-tmpfile/blob/master/src/File.php#L55. I've never had problems with this. This should really work across all browsers.

What you can try:

 * Check if the example from `readfile()` works for you (using a plain PDF without phpwkhtmltopdf)
 * Check if your the HTTP headers differ in some way from the example

**Comment by digitill** [comment]
Thank you for your quick response and help with this matter. I am a bit confused because the file with the implementation that you reference doesn't seem to be in the phpwkhtmltopdf library folder that I am using with my drupal install. Am I doing something wrong by not using the php-tmpfile library as well?

**Comment by digitill** [comment]
Thank you for your quick reply and your help with this matter. After doing some testing with the php.net readfile() example and the send function in File.php the difference that seems to make a difference is the exit; call after the readfile($file) call. If I add "exit;" after the readfile() call on line 76 of the File.php file, the Firefox download popup window reads:

You have chosen to open:
test.pdf
which is: Adobe Acrobat Document
What should Firefox do with this file?
Open with Adobe Acrobat Reader DC (default)

Which is what I want because Firefox clearly thinks that the file is a pdf. Without the exit; the diaglog reads:

You have chosen to open:
test.pdf
which is: Firefox HTML Document
What should Firefox do with this file?
Open with Firefox (default)

This makes it seem like the headers are fine, but something else happens to make Firefox treat the test.pdf file as a html file instead of a pdf file. I can see that the send() function in php-tmpfile/src/File.php is being called by the send() function in phpwkhtmltopdf/src/Pdf.php file, but I can't see anything that would change how Firefox classifies the file. I'm very interested in getting to the bottom of this mystery so any further information that you can provide about this situation is appreciated.

**Comment by digitill** [comment]
If I exit; after the $pdf->send('test.pdf'); call in my code I get the desired Firefox behavior. Thanks for your help.
