### ISSUE TITLE
multiple html / css

### ISSUE THREAD

**Issue by flip111** [mikehaertl/phpwkhtmltopdf#160]
Are there any provisions to work with multiple html and css files? Or can anyone recommend a good tool to put everything into a single html and a single css file so that phpwkhtmltopdf can work with it?

**Comment by mikehaertl** [comment]
You could use https://github.com/mikehaertl/php-pdftk to combine several single page PDF files into one final file.

**Comment by flip111** [comment]
I don't need multiple PDF pages. This doesn't answer my question.

**Comment by mikehaertl** [comment]
Then I don't know. This library does not extend the capabilities of `wkhtmltopdf`.
