### ISSUE TITLE
Nothing returned - blank screen.

### ISSUE THREAD

**Issue by blue-coder** [mikehaertl/phpwkhtmltopdf#162]
@mikehaertl 
I am a noob, but have read through the readme and all the stackoverflow questions which relate to this, and four hours down the like still can't seem to make this work.  It does not throw any errors, but just shows a blank page.

The code I have to test is as follows:

```php
<?php 
require_once __DIR__ . '/vendor/autoload.php';
use mikehaertl\wkhtmlto\Pdf; 
$pdf = new Pdf;
$pdf->addPage('http://google.com');
$pdf->send();
if (!$pdf->send()) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
}
$content = $pdf->toString();
if ($content === false) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
}
?>
```

I currently have a button on another website (which I am building) which takes you to this page, however, it is just a blank page.

If you have any ideas where I am going wrong, please let me know.

**Comment by Mommens** [comment]
Hello there @blue-coder 

Try adding following line of code below $pdf = new Pdf;
(MAC)
 $pdf->binary = '/usr/local/bin/wkhtmltopdf';

This will make it work!

Kind regards,

Bart

**Comment by mikehaertl** [comment]
@blue-coder Sorry, I missed this issue. Please first remove the duplicate `$pdf->send()` (the one above the `if`). You should only call this once.

**Comment by blue-coder** [comment]
Thanks @Mommens and no worries @mikehaertl 
I used the very temporary alternative of a small piece of javascript to bring up a print window, and do the rest manually.  However, thanks to these responses I should be able to get it all automated (it is a business report system, which needs to automatically email out a pdf overview at the end of each day).  I will try these solutions out at the coming weekend.

**Comment by mikehaertl** [comment]
I'm closing this for now as there was no further feedback and this is not a real bug report anyway.

**Comment by Mommens** [comment]
Indeed it was not, good work on the wrapper saved us a lot of time.

Kind regards,
Bart Mommens
