### ISSUE TITLE
No transparent background

### ISSUE THREAD

**Issue by daHaimi** [mikehaertl/phpwkhtmltopdf#166]
Hi there,

when I am trying to create a PDF with transparent background (I need to merge it onto a template pdf later), the output always contains a background rectangle filled with white background-color. I tried to override it using
```html
<body style="background-color: transparent !important;">
```
But it always produces an opaque white background. Is there any switch I can use or is it a bug?

**Comment by mikehaertl** [comment]
I'm sorry, but this is a question for `wkhtmltopdf` itself. This library is only a wrapper around that tool.
