### ISSUE TITLE
Cannot add 'pdf-no-compression' option 

### ISSUE THREAD

**Issue by davidtmnolan** [mikehaertl/phpwkhtmltopdf#167]
Hello.  I'm trying to create non-compressed PDFs with this wrapper.  It's currently set up and working without any issues, until I try to add the 'no-pdf-compression' option.

`$pdf = new Pdf($html);`
`$pdf->setOptions([
    'binary' => '/usr/local/bin/wkhtmltopdf.sh',
    'no-pdf-compression'
    ]);`

When I dump the `$pdf` object after I get

`Could not run command /usr/local/bin/wkhtmltopdf.sh --pdf-no-compression '/tmp/tmp_wkhtmlto_pdf_vtHd6S.html' '/tmp/tmp_wkhtmlto_pdf_Ipjn44.pdf'`

The protected property `_options` shows 'pdf-no-compression'.  

Is --no-pdf-compression not supported in this wrapper?  Thank you.

**Comment by davidtmnolan** [comment]
Assuming `wkhtmltopdf --extended-help` shows all available options, it looks like `pdf-no-compression` is not supported in this wrapper.  :(

**Comment by mikehaertl** [comment]
The wrapper supports whatever your `wkhtmltopdf` command provides. We don't restrict this at all. If you miss an option you should update your version of `wkhtmltopdf` on your machine. But this has nothing to do with this wrapper class.

**Comment by davidtmnolan** [comment]
Thank you, I understand now.
