### ISSUE TITLE
Toc with mulitple pages

### ISSUE THREAD

**Issue by nniicc** [mikehaertl/phpwkhtmltopdf#168]
Hey, I'm trying to make a pdf with multiple pages where the TOC can be anywhere, so i add multiple pages to the pdf and at some point i add the TOC ($pdf->addToc())

For a simple test i tried to use this
```php
$pdf->addPage("<html><h1>H1</h1><h2>h2</h2><h2>H22</h2></html>");
$pdf->addPage("<html><h2>H23</h2></html>");
$pdf->addToc(array('toc-header-text' => 'Kazalo'));
```
The result is not what i'd expect 

<img width="1032" alt="screen shot 2016-05-25 at 11 41 38" src="https://cloud.githubusercontent.com/assets/5363602/15535448/b3fe42e8-226d-11e6-9fae-75173c9c2089.png">

The 2nd h2 was added as a new h1 in the new page.
Is there any way to fix this?

**Comment by mikehaertl** [comment]
This is nothing we can fix here. It's an issue of `wkhtmltopdf` itself.
