### ISSUE TITLE
Problems with large HTML and CSS

### ISSUE THREAD

**Issue by proecil** [mikehaertl/phpwkhtmltopdf#170]
Hello Mike!

I'm just testing your awesome package, but I have a problem when I add a large HTML and CSS.
In this case I get the following error from browser:

`The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must to be declared in the document or in the transfer protocol.`

I tried everything but I can't find any solution.

Can you help me a bit?

Thank you!

**Comment by mikehaertl** [comment]
This is a message from `wkhtmltopdf`. This is nothing we can fix here. You should ask at the `wkhtmltopdf` project instead.
