### ISSUE TITLE
repeating header-html & footer-html doesn't work correctly with x-serve (on debian jessie)

### ISSUE THREAD

**Issue by CODEheures** [mikehaertl/phpwkhtmltopdf#171]
Hello,

Html footer & header don't want appear when I use x-server.
But for information the sames Html header and footer are OK for me with wkhtmltox package.

An observation on your doc:  it's hard to understand how obtain and install this package!!.. One day for me. I think https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/INSTALL.md is better than your link to unterstand how create package. After create and dpkg -i command I can finally use your PHP librairie.

Thank you (sorry for my "french" english ;-) )

**Comment by mikehaertl** [comment]
> Html footer & header don't want appear when I use x-server.

This is nothing we can fix here. If the PDF creation per se works, it's rather a problem with wkhtmltopdf + Xserver. I recommend you use a statically compiled version of `wkhtmltopdf` then you don't need an XServer.

> it's hard to understand how obtain and install this package!!

We only support installation with composer. This is really standard these days. If you don't use it yet, you really should. Installing the package is a single command.

**Comment by CODEheures** [comment]
> We only support installation with composer. This is really standard these days. If you don't use it yet, you really should. Installing the package is a single command.

Yes, it's OK for me about the installation of your php librairie with composer. My observation is to obtain the wkhtmltox debian package
