### ISSUE TITLE
Failed to load PDF document

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#172]
Hello,
I see no error but browser ends with:
**Failed to load PDF document**

only in /var/log/apache2/myweb.error.log:
`[Tue Jun 14 14:27:22.109808 2016] [:error] [pid 6456] [client 192.168.6.116:40370] PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/myweb/pdf/phpwkhtmltopdf/vendor/mikehaertl/php-tmpfile/src/File.php:76) in /var/www/myweb/pdf/phpwkhtmltopdf/vendor/mikehaertl/php-tmpfile/src/File.php on line 68, referer: http://192.168.1.7/index.php/de/186
`
but I think it is not the problem why the PDF is not loaded

**Comment by mikehaertl** [comment]
Seems like you call the `send()` method a second time. Because the error is thrown in line 68, and it complains that the output started in line 76 which comes later. So this must be from a previous call.

**Comment by ZAJDAN** [comment]
I am sorry...it was my mistake!
I forgot to pass a php value of variable which is called inside html for rendering.
