### ISSUE TITLE
Safari "The network connection was lost" but Chrome works

### ISSUE THREAD

**Issue by suntrop** [mikehaertl/phpwkhtmltopdf#174]
I am using phpwkhtmltopdf inside a CMS (template) and my tests went quite well.

But now after I placed the code in another file (other include) I can't get the PDF output with Safari, but Chrome still displays the PDF. Using a HTTP tool (Do HTTP) I get the message 
_status code: 200
The network connection was lost._

This one works:
```
<?php
use mikehaertl\wkhtmlto\Pdf;
require __DIR__ . '/../vendor/autoload.php';

if ($urlsegment1 === 'pdf_source') {
	$sub_template = 'pdfsource';
} elseif ($urlsegment1 === 'pdf') {
	$sub_template = 'pdf';
}

$pdf = new Pdf;
$pdf->setOptions(['ignoreWarnings'=>true]);
// $pdf->addPage('http://www.example.com');
$pdf->addPage('<html><body>PDF-Datei neu</body></html>');

if (!$pdf->send()) {
    echo $pdf->getError();
}

die();
```

When I move the phpwkhtmltopdf (use, require, new Pdf etc.) to the other file it doesn't work in Safari.
The other file is loaded later on with an include and looks identical, but without the if/elseif part.

There is nothin in my Apache error log and there is no error by wkhtmltopdf

(PHP 5.6, Apache 2.2, Linux)

// Forgot to mention, saveAs() works

**Comment by mikehaertl** [comment]
Maybe the CMS outputs some header or similar. We can't fix this here.

**Comment by suntrop** [comment]
The first code example comes from the CMS as well. It is just a couple lines before the other code. And Chrome is able to display the PDF.
Snappy works fine. I think I'll go with it.

**Comment by mikehaertl** [comment]
This extension does not make any difference between browsers. If it works without the CMS then it must do something to the headers or output some content before.
