### ISSUE TITLE
90mb pdf fails, no error or feedback

### ISSUE THREAD

**Issue by dpayne0220** [mikehaertl/phpwkhtmltopdf#176]
I'm generating a pdf with your library, and it's working fine until I try with a large amount of data.
I can generate the pdf in the command line just fine, but in the library it just stays hanging. I've traced it back to the Pdf.php file in the library, but it hangs on $command->execute. Is there any way to get feedback from the output of the command before it completes? Or any clues as to why it's failing? I've already changed my php execute timeout.

```
         $pdf = new Pdf($options);      
        
     
        foreach ($html_file as $file) {
            #create pdf and add all html pages to it
            $pdf->addPage($file);  
            error_log("page added".$file);
        }
            
        $date = new DateTime();
        $stamp = $date->getTimestamp().bin2hex(openssl_random_pseudo_bytes(4));
        $pdffilename = "catalog_$stamp.pdf";
        
        if (!$pdf->saveAs($pdfpath.$pdffilename)) {
        
            error_log($pdf->getError());
        }    

```

**Comment by mikehaertl** [comment]
Could you check #78 and see if any of the discussed solutions works for you?

**Comment by dpayne0220** [comment]
I added this parameter to Pdf and it worked. Thank you for your prompt response. 
`'commandOptions' => array(
        'useExec' => true
    ) `
