### ISSUE TITLE
Failed without error message: wkhtmltopdf 

### ISSUE THREAD

**Issue by TuCaO96** [mikehaertl/phpwkhtmltopdf#177]
I try to create an PDF with an HTML content, and it is everything alright with the HTML data, the page starts to load to generate the PDF but does not download it. When I check the getErrror, returns this message with the temp file path, but when I check the folder, the HTML and PDF temp files are not there..

**Comment by mikehaertl** [comment]
> When I check the getErrror, returns this message with the temp file path

Which message is it?

**Comment by TuCaO96** [comment]
It gives the following error:

> Failed without error message: wkhtmltopdf "...\tmpC1F5.tmp.html" "...\tmpC1F5.tmp.pdf"

I tried to get the output like I saw in other posts, but I couldn't access the plugin command lines, it gives the message that it is not a valid command

**Comment by mikehaertl** [comment]
Hmm, the temp file names look a bit weird. Can you show me the full code you used for PDF creation? I don't need lengthy HTML, just the PHP part and only the section relevant for PDF.

**Comment by TuCaO96** [comment]
PHP Controller:

`
$pdf = new Pdf();
`

        $slugifier = new Slugify();
`
        //html page
        $content = $app['twig']->render('pdf/hiring-company.twig.html', [
            'company' => $company,
        ]);
`

        $pdf->addPage($content);
`

        if(!$pdf->send($slugifier->slugify($company->name) . '.pdf')){
            echo $pdf->getPdfFilename();
            print_r($pdf->getError());
        }`

**Comment by mikehaertl** [comment]
Have you tried the `useExec` option?

```
$pdf = new Pdf([
    'commandOptions' => ['useExec' => true],
]);
```

**Comment by TuCaO96** [comment]
Gives the error on Windows: "'wkhtmltopdf' is not recognized as an internal or external command" but worked now on Linux, there is any way I can fix this to work on Windows too?

**Comment by mikehaertl** [comment]
Please check the `binary` option in the wrapper. You need to tellt he wrapper where it can find `wkhtmltopdf` if it's not in your search path. 

https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options

**Comment by bretto36** [comment]
You need to add the location of the wkhtmltopdf exe to your system path. So that it can be run from the command line, or you can do what mike suggested

**Comment by skunkbad** [comment]
FYI, if you upload the file with FTP via FileZilla, make sure to manually transfer using binary mode. I was getting this error message today, and then after doing a checksum of the file noticed that it was somehow corrupted. Transferred with binary mode and started working instantly.

**Comment by sainirajat74** [comment]
Sir,do i need to install also WkHtmlToPdf on windows along with composer?
