### ISSUE TITLE
Missing elements

### ISSUE THREAD

**Issue by MattRogowski** [mikehaertl/phpwkhtmltopdf#178]
I'm trying to export a PDF of my page, but it's completely missing out the entire header tag and h1 tag. Also, it doesn't seem to be able to include fonts? That may be why the h1 is missing but the header tag contains a logo image and text in Arial and there's just nothing in the PDF.

**Comment by mikehaertl** [comment]
You should point your questions to the wkhtmltopdf team. This library is just a frontend and has no influence on the way wkhtmltopdf works.
