### ISSUE TITLE
Having issue with UTF-8 characters

### ISSUE THREAD

**Issue by doshimehul** [mikehaertl/phpwkhtmltopdf#180]
Hi I am facing issue with displaying UTF-8 characters on my server, the same character is getting displayed fine on my local machine. 

Local copy shows correctly
[working.pdf](https://github.com/mikehaertl/phpwkhtmltopdf/files/405497/working.pdf)

PDF on server shows square boxes 
[index.pdf](https://github.com/mikehaertl/phpwkhtmltopdf/files/405496/index.pdf)

Can you help me to debug the same?

**Comment by mikehaertl** [comment]
Please check the example for setting [encoding](https://github.com/mikehaertl/phpwkhtmltopdf#setting-options) and [procEnv](https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options) options.

**Comment by doshimehul** [comment]
Thanks for the reply, Here is my code,

$pdf = new Pdf(array(
            'encoding' => 'UTF-8',
            'ignoreWarnings' => true,
            'commandOptions' => array(
                'procEnv' => array(
                    'LANG' => 'en_US.utf-8',
                ),
            ),
        ));
        $event =  Events::findOne($id);
        if($event) {
            $html = $event->getItemHTMLForPdf($item_type);
            //echo $html;
            $pdf->addPage($html);
            if($action == "preview") {
                $pdf->send();
            } else {
                $file_name = $event->getPdfFileName($item_type);
                $pdf->send($file_name);
            }

Also  the HTML generated has following 2 lines
`
<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<meta content="utf-8" http-equiv="encoding">
`

**Comment by mikehaertl** [comment]
Is `en_US.utf-8` listed in the output of `locale`? Also does it work correctly if you use `wkhtmltopdf` on the command line?

**Comment by hackel** [comment]
Make sure you're using the same font on the server, and that the font actually has those characters!

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback from the reporter.
