### ISSUE TITLE
Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by cmohanraj10** [mikehaertl/phpwkhtmltopdf#181]
I am running this page, tests/ImageTest.php. I am getting this error.

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in **tests\ImageTest.php** on line 6

**Comment by mikehaertl** [comment]
This is a problem in your phpunit installation. The tests work as you can see here:
https://travis-ci.org/mikehaertl/phpwkhtmltopdf
