### ISSUE TITLE
Help needed in saving the updated values on regenerated html

### ISSUE THREAD

**Issue by Venkata-sai-Gopichand** [mikehaertl/phpwkhtmltopdf#183]
Hi mike, 
I used your phpwkhtmltopdf and was able to generate a single  html  and pdf  for all my .html pages.
Now i need to update my database server with edited data on html generated from phpwkhtmltopdf.

Kindly guide me through your advices

Do i need to show/put  button on the last html page to push the edited to my db server?

Do i need to use any ajax function to save/update edited data on html?

Thanks

**Comment by mikehaertl** [comment]
I'm happy to fix bugs with the library, but I'm sorry: please understand that I can not give project specific support.

**Comment by Venkata-sai-Gopichand** [comment]
I was just curios that you might help me . Thanks though. Thanks a ton for your library... helping a lot of ppl. 

Appreciate it
