### ISSUE TITLE
Add pdf page

### ISSUE THREAD

**Issue by PeterJason** [mikehaertl/phpwkhtmltopdf#184]
Hi
I can do that? I saw the documentation and there say:

>  @param string $input either a URL, a HTML string or a PDF/HTML filename

> $pdf->addPage('rec.pdf');

It's normal getting the error?

**Comment by mikehaertl** [comment]
Sorry, the docs where incorrect here. I've fixed it now.

If you need to merge PDF pages into the final PDF you can use `pdftk`. You can use my other library here: https://github.com/mikehaertl/php-pdftk
