### ISSUE TITLE
Wkhmltopdf not working  on AWS Cpanel

### ISSUE THREAD

**Issue by Venkata-sai-Gopichand** [mikehaertl/phpwkhtmltopdf#186]
Hello, 

I was running wkhtmltopdf on my Windows local machine which was working fine. But now I hosted my website on aws(CentOS server) and tried to run, here it's not creating the .pdf file using wkhtmltppdf.  

So  Does it make a difference in installing wkhtmltopdf on windows and aws (linux I suppose) with same windows flavored version.

**Comment by mohitmittal1** [comment]
I am also having a same problem, please help me out.

**Comment by mikehaertl** [comment]
I don't use AWS Cpanel, so I can't help if you don't at least provide any meaningful error message. What does `$pdf->getError()` return?

**Comment by mohitmittal1** [comment]
It is not able to pick up the link for the .exe file in cpanel as far as I understand, and shows http error 505 . 

My code is 

require __DIR__ . '/vendor/autoload.php';
$html1 = $doc1->saveHTML();

//echo $html1;

use mikehaertl\wkhtmlto\Pdf;
$pdf = new Pdf;
$pdf->binary = '/wkhtmltopdf/bin/wkhtmltopdf.exe';
$pdf->addPage($html1);

if (!$pdf->send()) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
}
mysqli_free_result($result);
exit();
?>

I am trying to convert $html1 to pdf. The code is working fine when I uncomment "echo $html1", it shows editable html.So, I guess autoload. php is loading correctly, but when I comment "echo $html1" and want to convert this to pdf, it shows http 500 error.

**Comment by mikehaertl** [comment]
If you are on Linux, you can't use `.exe` files. You need to install the wkhtmltopdf version for linux on the server.

I'm really sorry, but I can not give support on this. This library requires that `wkhtmltopdf` is ready on your system. If you have questions with this, please consult the wkhtmltopdf website or ask there for support.
