### ISSUE TITLE
Warning: Failed to load http://sis.local/img/topo_landscape.png

### ISSUE THREAD

**Issue by OnixDF** [mikehaertl/phpwkhtmltopdf#189]
I have an image in html

`<img src="<?php echo $baseUrl; ?>/img/topo_landscape.png" />`

I get the above error

`Warning: Failed to load http://sis.local/img/topo_landscape.png`

How to put images in html and convert to pdf?
Another question, how to put more than 1 .css?

Thank you in advance

**Comment by mikehaertl** [comment]
I'm sorry, but these are questions for `wkhtmltopdf` - this library just wraps the wkhtmltopdf in a PHP class binary. If you find problems like yours, then first try to make it work on the command line with a simple example. If it works there and you can't make it work in PHP, then you can report an issue here. In that case please provide a full example so I can reproduce the problem. 

About multiple CSS: I think that's not supported by wkhtmltopdf. Again: First try on the command line (Check `wkhtmltopdf -H` for all the options), then make it work in PHP.
