### ISSUE TITLE
Multiplage html conversion

### ISSUE THREAD

**Issue by abalakrishnan** [mikehaertl/phpwkhtmltopdf#190]
I am using this package, when i pass my multi page html only the margin get applied to 1st page, so 2nd page starting on the edge, so very difficult in printable view. How can i use solve this and set minimum margin top and bottom on each page( it is a full html , may be single or page or multiple pages)

**Comment by mikehaertl** [comment]
Sorry, but I can not help with any layout specific questions, because they are a related to `wkhtmltopdf` itself. This is just a PHP library around the binary. Please consult their support for any questions: http://wkhtmltopdf.org/support.html

**Comment by abalakrishnan** [comment]
I have solved this by setting global options
