### ISSUE TITLE
PDF->save() ignores empty paragraphs while PDF->send() does not

### ISSUE THREAD

**Issue by scriptshark** [mikehaertl/phpwkhtmltopdf#191]
Running phpwkhtmltopdf on Ubuntu 14.04. This issue can be reproduced with this HTML: 
```
<!DOCTYPE html>
<html><head><title></title></head><body>
<p>&nbsp;</p>
<h1>H1 Text</h1>
<p>&nbsp;</p>
<h2>H2 Text</h2></body></html>
```

$pdf->send() results in this: 
[pdfsend.pdf](https://github.com/mikehaertl/phpwkhtmltopdf/files/503762/pdfsend.pdf)

$pdf->save() results in this:
[pdfsave.pdf](https://github.com/mikehaertl/phpwkhtmltopdf/files/503763/pdfsave.pdf)

When using wkhtmltopdf without the wrapper from command line, the output is the same as $pdf->send(). The desired output should match $pdf->send() as I don't think we want to ignore empty paragraph tags.

**Comment by scriptshark** [comment]
Sorry here's the HTML:
```html
<!DOCTYPE html>
<html>
    <head><title></title></head>
    <body>
        <p>&nbsp;</p>
        <h1>H1 Text</h1>
        <p>&nbsp;</p>
        <h2>H2 Text</h2>
    </body>
</html>
```

**Comment by mikehaertl** [comment]
I can't see how this could happen. Both methods use exactly the identical code to create the PDF. The only difference happens in the `send()` and `saveAs()` methods here: https://github.com/mikehaertl/php-tmpfile/blob/master/src/File.php#L70.

So I have to assume that you changed something in your CSS/Markup between the two runs.

**Comment by scriptshark** [comment]
I did not change anything between the two runs, they used the exact same html file. Are you not able to reproduce the issue?

**Comment by scriptshark** [comment]
I can also note that `send($filename)` produces the same result as `saveAs()`

**Comment by mikehaertl** [comment]
Sorry, I can not reproduce this. As stated above, the files created exactly the same way *before* either sending or saving them. So there can't be a difference.
