### ISSUE TITLE
created PDF is not returned into client browser

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#192]
Hello,
in my previous version I have sent my form to PHP via standard submit and everything was ok.
Now I am sending form values via AJAX, but problem is, that the PDF is not returned to window of client browser.
To make me sure, that the PDF is created correctly I tried to saveAs on a server and in this case I see, that PDF is created correctly. But I would like to send the PDF to the client browser.
Could be the problem, that connection runs on SSL? but debugger is clean(any X-Windows, CrossDomain , etc, problem)

in debuger in Response I see:
```
%PDF-1.4
1 0 obj
<<
/Title (þÿ)
/Creator (þÿwkhtmltopdf 0.12.2.1)
/Producer (þÿQt 4.8.6)
/CreationDate (D:20161007120104+02'00')
>>
endobj
3 0 obj
<<
/Type /ExtGState
/SA true
/SM 0.02
/ca 1.0
/CA 1.0
/AIS false
/SMask /None>>
endobj
4 0 obj
[/Pattern /DeviceRGB]
endobj
6 0 obj
<<
/Type /XObject
/Subtype /Image
/Width 4536
/Height 1073
/BitsPerComponent 8
/ColorSpace /DeviceGray
/Length 7 0 R
/Filter /FlateDecode
>>
stream
...
..
.
```
Thank You for any hint
Regards Zdenek

**Comment by mikehaertl** [comment]
Sorry, but I can not give support for app specific questions, like "how to make PDF download work with AJAX requests" (which I think is your issue here - and I don't think this will work at all). 

This here is really only for issues when you think something is broken with the library.

**Comment by ZAJDAN** [comment]
as you see, the problem is not with AJAX when via saveAs is PDF created correctly

**Comment by mikehaertl** [comment]
You can not trigger a download dialog with AJAX request.

**Comment by ZAJDAN** [comment]
You are right
