### ISSUE TITLE
saveAs with random name

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#193]
Hello,
is somehow possible to set for method saveAs use name + postfix(random) or just random name?
Thank You

**Comment by mikehaertl** [comment]
Generating random names is definitely not in the scope of this library. You can use whatever filename you want? So just generate a random name and use that as file name.

**Comment by ZAJDAN** [comment]
so I can create a variable contains string and pass the variable into saveAs ...?

$pdf->saveAs('$pdfName');

**Comment by mikehaertl** [comment]
Yes - but without single quotes around the variable.

Sorry, these are really basic PHP questions. I can not tutor you to learn PHP. Please consult a PHP tutorial or something.
