### ISSUE TITLE
Symfony 2.3 on Linux

### ISSUE THREAD

**Issue by sonylifull** [mikehaertl/phpwkhtmltopdf#194]
Do you have step-by-step way to integrate this to Symfony vendor?

I already copy the source to vendor folder

but error happens like this.

Error: Class 'mikehaertl\wkhtmlto\Pdf' not found in .....

**Comment by mikehaertl** [comment]
Sorry, I can't give support for specific frameworks. You should ask at the symfony support forums how to make composer autoloader working. This has nothing to do with my libray here.
