### ISSUE TITLE
footer-left/right in setOptions

### ISSUE THREAD

**Issue by jmbeekman** [mikehaertl/phpwkhtmltopdf#195]
Previously I've used this code to set my footers with great success. Suddenly it doesn't seem to be working, and I can't find where to fix them.

```
$wkPdf->setOptions([
            'encoding' => 'UTF-8',
            'footer-left' => 'Copyright '.\date('Y').'My Company',
            'footer-right' => '[page]', 
        ]);
```

In the error log (NGINX) I get usage instructions
```
[2016-10-26 22:25:35] api.ERROR: Exception: Sales Report Save(temp) Error: Unknown long argument -- 

Name:
  wkhtmltopdf 0.12.2.1 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>
// more stuff here
```

**Comment by jmbeekman** [comment]
Note, if I comment out footer-left, footer-right it works fine.

**Comment by jmbeekman** [comment]
Upon further screwing around it would seem to be the trailing comma in the array. Not used to that mattering...

**Comment by mikehaertl** [comment]
It seems to me that your problem is this: `\date('Y')`. Why do you prepend a `\` here?

**Comment by jmbeekman** [comment]
Style guide at work for working with namespaces and our frameworks, it worked fine after I removed that trailing comma. eg `'[page]', ` to `'[page]'`

**Comment by mikehaertl** [comment]
That makes no sense, trailing commas have always been valid in PHP. I'm closing this as there's nothing to fix in our side.
