### ISSUE TITLE
Cellmap.php undefined index

### ISSUE THREAD

**Issue by MattRogowski** [mikehaertl/phpwkhtmltopdf#197]
I've been having a repeating problem of having undefined indexes on line 800 of /dompdf/dompdf/src/Cellmap.php

I'm not really sure how to reliably reproduce as there is seemingly no logic to what causes the issue.

When I first had this issue, it was fixed by adding a simple `<div>` tag around another div; I would just randomly add tags until it worked.

Currently I have a section of (perfectly valid) HTML that used to work, but now causes this error - I can remove bits of HTML until it works, and if I then add in something like `<span>hello</span>` the PDF is generated, however if I change it to `<div>hello</div>` this errors.  Even `<div></div>` works, but `<div>.</div>` breaks. I'm not sure exactly what specifically it is about a div tag that breaks while a span tag is okay, or why a period breaks it.

I am using 2.2 on PHP 5.6. Has anything similar to this been reported?

**Comment by mikehaertl** [comment]
Not sure, why you report this here. We have nothing to do with dompdf.

**Comment by MattRogowski** [comment]
@mikehaertl Ugh, my bad, long week with too many libraries. Sorry!
