### ISSUE TITLE
Wrapper not working when Header or Footer contains spaced Text

### ISSUE THREAD

**Issue by mohitp** [mikehaertl/phpwkhtmltopdf#2]
When the `--header-*` or `--footer-*` option is set with a string containing spaces, the wrapper does not output the result.

For example, this option is not working:
`$pdf->setOptions(array('header-left'=>'"ABC A"', ));`

Altering the nested quotes in any combination of single/double quotes is also not working. Also, escaping " with \ is not working. But the `$command` string created by the wrapper works fine when pasted directly at the command prompt.

In the Windows version, the error thrown is:
`'C:\Program' is not recognized as an internal or external command,
operable program or batch file.`
where  $bin is set to `"C:\Program Files (x86)\wkhtmltopdf\wkhtmltopdf"`

**Comment by JagadeeshaNagendramurthy** [comment]
when i am reading pdf am facing "The end-of-file marker was not found."
can you suggest whats wrong

Thanks
