### ISSUE TITLE
I cant generate a pdf file

### ISSUE THREAD

**Issue by Nsengiyunva** [mikehaertl/phpwkhtmltopdf#200]
I am trying to generate a pdf using this phpwkhtmltopdf library but nothing has worked for me yet.
1. I created a folder in my xampp/htdocs folder 
2. From the CMD, i navigated to that folder and use composer to install the phpwkhtmltopdf package
3. I have created a test.php -- this is where i am trying to generate the pdf from; (you see can this php code in the test.txt file)
4. I downloaded and installed the wkhtmlpdf software to my C:/Program Files
5. In the Pdf object  - i set the binary index to the wkhtmlpdf path.
6. I also have another file - a demo.html (see this code in the attached file demo.txt)
7. Am using this piece of code:
`$content = $pdf->toString(); echo $content;` to output a pdf
7. When i try to run this test.php file in my localhost - i get nothing.
[test.txt](https://github.com/mikehaertl/phpwkhtmltopdf/files/570786/test.txt)
[demo.txt](https://github.com/mikehaertl/phpwkhtmltopdf/files/570788/demo.txt)

How can i solve this problem?

**Comment by mikehaertl** [comment]
I'm sorry, but I can't give much support for windows systems. It probably has something to do with wrong paths, or paths with space which sometimes can result in problems. Did you also check the output of `$pdf->getError()` after creating the PDF?

**Comment by Nsengiyunva** [comment]
yes i have - I have just added this piece of code: 
`$pdfError = $pdf->getError(); echo $pdfError;`
and i am seeing this response in my browser:
'wkhtmltopdf' is not recognized as an internal or external command, operable program or batch file.

2. You say that you cant give much support in Windows - should i try to use the Linux OS then? Do you offer support for Ubuntu?

**Comment by mikehaertl** [comment]
The error message seems to indicate, that it can't find your `wkhtmltopdf` executable. 

If Linux is an option, please try it. Developing on Windows is only giving huge pain in all body parts :P. But please understand that this here is only for reporting bugs. I can't give full support for setting up your system. The README should usually help you with all questions.
