### ISSUE TITLE
Options set in described methods resulting error

### ISSUE THREAD

**Issue by BakuDev** [mikehaertl/phpwkhtmltopdf#201]
Hi!

Tried to set options directly within called methods as described in docs but seems it's not possible?

`$pdf->addCover('cover.html', ['orientation' => 'Portrait']);`

Error:

> --orientation specified in incorrect location

`$pdf->addPage('page1.html', ['encoding' => 'UTF-8']);`

Error:

> Unknown long argument --charset

And because of above, it's impossible to mix multiple pages of different orientation. Is there any workaround on how to combine pages with different orientation in a single PDF file without using any other software?

**Comment by mikehaertl** [comment]
These are questions about [wkhtmltopdf](http://wkhtmltopdf.org/) so you should ask there. This here is only a PHP wrapper around it.

If you check `wkhtmltopdf -H` you see, that `orientation` is a global option and `charset` is no option at all. So the error is expected. You can try `encoding` instead of `charset`.

**Comment by jfcartier** [comment]
I think this thread could be reopen since it's actually resulting error when you try different variables. 
ie. ['encoding' => 'UTF-8'] will work, but not ['margin-top' => '100mm']

**Comment by mikehaertl** [comment]
What do you mean by "not work"? Is there an error from wkthmltopdf or is there a problem with the created command string?

**Comment by jfcartier** [comment]
@mikehaertl thanks for your quick feedback. 
There is my error 
Error: --margin-top specified in incorrect location

I searched more about this and I think margin-top is only available as a global variable. 
In fact, margin per page seems not quite implanted yet (as seen in [this thread](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3635#issuecomment-410951887)).

**Comment by mikehaertl** [comment]
We can't fix this here. Our library is only a wrapper for `wkhtmltopdf` which does no syntactical checks if your options are at the right place. In other words you need to know how to use wkhtmltopdf to use our library.

**Comment by jfcartier** [comment]
Yeah that's what I understood. Thanks for your support.
