### ISSUE TITLE
Example Rendering Small 

### ISSUE THREAD

**Issue by christianmagill** [mikehaertl/phpwkhtmltopdf#203]
The "Full example" from the front page isn't working properly for me on latest wkhtmltopdf on Mac OSX.

It renders the contents much smaller than they should be.

Any ideas how to fix this?

![screen shot 2016-12-26 at 4 15 25 pm](https://cloud.githubusercontent.com/assets/2133370/21486721/5520b224-cb87-11e6-9ea6-e74287cd9bbb.png)

**Comment by christianmagill** [comment]
Explicitly setting the DPI to 300 seems to make it scale properly, but any other DPI does not.

**Comment by mikehaertl** [comment]
I'm sorry, I can't help with styling issues. Please consult the wkhtmltopdf manual. This here is just a lightweight PHP wrapper.
