### ISSUE TITLE
Pdf not generated 

### ISSUE THREAD

**Issue by keyurkansara** [mikehaertl/phpwkhtmltopdf#204]
I have try to generate PDF but give following error
My code

use  mikehaertl\wkhtmlto\Pdf;

 public function htmlToPdf()
  {

$pdf = new Pdf('/opt/lampp/htdocs/projectname/public/mypdf/demo.html');
$pdf->saveAs('/opt/lampp/htdocs/projectname/public/mypdf/heloopdf.pdf');
      if (!$pdf->send()) {
        var_dump('Could not create PDF: ' . $pdf->getError());
      }
}

Give bellow error:

string(156) "Could not create PDF: wkhtmltopdf: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /usr/lib/x86_64-linux-gnu/libQtWebKit.so.4)"

**Comment by mikehaertl** [comment]
This error indicates, that something is wrong with your installation of `wkhtmltopdf`. You have to make sure, that it works on the command line first.
