### ISSUE TITLE
creating multiple PDFs with one instance of  wkhtmltopdf appends new output to previous output

### ISSUE THREAD

**Issue by faceless105** [mikehaertl/phpwkhtmltopdf#206]
I love wkhtmltopdf, it's a world of helpful. That being said, I'm running into one issue that's holding me up. I've got a reporting class that is passed an instance of a PDF object. My reporting class will generate many PDFs but I'm finding there's no way to clear the cache and every time I create a new report, it's appended to the previous output and my PDFs keep growing in size. Is there a way to add a clear() function to your class to prevent this from happening? I've been attempting to do so but I'm missing something, and when I call getCommand(), I see all references I've created in it still, not just the current PDF I'm creating.

**Comment by mikehaertl** [comment]
One instance of  `Pdf` represents one single file. You should not reuse it, but create a new instance of the `Pdf` class for each document.

**Comment by AzaZPPL** [comment]
Is this still not possible? In CodeIgniter I would love such a feature.
I would be able to use it like this:
`$this->load->library('pdf');`
`$this->pdf->addPage('<html>...</html>');`
`$this->pdf->saveAs('my.pdf');`
`$this->pdf->clear();`

instead like currently:

`$this->load->library('pdf');`
`$pdf = new Pdf();`
`$pdf->addPage('<html>...</html>');`
`$pdf->saveAs('my.pdf');`

**Comment by mikehaertl** [comment]
@AzaZPPL To be honest, I can't see the problem. What would be the advantage?

It also doesn't make much sense logically: the `Pdf` class from this library represents one specific PDF. So if you want to create a different PDF with other pages etc., you create a new instance. So it's perfectly in line with what is actually happening.

**Comment by faceless105** [comment]
I initially didn't want to keep recreating a PDF object. It seemed to me that it'd be more efficient to re-use the existing object. I have a project that will generate bulk reports and it can generate upwards of 100 PDFs per run. After this discussion however, I did just change my code to dump the PDF object and create a new one for each report. From a programming perspective, it didn't create any barriers. It did however feel a bit weird that once you save the PDF, or at any point, you couldn't run a ->clear() function or something to that nature, to re-use it. As far as the performance, I didn't run any benchmarks, and I didn't notice any change in it either.

**Comment by AzaZPPL** [comment]
@mikehaertl It's fine like this. It's not a problem at all. Just when working with a framework like CodeIgniter it feels more natural to use clear().

Exactly like @faceless105 said.
