### ISSUE TITLE
I was unable to set 'page-size' atrribute

### ISSUE THREAD

**Issue by racastellanosm** [mikehaertl/phpwkhtmltopdf#207]
I tried to set the arg 'page-size' => 'Letter' without any effect.
Altought my HTML is fit via CSS to letter dimensions, the HTML content is placed in an A4 papper.

Any help would be appreciated

**Comment by mikehaertl** [comment]
We only provide the PHP wrapper around wkhtmltopdf binary. For any questions about itself, please consult their support.
