### ISSUE TITLE
PDF generation hanging indefinitely

### ISSUE THREAD

**Issue by leonardopcastro** [mikehaertl/phpwkhtmltopdf#208]
I was testing some html conversions, when I noticed one made PHP hang indefinitely.

Doing some debug I found out that it was happening in the php-shellcommand/src/Command.php file at line number 317:
```PHP  
$this->_stdOut = stream_get_contents($pipes[1]); 
```
After some research, I found a similar problem in this stackoverflow question and an apparent solution. http://stackoverflow.com/questions/31194152/proc-open-hangs-when-trying-to-read-from-a-stream

According to the stackoverflow answer, there is a possibility of an execution not outputting anything to stdout (pipe[1]) when an error occurs, so stream_get_contents waits for a stream that never comes. 

As pointed out in the stackoverflow answer, reading the stderr (pipe[2]) before stdout (pipe[1]) did the trick for me, with the PHP finishing execution and the error message being outputted.
```PHP  
$this->_stdErr = stream_get_contents($pipes[2]);
$this->_stdOut = stream_get_contents($pipes[1]); 
```

**Comment by mikehaertl** [comment]
@leonardopcastro Thanks for this, we already had several reports about weird issues with `proc_open()` and `stream_get_contents()`. Would you mind opening this same issue over at https://github.com/mikehaertl/php-shellcommand which is where this code is actually from? Could you please also add there which OS you use?

Thanks!

**Comment by leonardopcastro** [comment]
@mikehaertl No problem, already opened the issue there. 

Do you want me to close this one to avoid repetition?

**Comment by mikehaertl** [comment]
Thanks!
