### ISSUE TITLE
Verify completion of generating a PDF

### ISSUE THREAD

**Issue by faceless105** [mikehaertl/phpwkhtmltopdf#210]
I'm not sure this is possible but is there a way to verify a page has been written?

I've had issues where a 5 page (just an example) PDF for whatever will only generate the 1st page. It is doing this without generating any errors either. I've had a difficult time tracking this as well because the page count is determined by the rendering engine, so if one HTML document generates a PDF that is 3 pages in length, it's hard to line that up for error checking. So far the most of what I've been able to do is check that the PDF page count is greater than or equal to the number of HTML documents used to generate it. This works if the conversion produces only a single page when it should have produced more, but it allows for false positives if the html documents span for multiple pages.

For example, if I am creating a PDF for 3 HTML documents...
HTML Document 1 -> Produces 3 PDF pages
HTML Document 2 -> Produces 1 PDF page
HTML Document 2 -> Failed to convert

My error checking will take a page count of the PDF and see that it had 3 HTML documents and the PDF has 4 pages, creating a false positive that everything processed perfectly.

My reports are fluid enough that I can't build manual counts into them.

If $pdf->addPage could return a page count then this would allow a lot of data checking. Or if these aren't rendered individually, $pdf->saveAs could give a bit more data about what was produced, it could definitely be extremely helpful for redundant checking. I also understand that this might very well go beyond the scope of the PHP wrapper and might not be possible without more core functionality being built into wkhtmltopdf.

**Comment by mikehaertl** [comment]
I'm sorry, but that's not possible. This library is just a "stupid" wrapper around the `wkhtmltopdf` command line tool. It helps you to build an often somewhat lengthy command string in an object oriented manner. It then simply calls `wkhtmltopdf` with all those arguments to create the PDF in one go.

So when you call `addPage()` not much happens. The PDF is only created when you call `saveAs()` or `send()`.

You may want to check out my other wrapper for [pdftk](https://github.com/mikehaertl/php-pdftk) which can help you to inspect created PDFs.
