### ISSUE TITLE
Using renderPartial doesn't work

### ISSUE THREAD

**Issue by 1Luc1** [mikehaertl/phpwkhtmltopdf#211]
If i try use the `renderPartial` function from yii2 `$pdf->send()` return false.
`$pdf = new Pdf($this->renderPartial('update', ['model' => $this->findModel($id)]));`

If i enter the full url of the view into the constructor the output works perfectly.
`$pdf = new Pdf('http://localhost/basic/web/index.php?r=ensemble-proposal%2Fupdate-proposal&ensemble_id=5');`

**Comment by mikehaertl** [comment]
I'm sorry, but this does not sound like anything related to this library at all. You mention `renderPartial()` - but it does not matter at all how you create your HTML string. As long as you pass valid HTML the PDF should be created correctly.

That said, I wonder, why you call `renderPartial()` and not `render()`. The former will not apply the layout so maybe this is the problem. But this is really not related to this library. Closing this for now unless you provide a reproducible minimal (!) example.
