### ISSUE TITLE
Fix Header and Footer for All Pages

### ISSUE THREAD

**Issue by reignsly** [mikehaertl/phpwkhtmltopdf#213]
Is it possible to create custom header and footer for all pages?
Example when you pass a long html table, the pdf pages generated can have header and footer (in my case logo of company, name and address).
This is not an issue but a question.
I can't seem to find any docs for it?
Thanks

**Comment by mikehaertl** [comment]
Sorry, I can't provide help with specific questions about `wkhtmltopdf` features. Please check the help with `wkhtmltopdf -H` or consult their support for questions like this. You can use all options from `wkhtmltopdf` with this class.
