### ISSUE TITLE
addToc generates two table of contents heading

### ISSUE THREAD

**Issue by aryabs** [mikehaertl/phpwkhtmltopdf#217]
Hi,

I just like to know the reason behind the issue.

 ## $pdf->addToc(array('toc-header-text' => 'Kazalo'));

The above code generates two TOC heading , one at the middle central aligned and second above the contents ,how to fix that issue.

**Comment by mikehaertl** [comment]
Sorry, this is a question for `wkhtmltopdf` itself. This library is only a PHP wrapper, so we can't help with that.

**Comment by aryabs** [comment]
Ok Thank you for your quick response :) .
