### ISSUE TITLE
Error when trying to output the HTML string

### ISSUE THREAD

**Issue by dandreevatom** [mikehaertl/phpwkhtmltopdf#218]
Fatal error: escapeshellarg(): Argument exceeds the allowed length of 8192 bytes in C:\xampp\htdocs\projects\lexikon\vendor\mikehaertl\php-shellcommand\src\Command.php on line 223

`$pdf = new Pdf($de_content);`
`$pdf->send();`

**Comment by mikehaertl** [comment]
Hmm, do you have valid HTML content in your `$de_content`? It must match this regex: `/<(?:!doctype )?html/i`. So it should contain a `<hmtl>` tag or something. Otherwhise the library can't know what it is and interprets it as a filename.

**Comment by dandreevatom** [comment]
Thanks for the fast response, this helped me a lot, but there is still 
one issue.

When i wait for generating the pdf the apache port 80 changed to other 
port and the whole site became unusable.

I am using windows(xampp). Do you have any suggestions about this ?

**Comment by mikehaertl** [comment]
> When i wait for generating the pdf the apache port 80 changed to other port and the whole site became unusable.

Sorry, no. This sounds also completetly unrelated to this extension. We don't mess around with Ports.

As a general advice I can only recommend to develop in a Linux-like environment. This would save you a lot of trouble. You could try VM or docker based setups. But that's all a different story.

I'm closing this for now. If you think there's still something to fix feel free to leave a comment or open a new issue.
