### ISSUE TITLE
crash with \n in replace function

### ISSUE THREAD

**Issue by Fighter777** [mikehaertl/phpwkhtmltopdf#221]
hello (again) :),

wkhtmltopdf crash when i use a php variable with \n inside in the replace function.

i must use : str_replace("\n", "", $text);

thx you !!

**Comment by mikehaertl** [comment]
You mean when you use the `replace` feature? I think, that's not easy to fix. Keep in mind, that this library simply creates a (huge) command line string to call `wkhtmltopdf`. That string of course must not contain line breaks.

If you find a way to pass linebreaks in CLI arguments, we can think about a solution. I can also have a look - but will not have much time. Actually I think, this is a ticket for our https://github.com/mikehaertl/php-shellcommand (that's what we use to call `wkhtmltopdf`). We probably need a generic solution that also works on Windows.

If you find time, feel free to open an issue there.

**Comment by Fighter777** [comment]
yes, i test the feature from your wrapper.

```
$tocOption = array(
	'header-html'=> $header,
	'header-line',
	'toc-header-text'=>"sommaire",
	'footer-center'=>"CONFIDENTIEL",
	'footer-right'=>"[page]/[toPage]",
	'footer-left'=>"[date] [time]",
	'footer-line',
	'header-spacing'=>0.5,
	'replace' => array(
		'{titre_livret}' => $json->titre_livret,
		'{logo_societe}' => '../public/static/img/logo.png',
		'{titre_page}' => remplace_shash_n($section->meta->titre_page),
	),
);
```
thx

**Comment by Fighter777** [comment]
so after using replace function from wkhtmltopdf, i will don't use that because i replace a html url in a relative path and i must write the relative path since wkhtmltopdf.exe... 

thx !!
