### ISSUE TITLE
Warning: SSL error ignored Error: Authentication Required

### ISSUE THREAD

**Issue by miclaus** [mikehaertl/phpwkhtmltopdf#222]
I have a HTTP Basic Auth to prevent people from directly accessing the generated PDFs. However I get the following error after successfully bypassing the HTTP Basic Auth:

<img width="694" alt="screen shot 2017-04-10 at 16 19 56" src="https://cloud.githubusercontent.com/assets/4658706/24866190/b6262d0e-1e09-11e7-9ff7-9f6fb0e88a89.png">

Depending on the GET parameters, different pages ( other `.php` templates ) are added to my PDF like so:

<img width="526" alt="screen shot 2017-04-10 at 16 23 32" src="https://cloud.githubusercontent.com/assets/4658706/24866406/4c817790-1e0a-11e7-84c4-683a99382bf9.png">

It seems like those added pages also require authentication. Is there any possibility I can do this with your library, or do I have to manually add the correct headers?

Thanks!

**Comment by mikehaertl** [comment]
You can pass any option that you can use with `wkhtmltopdf` when you create the `$pdf` object:

https://github.com/mikehaertl/phpwkhtmltopdf

See `wkhtmltopdf -H` and check the `--username` and `--password` options.
