### ISSUE TITLE
wkhtmltopdf processes never stop

### ISSUE THREAD

**Issue by MCON** [mikehaertl/phpwkhtmltopdf#223]
We have an option in our code:
['window-status'=>'ready-to-print']

However on some occasions this code is not set in js. In this case wkhtmltopdf processes will never stop. And after some time we have hundreds of zombie-processes. Is it possible to set max execution time for wkhtmltopdf

**Comment by mikehaertl** [comment]
This is rather a feature request for our [php-shellcommand](https://github.com/mikehaertl/php-shellcommand) library, which we use here to execute `wkhtmltopdf`. You can open another issue there, but as such a feature would be non trivial to implement I wouldn't expect a solution anytime soon, sorry.

**Comment by MCON** [comment]
I wrote a more explained issue here:
https://github.com/mikehaertl/php-shellcommand/issues/24

**Comment by drmax24** [comment]
Any news on this?
