### ISSUE TITLE
How can i add custom headers to file download?

### ISSUE THREAD

**Issue by MCON** [mikehaertl/phpwkhtmltopdf#225]
How can i add custom headers to file download?
$pdf->send($pdfFileName);

I need 'Access-Control-Allow-Origin'      => '*',
And
Access-Control-Allow-Headers →Content-Type, X-Auth-Token, Origin, Accept, Authorization, X-Request, X-Requested-With

I have a middleware that adds $response->headers->set('Access-Control-Allow-Origin', '*');
etc but pdf download directive ignores it

**Comment by mikehaertl** [comment]
You can simply call `header()` before `send()` do add additional headers.

**Comment by MCON** [comment]
Yeah did just that. But I think middleware should not be skipped inside send

**Comment by mikehaertl** [comment]
Not sure what you mean. But this is not really an issue for here anyway but for the https://github.com/mikehaertl/php-tmpfile library we use. So I'm closing this for now.
