### ISSUE TITLE
Orientation of PDF

### ISSUE THREAD

**Issue by jayendharp** [mikehaertl/phpwkhtmltopdf#227]
How to set the orientation of the pdf file that get generated?

**Comment by luis-alves** [comment]
After you instantiate the pdf object, you setup its options. Oneway is like so: 


        $pdf = new Pdf($content);

        $pdf->setOptions(['orientation' => 'Landscape',
                          ]);

read [this](https://github.com/mikehaertl/phpwkhtmltopdf) it has a complete example, on setting up options.
