### ISSUE TITLE
can i execute since temp folder ?

### ISSUE THREAD

**Issue by Fighter777** [mikehaertl/phpwkhtmltopdf#229]
hello, with the DOS command line length limit, can i execute the executable since the temp folder ?

i can save 6720 (336 * 20) characters with that :-S

`C: && cd "C:\inetpub\XXX\temp\" && "C:\inetpub\XXX\src\Xxx\Providers\..\..\..\resources\bin\32\wkhtmltopdf_12.4_MSVC.exe" "tmp5F97.tmp.html" --header-html "tmp5F98.tmp.html"....`
rather
`C: && cd "C:\inetpub\XXX\src\Xxx\Providers\..\..\..\resources\bin\32" && wkhtmltopdf_12.4_MSVC.exe
"C:\inetpub\XXX\temp\tmp5F97.tmp.html" --header-html "C:\inetpub\XXX\temp\tmp5F98.tmp.html"....`

maybe remove tmp***.tmp from the name file :) --> 7 * 336 (2352 characters)

thx in advance ;)

**Comment by mikehaertl** [comment]
That's a very specific request that would require too many changes. So I'm sorry, but I can't offer a solution. My advice: Try to get rid of Windows and develop on Linux. It would make your life so much easier.

**Comment by Fighter777** [comment]
hum, i have found a solution : --read-args-from-stdin
i can pass a file argument in the executable
