### ISSUE TITLE
is there a way to include a blade template instead of plain html ?

### ISSUE THREAD

**Issue by abdelrahmanahmed** [mikehaertl/phpwkhtmltopdf#230]

**Comment by mikehaertl** [comment]
Not sure what you mean, can you give an example?

**Comment by abdelrahmanahmed** [comment]
I was trying to use phpwkhtmltopdf in my laravel project ,when i tried this code it didn't work

```
$pdf = new Pdf;
$pdf->addPage('temp');
$pdf->saveAs('test2.pdf'); 
```
but i realized that i can render my view first then i can pass it to **addPage** method,like this : 

$view= view('temp')->render();
$pdf->addPage($view);

problem solved.
