### ISSUE TITLE
Setting TOC styles give invalid location error 

### ISSUE THREAD

**Issue by sakhunzai** [mikehaertl/phpwkhtmltopdf#231]
Setting TOC styles gives error for both url/file 
e.g
<code>--xsl-style-sheet specified in incorrect location </code>

**Comment by sakhunzai** [comment]
command dump show something like this:


    [_stdErr:protected] => --xsl-style-sheet specified in incorrect location

I can load the stylesheet correctly in browser

**Comment by mikehaertl** [comment]
Please notice that this is just a PHP wrapper for wkhtmltopdf. If you're passing wrong options then you get a wkhtmltopdf error. This is nothing we can fix here.

If you still think, there's something to fix for us, please give a code example of the relevant parts.
