### ISSUE TITLE
The code is not working on HTTP(Web-browser)

### ISSUE THREAD

**Issue by imdadk** [mikehaertl/phpwkhtmltopdf#232]
The code is working fine in terminal but not working on HTTP or Web Browser. That's shows error no. 500 currently unable to handle this request.

**Comment by mikehaertl** [comment]
This very much sounds like something is not set up correctly. You should check your webserver error log which should have more details about the 500.

**Comment by imdadk** [comment]
Dear mikehaertl,

That is solved.. That is problem in composer..

Regard's
Imdadali
