### ISSUE TITLE
Can not add Header or footer in pdf file. 

### ISSUE THREAD

**Issue by bakarshams** [mikehaertl/phpwkhtmltopdf#234]
what i want to achieve is to add a date in header but every time i insert an attribute in 		$pdf>setOptions(array , it gives a blank, 1 pages PDF. Otherwise it displays the pdf file correctly depending upon the HTML provided in $htmlContent. Kindly help @mikehaertl  
Version : 1.0.2
OS : Ubuntu 16.04
PHP code > 
use mikehaertl\wkhtmlto\Pdf;
		$fileName="";
		$htmlContent="No HTML content";
		$orientation="Portrait";
		
		$fileName = $_POST['fileName'];
		$htmlContent = $_POST['htmlContent'];
		$orientation = $_POST['orientation'];
		// You can pass a filename, a HTML string, an URL or an options array to the constructor
		$pdf = new Pdf($htmlContent);
		$pdf->setOptions(array(
			'orientation' => $orientation,
			'header-html' => $headerOnPage//I want to add header but upon adding this, blank page shows up. 
        ));

		// On some systems you may have to set the path to the wkhtmltopdf executable --orientation 
                Landscape
		//$pdf->binary = "./wkhtmltopdf/bin/wkhtmltopdf.exe";
		$pdf->binary = "./wkhtmltox/bin/wkhtmltopdf";

**Comment by mikehaertl** [comment]
I'm sorry, but we can not provide support for questions regarding `wkhtmltopdf` itself. In other words: You need to understand how `wkhtmltopdf` features work before using this library. Please consult the wkhtmltopdf help with `wkhtmltopdf -H` and try to make it work on the command line first. This should help you to also make it work with our library.
