### ISSUE TITLE
Can I put/show header and footer only for the first page of the pdf?

### ISSUE THREAD

**Issue by maiconpazin** [mikehaertl/phpwkhtmltopdf#236]
I need to possibilite show a html header/footer only for specific pages. I have done it by css using display:none however the PDF keeps the height of the empty space.

**Comment by mikehaertl** [comment]
Sorry, we can not provide support for questions regarding `wkhtmltopdf` features as this is only a PHP wrapper. Please check the help with `wkhtmltopdf -H` or their website.
