### ISSUE TITLE
empty / broken pdf

### ISSUE THREAD

**Issue by daudmalik06** [mikehaertl/phpwkhtmltopdf#237]
i tried to convert freelancer.com to pdf using following options

```
'use-xserver',
'outline',
                'commandOptions' =>
                    [
                        // You can change ':0' to whatever display you pick in your daemon script
                        'procEnv' => array( 'DISPLAY' => ':0' ),
                    ],
                'custom-header'=>
                    [
                        'User-Agent'=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110'.rand().' Safari/537.36',
                    ],
                'custom-header-propagation',
                'page-size'=>'A4',
                'encoding' => 'UTF-8',
                'ignoreWarnings' => true,
                'javascript-delay'=>'2000',
                'load-error-handling'=>'ignore',
                'images',
                'orientation'=>'Landscape',
```

and it produces  following result 
![empty](https://user-images.githubusercontent.com/3526480/27773380-b57c7b28-5f78-11e7-99cb-bfcf604ba12c.JPG)

any idea whats wrong , i am just doing pdf->send()
p.s
it works perfect for other sites e.g googel.com

**Comment by mikehaertl** [comment]
Does it work on the command line with `wkhtmltopdf`?

**Comment by daudmalik06** [comment]
this is what i received  on cli
![responsefreelanc](https://user-images.githubusercontent.com/3526480/27820690-e8176e08-609f-11e7-9c8e-47c3117aae67.PNG)

**Comment by mikehaertl** [comment]
Well, if it doesn't work on the CLI then don't expect it to work under PHP. For problems like this please consult `wkhtmltopdf` support. This library here is only a PHP wrapper around this tool.

**Comment by daudmalik06** [comment]
@mikehaertl  yeah you are right thanks :)
