### ISSUE TITLE
pdf is not generated

### ISSUE THREAD

**Issue by naina96** [mikehaertl/phpwkhtmltopdf#238]
Hey,
I am trying to get a php file to be pdf it doesn't show any errors but it's blank no pdf
![code](https://user-images.githubusercontent.com/30293938/28371763-be653ed0-6c95-11e7-9b67-639a769f0b31.PNG)

**Comment by mikehaertl** [comment]
Do you have `wkhtmltopdf` executable installed on your system? It seems you're on windows, so you will also always have to configure the path to the `wkhtmltopdf.exe` with the `binary` option.

**Comment by naina96** [comment]
Thank  you so much the path was the problem indeed
