### ISSUE TITLE
Error with send function

### ISSUE THREAD

**Issue by saebakun** [mikehaertl/phpwkhtmltopdf#241]
HI,

I use this module since 2 years, but two weeks ago, my pdf send function doesn't work anymore.

If I use $pdf->save(test.pdf) it's all right, I have my pdf in the root folder. But if I make a send() my pdf is broken and not visible.

I use 2.2.2 and 1.2.5 for shell command

Thx for your help.

**Comment by saebakun** [comment]
Other thing,

if I add a html page classic (only text) it's work.

But if I add a print or a echo of a php's variable, it's not working anymore.

If this can help.

Really Thx again

**Comment by mikehaertl** [comment]
Did you change anything? Can you try to downgrade to older versions and see if they still work?

**Comment by saebakun** [comment]
Hi,

how can I downgrade please ?

I try something between our messages, I make a for like this :

`for($i=0; $i<2; $i++){
   echo $months[8];					  
}`

If I set $i<2 it's ok, step by step it's always ok until I set $i<9. It's very strange, it's like a time to wait or a memory error?

**Comment by mikehaertl** [comment]
The main question is still: Did you change anything? E.g. did you upgrade to another version.

To downgrade you can specify a version for `mikehaertl/phpwkhtmltopdf` and `mikehaertl/php-tmpfile` in your `composer.json` and run `composer update`. For details please consult the composer manual.

Also please understand that I can not help you debug your application specific code like the loops you show. This has nothing to do with our library here. If you think something is broken, we need a simple code example that I can use to reproduce the issue.

**Comment by saebakun** [comment]
Understand.

I didn't change my code, it's maybe a problem with the version of the module. I'll try some and come back to tell you.

**Comment by mikehaertl** [comment]
Closing this as there was nor further feedback. If downloads are broken I suggest to open an issue at https://github.com/mikehaertl/php-tmpfile and provide a code example to reproduce the issue.
