### ISSUE TITLE
error generating the pdf without error message

### ISSUE THREAD

**Issue by naina96** [mikehaertl/phpwkhtmltopdf#244]
Failed without error message: C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --inputArg "C:\Users\acer\AppData\Local\Temp\tmp2E3E.tmp.pdf" 
this is what is what i get when i try to generate a pdf knowing that i have already set the binary path

**Comment by mikehaertl** [comment]
Hard to say, I don't use Windows. Maybe something with the binary path is wrong or a problem with spaces (shouldn't be). You could try to play around with encoding options, see here: https://github.com/mikehaertl/phpwkhtmltopdf#note-for-windows-users

That's all I can say. From other reports I know that the extension works under windows. So unless you can point me to a bug I'm closing this as nothing is really broken.
