### ISSUE TITLE
 proc_open(): proc_open(): CreateProcess failed, error  code - 5 

### ISSUE THREAD

**Issue by immikhan6** [mikehaertl/phpwkhtmltopdf#245]
I am getting this error while creating arc diff 
 EXCEPTION: (Exception) Failed to passthru proc_open(): proc_open(): CreateProcess failed, error
 code - 5 at [<phutil>\src\future\exec\PhutilExecPassthru.php:103]
Can anyone please help

**Comment by mikehaertl** [comment]
What does our library here have to do with "arc diff" (whatever you mean by that)?

**Comment by immikhan6** [comment]
Sorry i have posted under wrong thread by mistake.
