### ISSUE TITLE
Class not found on some pages

### ISSUE THREAD

**Issue by jvdsahil** [mikehaertl/phpwkhtmltopdf#246]
normaly phpwkhtmltopdf working fine

but error come on new pages, this is not working on some or new pages
and error  display
Fatal error: Class 'mikehaertl\wkhtmlto\pdf' not found

when i add this line
require 'wkhtmltopdf/vendor/mikehaertl/phpwkhtmltopdf/src/Pdf.php';
then its work fine
but this line need only new pages

**Comment by mikehaertl** [comment]
Sorry, I can't provide help with basic class loading issues. Please consult the according documentation in composer here: https://getcomposer.org/doc/01-basic-usage.md#autoloading
