### ISSUE TITLE
footer-html isn't rendered

### ISSUE THREAD

**Issue by dni** [mikehaertl/phpwkhtmltopdf#248]
Hi!

I have a problem when iadd the option footer-html nothing is rendered

`$pdf->addPage($html, ['footer-html' => '<p>test</p>']);`

**Comment by mikehaertl** [comment]
I think, you can't set `footer-html` as page option. Don't know for sure, as I never use it myself. You should try a simple test with `wkhtmltopdf` on the command line to find out if it works there.

I'm closing this, as I don't think this is an issue of our library but rather a limitation of `wkhtmltopdf`.

**Comment by dni** [comment]
my problem was the version from apt-get install, i used the version from the web an everything worked..
