### ISSUE TITLE
Out Pdf does not follow standards

### ISSUE THREAD

**Issue by geeckmc** [mikehaertl/phpwkhtmltopdf#249]
**mupdf** render can't annotate the generated with **phpwkhtmltopdf** (mupdf android crash when you try to open only **phpwkhtmltopdf** generated pdf)

**PdfExplore** an simple tool for analyze pdf structure (**PdfExplore** android crash when you try to open only **phpwkhtmltopdf** generated pdf)

**Adobe Acrobat ** And more tools.....

**Comment by mikehaertl** [comment]
Sorry, this has nothing to do with our library. Please direct your issues to [wkhtmltopdf](https://wkhtmltopdf.org/). This here is only a PHP wrapper around that tool.

**Comment by geeckmc** [comment]
ok @mikehaertl sorry
