### ISSUE TITLE
'header-html' doesn't appear to work as an option.

### ISSUE THREAD

**Issue by bensinjin** [mikehaertl/phpwkhtmltopdf#251]
I ran into this with my own code and then decided to test by referencing the code in one of the tests in the repo...

`$pdf->addPage('<html>test</html>', array('header-html' => '<h1>Page Header</h1>', 'footer-html' => '<h1>Page Footer</h1>',));`

for example only adds a footer to the page. 'header-html' doesn't seem to work at the pdf level either (when you pass it to the pdf as apposed to the page) Is there something I'm missing?

Borrowed this from https://github.com/mikehaertl/phpwkhtmltopdf/blob/3afe8c8723fec4b32726ed6311c7997985662cf8/tests/PdfTest.php

**Comment by mikehaertl** [comment]
Did you test on the command line? Does it work there with the HTML you provided? You need to save the header content to a file, though, and pass this with `--header-html` option.

**Comment by bensinjin** [comment]
Doesn't work with provided html (the same example with 'footer-html' does) doesn't work when saved to a file .. for me..

**Comment by bensinjin** [comment]
I just realized I'm actually using a wrapper on your library (not intentionally, I came to this project late) - I'm going to see if it's causing the issue, this may not be anything to do with this library.

**Comment by mikehaertl** [comment]
If it doesn't work on the command line, then it's not a problem with this library but with wkhtmltopdf itself. Try to play around with the header HTML. I have reports that it works.

**Comment by bensinjin** [comment]
I know this is closed but I figured it out - I needed to add "<!DOCTYPE html>" to the top of the header. This has probably already been mentioned but I missed it along the way.
