### ISSUE TITLE
sh: 1: wkhtmltopdf: not found on Slim2

### ISSUE THREAD

**Issue by darknlight111** [mikehaertl/phpwkhtmltopdf#252]
hi, i'm new in Slim2 framework, i used this package following the docs, but when i trying like this : 
`$pdf = new Pdf();`
`$pdf->addPage("AAAAA");`
`if (!$pdf->send()) {`
`    echo $pdf->getError();`
`}`

i always got this : 

> sh: 1: wkhtmltopdf: not found

here is my ss:

![errror1](https://user-images.githubusercontent.com/32734255/31490558-8adfafca-af6e-11e7-8b4b-b133344bcde7.png)
![error2](https://user-images.githubusercontent.com/32734255/31490571-98aaf808-af6e-11e7-9ccf-1deb8f017a0f.png)

so what step i'd miss ?
any help will be appreciated
thanks

**Comment by mikehaertl** [comment]
Did you read the first paragraph in the README? It seems you don't have `wkhtmltopdf` installed. Also make sure you configre the `binary` option in case it is not in your search path.

**Comment by darknlight111** [comment]
@mikehaertl well, i have already installing your package...
(UBUNTU 16.04)
![error3](https://user-images.githubusercontent.com/32734255/31490965-eff750ba-af6f-11e7-96bc-f54515b805d8.png)

**Comment by mikehaertl** [comment]
Please read again, what I said: You need the `wkhtmltopdf` binary package on your system. This has nothing to do with my library here. It's a command line tool. See http://www.wkhtmltopdf.org.

**Comment by darknlight111** [comment]
aaaah, i see, well i will try now. thanks for your replied, i missed that one :(
