### ISSUE TITLE
problem with wkhtmltopdf in php

### ISSUE THREAD

**Issue by dicn1978** [mikehaertl/phpwkhtmltopdf#253]
hi i have a problem
when run the command in php script

the code that is being used goes like this:
$pdf = new Pdf($my_var);
$pdf->binary = '/usr/bin/xvfb-run -d /usr/local/bin/wkhtmltopdf';
$pdf->send($json['nombre'].".pdf",true);

and that causes this error when running in the browser

Failed without error message: /usr/bin/xvfb-run -d /usr/local/bin/wkhtmltopdf '/tmp/tmp_wkhtmlto_pdf_1E8xw8.html' '/tmp/tmp_wkhtmlto_pdf_nsd4OW.pdf'

thanks for your help

**Comment by mikehaertl** [comment]
> $pdf->binary = '/usr/bin/xvfb-run -d /usr/local/bin/wkhtmltopdf';

This is not the way you should use Xvfb with this library. Please check the section on Xvfb in the README: https://github.com/mikehaertl/phpwkhtmltopdf#installation-of-wkhtmltopdf

Apart from that I strongly recommend to use a statically compiled version of wkhtmltopdf to avoid Xvfb completely.
