### ISSUE TITLE
Options don't work, possibly due to xvfb-run

### ISSUE THREAD

**Issue by JorisDebonnet** [mikehaertl/phpwkhtmltopdf#255]
Thanks for this package, works great!

The only thing I'm missing is the options. I'm trying for example this: 
```
        $options = [
            'zoom' => 7.1,
            'encoding' => 'UTF-8',
            'user-style-sheet' => 'https://example.com/css/style.css'
        ];

        $pdf = new Pdf($options);
        $pdf->binary = 'xvfb-run wkhtmltopdf';
        $pdf->setOptions($options);
        $pdf->addPage($html, $options);
```
Not sure how many more places I should add the $options thing, but none of them are working. The zoom is just there to test whether it works :)

Luckily I can circumvent the issue by just putting the encoding and stylesheet into the <head> of the html, but what might be causing the options to fail? Is it the `xvfb-run`? I couldn't get the installation to work without...

**Comment by mikehaertl** [comment]
Did you check the section on Xvfb in the README? There's (limited) support built in. Maybe this helps.
https://github.com/mikehaertl/phpwkhtmltopdf#built-in-xvfb-support

**Comment by hakimio** [comment]
xvfb is no longer needed if you are running the latest version of wkhtmltopdf.

**Comment by mikehaertl** [comment]
Exactly. Closing this as there was no further feedback.

**Comment by JorisDebonnet** [comment]
Sorry about not answering earlier. The issue was probably indeed that I got an earlier version because I used some package manager that didn't have an updated version yet. As soon as I installed a newer version, the issue disappeared.
