### ISSUE TITLE
The Html is not saved to any file, PDF nor Image

### ISSUE THREAD

**Issue by JefferyHus** [mikehaertl/phpwkhtmltopdf#256]
When I try to save an html rendred from a php file to an image file, the current error is returned
```console
Could not run command wkhtmltoimage "C:\Windows\Temp\php9F09.tmp.html" "C:\Windows\Temp\tmp9F19.tmp.png"
```
I am on Windows 10 x64, and this is the code I use:

```php
ob_start();

// include the html
extract($parsedBody);

include dirname(__FILE__) . "/resources/reciept.php";

$output = ob_get_clean();

/* 1: Print an entire Image, start-to-finish */
$reciept = dirname(__FILE__) . '/reciept.png';

$image = new Image(array(
    'commandOptions' => array(
        'escapeArgs' => true,
        'procOptions' => array(
            // This will bypass the cmd.exe which seems to be recommended on Windows
            'bypass_shell' => true,
            // Also worth a try if you get unexplainable errors
            'suppress_errors' => true,
        ),
    )
));

$image->setPage($output);

// Add a HTML file, a HTML string or a page from a URL
// $pdf->addPage($output);

// Save the Image
$printed = $image->saveAs(dirname(__FILE__) . '/reciept.png');
```

**Comment by JefferyHus** [comment]
I have done a workaround to save rendered html to an html file then feed the Img class, but i'm still getting this error:
```console
Failed without error message: wkhtmltoimage "C:\wamp64\www\printer\src/resources/reciept.html" "C:\Windows\Temp\tmpA15.tmp.png"
```

**Comment by mikehaertl** [comment]
Did you configure the path to the `wkhtmltoimage` executable? See the `binary` option.

**Comment by JefferyHus** [comment]
Yes I did, because when I test a simple PHP file everything works fine, but only that cose which isn't working.

**Comment by mikehaertl** [comment]
I can't really help you out here. We added support for xvfb quite some time ago, but I personally never used it. I'd really recommend to avoid it and use a full version of wkhtmltopdf instead.

**Comment by JefferyHus** [comment]
I have tried lot, anyway I have fixed my issue but not using the library, even tho I must do it, I will check later and see if I can fix anything and back to you, thanks for your replies :+1: .
