### ISSUE TITLE
Command not found on Linux (Sharing Server) 

### ISSUE THREAD

**Issue by andyhartanto** [mikehaertl/phpwkhtmltopdf#260]
Hai, Mike I'm sorry for disturbing you, and I'm sorry if my English is not good, but I'll make you easy to understand.
We've some problem, after I've installed Wkhtml to the Linux (Sharing Server), and then after that I've installed composer, with your Library "Mikehaertl/phpwkhtmltopdf". 
We've got something error message, "sh : wkhtmltopdf : command not found"
After that, I've added binnary => "to/directory/of/wkhtml"
And then, We've got some error message about "sh : path/directory/wkhtml : No such file or directory
After that, I've checked with "whereis wkhtmltopdf", It's show empty directory.
Can you help me, what's wrong with it? And Can you give us, some solution, or good advice, please ?
Thank you very much for your attention

**Comment by mikehaertl** [comment]
It's `wkhtmltopdf` not `wkhtmlto`.

**Comment by andyhartanto** [comment]
Thank you @mikehaertl  For your advice. But I'm not understand what do you mean about. Please tell me little more. 
We can't  understand about what do you say, "It's wkhtmltopdf not wkhtmlto" ?
We've appreciate, about your good advice, and information.
Thank you for your attention.

**Comment by mikehaertl** [comment]
This library is a wrapper around `wkhtmltopdf`. This is a shell command that must be installed on your system. It's not called `wkhtmlto` as in your configuration.

**Comment by andyhartanto** [comment]
Thank you @mikehaertl for your response. I've appreciate.
But I've solution for this error.
We've must add ' ./wkhtmltopdf/path_to_bin/wkhtmltopdf ' on binary configuration.
We've missed add ' ./ ' in front of the path.
And It's make trouble and error for us.
So, now It's can work properly like what we want.
Thank you @mikehaertl for your library, It's very usefull.
We're hope, you and your team have a good future.
Best Regards,

Andy
