### ISSUE TITLE
"Could not run command" Error

### ISSUE THREAD

**Issue by DRogueRonin** [mikehaertl/phpwkhtmltopdf#261]
wkhtmltopdf version: 0.12.3.2
on Debian

The command that could not be run
```
xvfb-run -a --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltopdf --encoding 'UTF-8' --page-size 'A4' --margin-top '1.1cm' --margin-right '0.6cm' --margin-bottom '1.7cm' --margin-left '2.5cm' --page-height '29.7cm' --use-xserver '/var/www/clients/client13/web20/tmp/tmp_wkhtmlto_pdf_3MpOGX.html' '/var/www/clients/client13/web20/tmp/tmp_wkhtmlto_pdf_3ZjIEd.pdf'
```

The options passed in php
```
$pdf = new \mikehaertl\wkhtmlto\Pdf([
			'binary' => '/usr/bin/wkhtmltopdf',
			'encoding' => 'UTF-8',
			'page-size' => 'A4',
			//'disable-smart-shrinking',
			'margin-top' => '1.1cm', 
			'margin-right' => '0.6cm', 
			'margin-bottom' => '1.7cm', 
			'margin-left' => '2.5cm', 
			'page-height' => '29.7cm', 

			'use-xserver',
			'commandOptions' => [
				#'useExec' => true,
				'procEnv' => [
					'LANG' => 'de_DE.UTF-8',
				],
				'enableXvfb' => true,
			],
		]);
```

When I use `useExec => true` it's working. BUT the encoding is totally broken. Every umlaut is broken.

When I use it from the command line with the exact same options but use `https://www.google.de` as source and `google.pdf` as output, everything's working.

I tried running it with `enableXvfb` and without and adding it in manually, but nothing works.

On Ubuntu 14.04 it's working with the exact same input but with wkhtmltopdf version 0.9.9 for some reason.

**Comment by mikehaertl** [comment]
Try with a statically linked version of `wkhtmltopdf` (download it from their website) and don't use xvfb.

**Comment by DRogueRonin** [comment]
Thanks, I'll try that.

Do you mean don't use xvfb with the option passed via PHP or don't use xvfb at all? But what should I use instead?

**Comment by DRogueRonin** [comment]
I got wkhtmltopdf version: 0.12.4 now with patched qt (0.9.9 was without but there it works somehow), 
but it's still throwing the same error.

CLI and everything still works just not when issued from the PHP script.

**Comment by mikehaertl** [comment]
You only need Xvfb with the unpatchted (non-static) version of wkhtmltopdf. It's kind of a hack. Also remove the `use-xserver` and the other `commandOptions`. You shouldn't need them.

What's the error message you get from `$pdf->getError()`?

**Comment by DRogueRonin** [comment]
Ok I did that, but it's still the same error, only now it's not wrapped into the xvfb-run command.

```
Could not run command /usr/local/bin/wkhtmltopdf --encoding 'UTF-8' --page-size 'A4' --margin-top '1.1cm' --margin-right '0.6cm' --margin-bottom '1.7cm' --margin-left '2.5cm' --page-height '29.7cm' '/var/www/clients/client13/web20/tmp/tmp_wkhtmlto_pdf_uz6kZX.html' '/var/www/clients/client13/web20/tmp/tmp_wkhtmlto_pdf_x7xMfe.pdf'
```

**Comment by mikehaertl** [comment]
Hmm, if you look here, the error appears if PHP could not successfully open the process for `wkhtmltopdf`:
https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L346

If you want to do some debugging, you could play around with a simple script where you try a simpler call to `wkhtmltopdf` via `proc_open()`. It's nothing special, so not sure, why it doesn't work for you. Maybe some security related limitation in your OS (SELinux, ...)?

Also check the PHP docs here: http://php.net/manual/en/function.proc-open.php

**Comment by DRogueRonin** [comment]
In the end it was as simple as removing `proc_open` from the `disabled_functions` directive in the php.ini.

Thanks @mikehaertl for all the fast responses!
