### ISSUE TITLE
How to calc count pages PDF after saveAs

### ISSUE THREAD

**Issue by nemozar** [mikehaertl/phpwkhtmltopdf#262]
Hi.

How i can calc count page from generated PDF from HTML?

i use **header-html** and i can write page count in pages via JS variable. But me need get page count in PHP after generate PDF.

**Comment by mikehaertl** [comment]
Sorry, I can't help you with questions like these. This extension is only a wrapper around `wkhtmltopdf` to create PDF from HTML. There's no way to get back information about the PDF from `wkhtmltopdf`.

You could maybe try my other extension to analyse the created PDF afterwards: https://github.com/mikehaertl/php-pdftk#get-pdf-data
