### ISSUE TITLE
sh: /usr/local/bin/wkhtmltopdf: Permission denied

### ISSUE THREAD

**Issue by Snick720** [mikehaertl/phpwkhtmltopdf#263]
my code is this:
`$html = ob_get_clean();

$options = array(
    'no-outline', // option without argument
    'encoding' => 'UTF-8', // option with argument
    'page-size' => $data->config->pagesize,
    'orientation' => $data->config->orientacion,
    'binary'=>'/usr/local/bin/wkhtmltopdf'
);

$pdf = new Pdf();

$pdf->setOptions($options);

$pdf->addPage($html);

if (!$pdf->send()) {
    echo $pdf->getError();
}`

in windows works fine, but when i try use this in my server centos 6.6 throw me the error 
sh: /usr/local/bin/wkhtmltopdf: Permission denied
i try given the perission whit: chmod +x /usr/local/bin/wkhtmltopdf, but not work i change de owner to apache but the error is the same, i verify the route whit "which wkhtmltopdf" bout the path is the correct, when use wkhtmltopdf in console works fine

**Comment by mikehaertl** [comment]
Probably some security restriction that either forbids calls to `proc_open()` in PHP or calls to shell commands from PHP on Centos. I think we already had several reports for this. I can't really help you with that and suggest to google the problem.

**Comment by tigerofmurder** [comment]
if you use net core or .net, use: `sudo chmod 777 -R <Directorio que contiene el wkhtmltopdf>`
