### ISSUE TITLE
Webserver hangs

### ISSUE THREAD

**Issue by RossAWaddell** [mikehaertl/phpwkhtmltopdf#269]
I'm using this sample code:

```
    ob_start();

... bunch of PHP code & HTML

    $html = ob_get_clean();
    use mikehaertl\wkhtmlto\Pdf;

    // You can pass a filename, a HTML string or an URL to the constructor
    $pdf = new Pdf($html);
    $pdf->binary = '/usr/local/bin/wkhtmltopdf';

    if (!$pdf->saveAs('../../../../private/contest/tmp/' . $entryNum . '.pdf')) {
        echo $pdf->getError();
    }
```
I know the HTML is good as I've run it through various validation tools.

My Apache webserver appears to hang (in FF the browser tab shows it's waiting for a response) and no .pdf file is generated, and no errors appear in the PHP log file.

My composer.json:

```
{
    "require": {
        "monolog/monolog": "^1.23",
        "phpfastcache/phpfastcache": "^6.1",
        "phpmailer/phpmailer": "^6.0",
        "dompdf/dompdf": "^0.8.2",
        "mpdf/mpdf": "^7.0",
        "knplabs/knp-snappy": "^1.0",
        "mikehaertl/phpwkhtmltopdf": "^2.3"
    },
    "config": {
        "platform": {
            "php": "5.6.32"
        }
    }
}
```
I'm running PHP v5.6.32 on MAMP.

**EDIT**
The hang seems to have been caused by the `ob_get_clean()` call being inside the `<body>` of the html, hence it never got the closing tags `</body></html>`. Fixing that resolved the hang. However, I still see my images are missing even though I've got absolute paths to them on our hosted site, which render fine when I copy-and-paste the path to a browser. Also, the resulting pdf page is postage-stamp sized with the no-print part included.

**Comment by mikehaertl** [comment]
Sorry, I can't help you with this. This is not a support forum but for reporting bugs. The library is based on `wkhtmltopdf` so you may have to invest some research time to figure out, how to use it. It only wraps wkhtmltopdf calls in a PHP class.

**Comment by LuanMaik** [comment]
I had the same problem, but i resolve adding the option:

```
$options = [
   //others options,
   'commandOptions' => array(
            'useExec' => true, // <- this resolve in my case
    )
];
```
