### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by lazzyms** [mikehaertl/phpwkhtmltopdf#272]
I am trying to convert html to pdf, on a Click action I want to download the pdf generated in browser.
`$pdf->send('report.pdf');`
throws this error : ERR_CONTENT_LENGTH_MISMATCH.
While this works fine : `$pdf->saveAs('report.pdf');`

**Backend** : _PhalconPhp_

**Comment by mikehaertl** [comment]
This sounds very much the same like this issue: #270. Can you verify if you also have mod_deflate enabled?

**Comment by lazzyms** [comment]
Ok. got my bug. I forced function to return response contentType : application/json instead of applicatoin/pdf.
