### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Mr-AjayM** [mikehaertl/phpwkhtmltopdf#273]
Error to convert PDF

require __DIR__ . '/vendor/autoload.php';

use mikehaertl\wkhtmlto\Pdf;

$pdf = new Pdf('/certificate/demo.html');

if (!$pdf->saveAs('/certificate/demo.pdf')) {
	$pdf->getError();
}
 

Fatal error: Class 'mikehaertl\shellcommand\Command' not found

**Comment by mikehaertl** [comment]
This is composer basics. https://getcomposer.org/doc/01-basic-usage.md#autoloading
