### ISSUE TITLE
It doesn't work in google map

### ISSUE THREAD

**Issue by ezekel** [mikehaertl/phpwkhtmltopdf#276]
Hi, I am having problem looks like that the google map cannot be captured ,I tried text and images and it has no problem but only the google map, there is no map displayed after it convert to image.

**Comment by mikehaertl** [comment]
This is probably a limitation of `wkhtmltopdf` itself. Our library is only a little wrapper class about the command line tool. If it doesn't work there it will not work here.

**Comment by ezekel** [comment]
@mikehaertl , before it works but now it doesn't work. How can I genereate the image using command in cli?
