### ISSUE TITLE
PHP inside addPage

### ISSUE THREAD

**Issue by greyfoxjump** [mikehaertl/phpwkhtmltopdf#277]
This is likely not an issue, I am just not sure where else to post for support. I am trying to use PHP inside of this string;

`$pdf->addPage('<html>tit</html>');`

The PHP I am attempting to use is;

`<?php echo htmlentities($_POST['iname']);?>`

How would I go about doing this;

`$pdf->addPage('<html><?php echo htmlentities($_POST['iname']);?></html>');`

I know that does not work but does anybody know if it is possible to do something like that?

**Comment by mikehaertl** [comment]
Sorry, but this is not a support forum. Your question is really basic PHP and has nothing to do at all with this library here.

**Comment by greyfoxjump** [comment]
Hmmmm....

> Your question is really basic PHP and has **nothing to do at all with this library here**.

```
use mikehaertl\wkhtmlto\Pdf;

$pdf = new Pdf;
$pdf->addPage('/path/to/page.html');
$pdf->addPage('<html>....</html>');
$pdf->addPage('http://www.example.com');
```

`$pdf->addPage('<html>....</html>');`
