### ISSUE TITLE
Corrupt Image

### ISSUE THREAD

**Issue by greyfoxjump** [mikehaertl/phpwkhtmltopdf#278]
Privacy.

**Comment by mikehaertl** [comment]
Could it be this: #270 ?

**Comment by mikehaertl** [comment]
The question is rather: Do you have mod_deflate or similar enabled in your webserver?

What you can also try: Compare the HTTP headers sent when you directly download the image you saved on the server to those when you use `send()`.

**Comment by greyfoxjump** [comment]
Tested on Debian 9 and Ubuntu 14.04, currently using Ubuntu, here is the live example;

http://155.254.35.63/test.php

- mod_deflate (Disabled)
- wkhtmltopdf/image is correctly installed on version 0.12.2.1 (patched qt)
- PHP5 (No custom settings/fresh Ubuntu install with lamp installed)

My File.php has the correct permissions, I have tried editing out said lines and not editing out said lines and the same problem still occurs.

My test.php file shows;

```
<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

?>

<?php

$loader = require __DIR__ . '/vendor/autoload.php';

?>

<?php

use mikehaertl\wkhtmlto\Image;

$image = new \mikehaertl\wkhtmlto\Image('https://www.google.com');
$image->setOptions(array(
'binary' => '/usr/local/bin/wkhtmltoimage',
'type' => 'png'
));

$image->saveAs('page.png');
$image->send('page.png');

?>
```

No errors within apaches error.log file, no visible PHP errors with reporting on. I am not 100% sure what you mean by comparing the headers? I will look into that now.

**Comment by mikehaertl** [comment]
https://developer.mozilla.org/de/docs/Web/HTTP/Headers
https://www.mkyong.com/computer-tips/how-to-view-http-headers-in-google-chrome/

**Comment by greyfoxjump** [comment]
I am familiar with chromes developer tools, I did actually check that before and nothing. When I navigate to (http://155.254.35.63/test.php), I don't see any headers either post or get requests...?

**Comment by mikehaertl** [comment]
I can not help you with debugging HTTP headers. Each and every request and response has HTTP headers. So it's the first thing that comes to mind if there's a difference between `saveAs()` and d/l and `send()`. If the content is the same it can only be the headers that differ.

**Comment by greyfoxjump** [comment]
IDK why that was not showing, just hopped onto my laptop and managed to get some information from the headers;

**General**
```
Request URL: http://155.254.35.63/test.php
Request Method: GET
Status Code: 200 OK
Remote Address: 155.254.35.63:80
Referrer Policy: no-referrer-when-downgrade
```

**Response Headers**
```
HTTP/1.1 200 OK
Date: Thu, 26 Apr 2018 08:58:07 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.24
Pragma: public
Expires: 0
Cache-Control: must-revalidate, post-check=0, pre-check=0
Content-Transfer-Encoding: binary
Content-Length: 2035503
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: image/png
```

**Request Headers**
```
GET /test.php HTTP/1.1
Host: 155.254.35.63
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
```

Again, this is a fresh install of Ubuntu 14.04 minimal specifically for troubleshooting this, I have disabled mod_deflate and I have not got any .htaccess or custom files/made any changes to the default settings apart from of course mod_deflate.

**Comment by mikehaertl** [comment]
I don't know either. It sounds very weird that you say `saveAs()` works while `send()` does not. Both use the same file (temporarily saved on disk). The one only copies the file to your saveAs-location and the other sends the file.

Try to call `saveAs()` and then `send()` the file for download and then compare the binary content. It must be the same.

I'm sorry, but I have no further ideas.

**Comment by greyfoxjump** [comment]
Mike, I figured some things out. This really, really f**** annoyed me so hopefully you can potentially look at this work-around and figure out what may of caused the issue?

`<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

?>

<?php

$loader = require __DIR__ . '/vendor/autoload.php';

?>

<?php

use mikehaertl\wkhtmlto\Image;

$image = new \mikehaertl\wkhtmlto\Image('https://www.google.co.uk/search?q=what+is+the+time&oq=what+is+the+time&aqs=chrome.0.69i59j0l5.1536j0j4&sourceid=chrome&ie=UTF-8');
$image->setOptions(array(
'binary' => '/usr/local/bin/wkhtmltoimage',
'type' => 'png'
));

$image->saveAs('tmp/page.png');

$image = 'tmp/page.png';
$imageData = base64_encode(file_get_contents($image));
echo '<img src="data:image/png;base64,'.$imageData.'">';

unlink('tmp/page.png');
die();

?>`

Now, I am amature if that when it comes to PHP. I don't know if this is bad practice but it works exactly how it should work, you can see the live demo;

http://155.254.35.63/test.php

**Comment by mikehaertl** [comment]
Hmm, while it looks a bit hacky to me - if it works I'd say it's fine.

I'm sorry, that I can't offer more assistance. TBH I myself never used `wkhtmltoimage` and only added this as per request of another user. All this is vulonteers work, you know, so I can't guarantee that everything always works as it should and I don't have the time to fix each and every possible problem immediately.
