### ISSUE TITLE
Undesirable extra blank Page

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#279]
Hello,
I am still using version **5.6** and there I have the problem, that after each page is added one blank/empty page.
Probably it is problem in the wkhtmltopdf library. Do you have same experiences? 
Thank You for any hint

**Comment by mikehaertl** [comment]
Sorry, I have no idea, check the wkhtmltopdf docs. This is for reporting bugs in our library.
