### ISSUE TITLE
HTML, instead of pdf

### ISSUE THREAD

**Issue by serjs11** [mikehaertl/phpwkhtmltopdf#280]
Hello. Please help me. I have a problem, i give phpwkhtmltopdf html file, like in examples, 

```
$pdf = new Pdf('/path/to/page.html');

if (!$pdf->saveAs('page.pdf')) {
    echo $pdf->getError();
}
$pdf->send('page.pdf');
```
i also did like that: 
```
$pdf = new Pdf([
                 'binary' => '/usr/bin/wkhtmltopdf',
                'ignoreWarnings' => true,
                 'commandOptions' => [
                  'useExec' => true,      // Can help if generation fails without a useful error message
                  'procEnv' => [
                         // Check the output of 'locale' on your system to find supported languages
                         'LANG' => 'en_EN.utf-8',
                     ]]
            ]);
            $pdf->addPage('https://mysite.ru/page-01.html');
            if (!$pdf->saveAs('test.pdf')) {
                echo '<pre>'.$pdf->getError().'</pre>';
            }
            $pdf->send('test.pdf');

```
But i can't open pdf file like pdf, if i open it by phpstorm or sublime i see just html code, no pdf =(((
And this html belongs to the page where my script starts.

Script returns no errors.

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but meant to report bugs. And your problem description does not sound like it has to do with our library here. You seem to mix PDF generation with other HTML output. I can not help you fix your code.
