### ISSUE TITLE
header-html from string without doctype fails

### ISSUE THREAD

**Issue by jaysee** [mikehaertl/phpwkhtmltopdf#281]
Hello,

creating a page with : 

`$pdf->addPage( '<html>test page</html>' );`

works but this kind of html content fails when used for header like this : 

`$pdf->addPage( '<html>test page</html>', [ 'header-html' => '<html>test header</html>' ] );`

adding `<!DOCTYPE html>` fixes it:

`$pdf->addPage( '<html>test page</html>', [ 'header-html' => '<!DOCTYPE html><html>test header</html>' ] );`

(Curiously it works for the footer-html option!)

regards,
jC

**Comment by mikehaertl** [comment]
Hmm, I think this is rather an issue with `wkhtmltopdf` itself. It usually expects a filename/url as argument for `--header-html`. So our library creates a temporary file if it detects a HTML string. This works exactly the same for `--header-html` and `--footer-html`. So if you say it works for the footer I'd recommend to do a quick test on the command line.

Create a html file with your header content and call wkhtmltopdf manually. Then see if you have the same problems. 

BTW what exactly is the problem?

**Comment by faheemhameed** [comment]
I am having "wkhtmltopdf 0.12.5 (with patched qt)" Mac OS 10.13.5
I get the same issue as well.

The header html does not show in the output pdf. Your script seem to generate the command correctly.

`/usr/local/bin/wkhtmltopdf --margin-top '5cm' --margin-right '0' --margin-bottom '2cm' --margin-left '0' --header-html '/private/var/tmp/tmp_wkhtmlto_pdf_FWRdRk.html' --footer-html '/private/var/tmp/tmp_wkhtmlto_pdf_yycTeK.html' --disable-smart-shrinking --dpi '374' --zoom '1' --load-error-handling 'ignore' --encoding 'utf-8' --page-size 'A4' --orientation 'Portrait' '/private/var/tmp/tmp_wkhtmlto_pdf_Y4m8ut.html' '/private/var/tmp/tmp_wkhtmlto_pdf_pio7tp.pdf'`

something to do with wkhtmltopdf

I am further checking this and will update.

**Comment by faheemhameed** [comment]
`/usr/local/bin/wkhtmltopdf --margin-top '5cm' --margin-right '0' --margin-bottom '2cm' --margin-left '0' --header-html '/Users/hameedbs/Projects/temp/header.html' --footer-html '/Users/hameedbs/Projects/temp/footer.html' --disable-smart-shrinking --dpi '374' --zoom '1' --load-error-handling 'ignore' --encoding 'utf-8' --page-size 'A4' --orientation 'Portrait' '/Users/hameedbs/Projects/temp/content.html' '/Users/hameedbs/Projects/temp/content.pdf'`

If I manually run the above code the the header & footer html did show properly.

Something related to your php wrapper?

**Comment by faheemhameed** [comment]
Actually it's to do with adding "<!DOCTYPE html>" to your html text.

When added the header & footer showed fine through your code. Thanks a lot!

**Comment by faheemhameed** [comment]
Footer did show correctly even if you have not added <!DOCTYPE html>

**Comment by mikehaertl** [comment]
Can you give a full (minimal!) PHP code example that demonstrates the issue?

**Comment by mikehaertl** [comment]
Closes because there was no further feedback.
