### ISSUE TITLE
Error "sh: 1: wkhtmltopdf: not found"

### ISSUE THREAD

**Issue by benjbmc** [mikehaertl/phpwkhtmltopdf#282]
Hello, 

I get this error with `$pdf->getError()`:
>     sh: 1: wkhtmltopdf: not found

Also dump from `$pdf` gives me `_exitCode` to 127.

I read that it was probably because of wkhtmltopdf binary not installed on server, but I'm getting `/usr/bin/wkhtmltopdf` with this command: `which wkhtmltopdf`.
It means binary is installed, no ? 

Any idea to solve this ?
Thanks,

**Comment by mikehaertl** [comment]
I'm getting a bit tired of answering this same question over and over again :unamused: . It's mentioned in the README, at least at 2 places, the first right on top in one of the first paragraphs. Check the `binary` option.

**Comment by benjbmc** [comment]
Thing is I've already read your README carefully, which by the way is very complete, thank you for that :)

In binary option you say "Default is wkhtmltopdf which assumes that the command is in your shell's search path."
Indeed I can run it, I checked it with `wkhtmltopdf --version`, but still I get this error. Same error when I put full path in binary option. That's why I asked for information. 

Sorry if you get tired of this question, and thank you for your quick answer.

**Comment by mikehaertl** [comment]
What's your OS? Some have restrictions on which commands you can execute from PHP. You have to do some research to find out. Also try if you can run `wkhtmltopdf` with `exec()`. If this works you must be overlooking something because our library does nothing different.

**Comment by benjbmc** [comment]
Actually I made a mistake, I checked shell's search path on my local environment (Linux Mint) but as I'm working with Docksal which uses Docker, it's not to taken into account.. 
With full path for binary option it's OK on remote server. I'm still trying to make it work on my local environment..
Thank you anyway !

**Comment by Troldefar** [comment]
$path = 'which wkhtmltopdf';
$pdf->binary = $path;

Worked for me
