### ISSUE TITLE
run-script option not working

### ISSUE THREAD

**Issue by kiranbariya** [mikehaertl/phpwkhtmltopdf#283]
below is my code

$BinaryPath=PHP_OS=='WINNT'?DIR_CLASS.'vendor\mikehaertl\binary\wkhtmltopdf\bin\wkhtmltopdf':DIR_CLASS.'vendor/mikehaertl/binary/wkhtmltox/bin/wkhtmltopdf';
        $options = ['no-collate',
	'margin-left'=>$this->marginLeft,
	'margin-top'=>$this->marginTop,
	'margin-right'=>$this->marginRight,
	'margin-bottom'=>$this->marginBottom,
	'orientation'=>$this->orientation,
        'page-size'=>$this->pageSize,
        'page-height'=>$this->pageHeight,
        'page-width'=>$this->pageWidth,
        'header-left'=>'[title]',
        'header-line',
        'header-font-size'=>'10',
        'header-spacing'=>'3',
        'footer-right'=>'Page [page] of [topage] ',
        'footer-font-size'=>'10',
	'footer-spacing'=>'3'
        ,'debug-javascript','enable-javascript','javascript-delay'=>1000,'no-stop-slow-scripts','run-script'=>  dirname(__FILE__).'/pdfjs.js'
        ];
        $pdf = new mikehaertl\wkhtmlto\Pdf($options);
        $pdf->binary = $BinaryPath;
        $pdf->addPage($PdfHtml);

        if($SaveToPath==null)
        {
            if(!$pdf->send())
            {
                return $pdf->getError();
            }
        }

And pdfjs.js File code like
document.getElement('body').innerHTML='sadsdasd';

**Comment by mikehaertl** [comment]
Does it work on the command line? We can not fix things that don't work with "raw" wkhtmltopdf. All we do is to call wkthmltopdf with all the arguments.

If it works there do some debugging. Try with a very simple and reduced example.

**Comment by kiranbariya** [comment]
It works on cammand line. 
D:\wkhtmltopdf\bin>wkhtmltopdf.exe --run-script "var thead = document.getElementById('table').tHead;var div = document.createElement('div');div.className='background';div.innerHTML='<p class=\"gb-text\">watrermark</p>';thead.insertBefore(div,thead[0]);" cmdSource.html test2.pdf

but not using phpwkhtmltopdf library.

**Comment by mikehaertl** [comment]
In your code example you use `dirname(FILE).'/pdfjs.js'`, but on the command line you use some inline js. I think you can't pass a filename to this option.

**Comment by kiranbariya** [comment]
i have changed and test this to inline script but still not to work.

**Comment by mikehaertl** [comment]
Is there any error? How does the generated command look?

```
$pdf->saveAs('test.pdf');
echo $pdf->getCommand()->getExecCommand();
```

**Comment by kiranbariya** [comment]
This cammand get message as below

D: && cd "D:\xampp\htdocs\InfraERP\ERP/class/vendor\mikehaertl\binary\wkhtmltopdf\bin" && wkhtmltopdf --no-collate --margin-left "5mm" --margin-top "10mm" --margin-right "5mm" --margin-bottom "10mm" --orientation "Portrait" --page-size "A4" --page-height "297mm" --page-width "210mm" --header-left "[title]" --header-line --header-font-name "Verdana" --header-font-size "9" --header-spacing "3" --footer-right "[page] of [topage] pages" --footer-font-name "Verdana" --footer-font-size "9" --footer-spacing "3" --footer-line --no-pdf-compression --print-media-type --run-script "document.getElementsByTagName('body')[0].innerHTML = 'none';" "C:\Windows\Temp\tmpA42D.tmp.html" "C:\Windows\Temp\tmpA42E.tmp.pdf"

**Comment by kiranbariya** [comment]
My Class is like below

class WkPdfAction
{
    public $marginLeft='10mm';
    public $marginRight='10mm';
    public $marginTop='10mm';
    public $marginBottom='10mm';
    public $orientation='Portrait';
    public $pageSize='A4';
    public $pageHeight='297mm';
    public $pageWidth='210mm';
    public $HeaderFooterFontName='Verdana';
    public $DocumentHeaderText='[title]';
    public $DisableSmartShrinking=false;

    public function __construct()
    {

    }

    public function GeneratePdf($PdfHtml,$SaveToPath=null)
    {
        $BinaryPath=PHP_OS=='WINNT'?DIR_CLASS.'vendor\mikehaertl\binary\wkhtmltopdf\bin\wkhtmltopdf':DIR_CLASS.'vendor/mikehaertl/binary/wkhtmltox/bin/wkhtmltopdf';
        $options = ['no-collate',
	'margin-left'=>$this->marginLeft,
	'margin-top'=>$this->marginTop,
	'margin-right'=>$this->marginRight,
	'margin-bottom'=>$this->marginBottom,
	'orientation'=>$this->orientation,
        'page-size'=>$this->pageSize,
        'page-height'=>$this->pageHeight,
        'page-width'=>$this->pageWidth,
        'header-left'=>$this->DocumentHeaderText,
        'header-line',
        'header-font-name'=>$this->HeaderFooterFontName,
        'header-font-size'=>'9',
        'header-spacing'=>'3',
        'footer-right'=>'[page] of [topage] pages',
        'footer-font-name'=>$this->HeaderFooterFontName,
        'footer-font-size'=>'9',
	'footer-spacing'=>'3',
	'footer-line',
        'no-pdf-compression',
        'print-media-type',
         'run-script'=>"document.getElementsByTagName('body')[0].innerHTML = 'none';"
        ];

        if($this->DisableSmartShrinking)
        {
           $options[]= 'disable-smart-shrinking';
        }

        $pdf = new mikehaertl\wkhtmlto\Pdf($options);
        $pdf->binary = $BinaryPath;
        $pdf->addPage($PdfHtml);
        $pdf->saveAs('test.pdf');
        echo $pdf->getCommand()->getExecCommand();
    }
}

**Comment by kiranbariya** [comment]
it Works



Thanks

**Comment by mikehaertl** [comment]
So what was the problem and how did you solve it? This could help others with the same question.

**Comment by kiranbariya** [comment]
I think the Problem should be in single or double quote.
I wrote syntex like 
'run-script'=>'document.getElementsByTagName("body")[0].innerHTML="inner Text"' //It Doesn't works but 
I wrote syntax like
'run-script'=>"document.getElementsByTagName('body')[0].innerHTML='inner Text'"  //It Works 

In short,
 Your script is Proper without any warning or error then script is working other wise not work
