### ISSUE TITLE
Where is tmp html saved?

### ISSUE THREAD

**Issue by amirbilal** [mikehaertl/phpwkhtmltopdf#285]
Hi there,

This is not an issue but I am trying to figure out something.

While generating a multi page PDF (which generates successfully), I was debugging the code and for some reason I never find the temporary HTML file in /tmp that is passed to wkhtmltopdf.

e.g. 
'/tmp/tmp_wkhtmlto_pdf_7m6CPu.html' 

Can you please tell me, where is it saved? I need this HTML for another program.

thanks,

**Comment by mikehaertl** [comment]
Check the `tmpDir` option [here](https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options):

* `tmpDir`: Path to tmp directory. Defaults to the PHP temp dir.

**Comment by amirbilal** [comment]
Thanks Mike for your in time reply. Much appreciated !
