### ISSUE TITLE
pdfwkhtmltopdf , saveAs(); works but not send(); or send('filename');

### ISSUE THREAD

**Issue by alrowaihi** [mikehaertl/phpwkhtmltopdf#289]
hi , 
I've set up the whole environment needed to generate pdf from html resources , 
but when I test the code I find that it works fine with the function saveAs(); and I can find the pdf file and open it successfully , 
but when I use the function send(); it opens the browser as it will show the pdf file but then an error message shows up and says : Failed to load PDF document.

here is the code I'm using 
```

<?php
require 'vendor/autoload.php';
use mikehaertl\wkhtmlto\Pdf;

$pdf = new Pdf(array(
    'binary' => 'wkhtmltopdf',
    'ignoreWarnings' => true,
    'commandOptions' => array(
        'useExec' => true,      // Can help if generation fails without a useful error message
        'procEnv' => array(
            // Check the output of 'locale' on your system to find supported languages
            'LANG' => 'en_US.utf-8',
        ),
    ),
));




$pdf->addPage('test.html'); // a .html file in the root of the site
$pdf->send();

?>
```

no matter what the array attributes are , it doesn't work even I use 
```
$pdf = new Pdf;
$pdf->addPage('test.html');
```

I really need help in this as the previous developers used mPDF library but it fails in generating more than 500 records ,, so I've decided to use mkhtmltopdf

**Comment by alrowaihi** [comment]
mmm , I don't know about it , I've read it before but couldn't find the solution  , I'm using localhost through ampps so I can send files to server when everything works fine ,,
I came up to a solution which is saving the pdf file first and then open it using the link , would I get any help to that ? and many thanks in advanced

**Comment by mikehaertl** [comment]
Sorry, I can't provide any help or support. We only fix bugs here and do . You need to do some research on how to check your webserver config and if compression is enabled there.

Your solution with saving the file and providing the download link should work, too. But that's really your job. I can't do that for you :).

**Comment by alrowaihi** [comment]
thanks , it worked now , I've deleted this code from File.php 
```

// $isIOS = preg_match('/i(phone|pad|pod)/i', $_SERVER['HTTP_USER_AGENT']);
        // if (!$isIOS) {
        //     header('Content-Length: '.filesize($this->_fileName));
        // }
```

**Comment by alrowaihi** [comment]
as I don't need to explore reports through any mobile or tablet
