### ISSUE TITLE
Doesn't output the PDF

### ISSUE THREAD

**Issue by apatuka** [mikehaertl/phpwkhtmltopdf#290]
I have this code:
```
		$pdf = new mikehaertl\wkhtmlto\Pdf(array(
			'tmpDir' => 'C:\\Bitnami\\',
		    'commandOptions' => array(
		    	'useExec' => true,
		        'escapeArgs' => false,
		        'procOptions' => array(
		            'bypass_shell' => true,
		            'suppress_errors' => true,
		        ),
		    )
		));
		$pdf->addPage($html);
		$pdf->binary = 'C:\\wkhtmltopdf\\bin\\wkhtmltopdf.exe';
		$pdf->send();

```

I have an predefined html on $html variable, but doesn't do anything, i checked everything from the execution command, windows permissions and settings. Only works if i send an URL.

**Comment by mikehaertl** [comment]
Did you check for any errors? I've just updated the readme and added error checks to all examples as this is missing from so many reports here. You should always try this first.

And what do you mean by "if i send an URL"? Which URL?

**Comment by apatuka** [comment]
I checked and it gives me an "No content error" also checked if doesn't generates the ".tmp.html" but no luck and that's why it wont generate the PDF. But if i send an url to generate, i tried google.com and it works perfects.

**Comment by mikehaertl** [comment]
The option to pass HTML content as a string is our extension to the original `wkhtmltopdf`. For this to work the string must contain a `<html>` tag, othwerhise we can't detect that you didn' pass a filename or URL. See this regex here: https://github.com/mikehaertl/phpwkhtmltopdf/blob/master/src/Pdf.php#L21

So can you make sure, that your `$html` contains a `<html>` tag?

**Comment by apatuka** [comment]
> Loading pages (1/6) [> ] 0% [======> ] 10% [=============> ] 23% Error: Failed to load file:///pokeadmin_v2/js/jquery.min.js, with network status code 203 and http status code 0 - Error opening /pokeadmin_v2/js/jquery.min.js: El sistema no puede encontrar la ruta especificada. [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) Printing pages (6/6) [> ] Preparing [============================================================] Page 1 of 1 Done Exit with code 1 due to network error: ContentNotFoundError

Looks like it wont generate because of a javascript file. Will try without that JS

**Comment by apatuka** [comment]
It works ! Using the getError() i could get the reason and now it works, thanks !
