### ISSUE TITLE
what is the SetDirection function , and page number account  in phpwkhtmltopdf ?

### ISSUE THREAD

**Issue by alrowaihi** [mikehaertl/phpwkhtmltopdf#291]
hello ,
I'm using mikehaertl phpwkhtmltopdf to produce pdf reports , but I need the function that sets the direction ( RTL ) , 
in mpdf it's like : `$mpdf->SetDirectionality('rtl'); `
is there a similar one ?

plus , I need to add page number count on each page , how is that to be ??

many thanks in advance .
My regards

**Comment by alrowaihi** [comment]
hey , 
I may wrote this in hurry , but I solved the issue of direction by adding dir="rtl" in html code , so it worked but there are some page improvements which I will work on it later ,,

now I still have the issue of adding page numbers count on footer of each page ,, if you could help me I will be so grateful ,,

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but for reporting bugs. Please consult the README and the output of `wkhtmltopdf -H` for the available options or ask for support on the wkhtmltopdf project (we are only a PHP wrapper library here).
