### ISSUE TITLE
Image is  not displayed in the pdf

### ISSUE THREAD

**Issue by Georgyge** [mikehaertl/phpwkhtmltopdf#293]
Hi,
  I have currently installed wkhtmltopdf. My objective is to take the pdf of the webpage. And I have the used the below line for adding the url.

> $pdf->addPage('http://www.example.com');

The problem is , it is generating the pdf. But images are not displayed. I had read that, we need to give the absolute path for images. But here, we are using the url of a webpage. So it is not possible to give the absolute path for images for the whole website(maybe we will be using other webpages which are not developed by us).

How to solve this issue?

**Comment by mikehaertl** [comment]
This is a question for wkthmltopdf, not our wrapper here. Please check their website or project page on github for support.
