### ISSUE TITLE
Differences between wkhtmltopdf and phpwkhtmltopdf

### ISSUE THREAD

**Issue by erwinelling** [mikehaertl/phpwkhtmltopdf#295]
Somehow I come across some differences between using wkhtmltopdf directly via the command line and using the phpwkhtmltopdf wrapper (on the same server). I'd like to understand if I am not doing things right:

Similarities:

- I am rendering a PDF from a html source (with quite some loadtime);
- The only argument I am using in both cases is to make the output landscape;
- The results is a 22 page PDF.

Differences:

- wkhtmltopdf takes ~10 seconds, phpwkhtmltopdf takes more than 2 minutes;
- wkhtmltopdf generates a ~560kB file, phpwkhtmltopdf generates a ~3,3MB file;
- wkhtmltopdf result looks mostly like the html original, phpwkhtmltopdf result uses different fonts and font sizes than the html original.

Any pointers to what might cause/ solve this would be greatly appreciated.

**Comment by mikehaertl** [comment]
Hmm, I have no idea. This wrapper is very lightweight, so it basically only calls `wkhtmltopdf` as you would on the command line. It only adds a [temporary file](https://github.com/mikehaertl/php-tmpfile) internally where the created PDF gets stored to. Maybe try to get the command string with `(string)$pdf->getCommand()` and check if it makes sense or is different to your CLI command.

**Comment by mikehaertl** [comment]
> wkhtmltopdf result looks mostly like the html original, phpwkhtmltopdf result uses different fonts and font sizes than the html original.

This sounds really weird. Could it be that you have 2 different versions of `wkhtmltopdf` installed on your system? And that PHP is using a different version that you have on your command line?

**Comment by erwinelling** [comment]
Thanks for thinking along. It's crazy right? Even when I set the path to the binary of wkthmltopdf explicity (/usr/bin/wkhtmltopdf) in phpwkthmltopdf and then use the exact command string $pdf->getCommand() outputs in the CLI, i get very different results.

**Comment by erwinelling** [comment]
I'm now pretty sure this has nothing to do with your wrapper, but with the server config. When I use exec to run the exact command I get the following error: "Fontconfig error: Cannot load default config file". Thanks again!
