### ISSUE TITLE
Different output local vs server

### ISSUE THREAD

**Issue by exhaler** [mikehaertl/phpwkhtmltopdf#299]
Hello,

I'm running into an issue where the local (windows) wkhtmltopdf is giving me a correct PDF layout while on the server (CentOS) I get a messed up layout. The configurations and the versions on both machines are the same 0.12.2.1 (with patched qt). I've attached a PDF sample from each source, the page being sent to the PDF is displaying correctly locally and online.

Does it matter if i have a 64-bit or 32-bit installed? on windows i have the 64 bit, however i'm unable to determine which is installed on CentOS

Thanks for the help
[local.pdf](https://github.com/mikehaertl/phpwkhtmltopdf/files/2644206/local.pdf)
[server.pdf](https://github.com/mikehaertl/phpwkhtmltopdf/files/2644207/server.pdf)

**Comment by mikehaertl** [comment]
You're reporting this to the wrong project. We only provide the PHP wrapper and are not related to the wkhtmltopdf project itself. You should report your problem there.
