### ISSUE TITLE
Load image on pdf file form using php-pdftk library

### ISSUE THREAD

**Issue by anjudhimna** [mikehaertl/phpwkhtmltopdf#300]
Hi,

I have a field on my pdf file form where I want to add the image from php script.
There is a form on my website and image browsed there need to be shown on pdf file form.

I have tried is bypassing full image URL, absolute image path as well. But it does not work.
I have tried by adding an image, button, text field on pdf form. But none of them work.
Can you please suggest me how can I load the image on pdf file using this library?

**Comment by mikehaertl** [comment]
You should try to make this work on the command line with raw `wkhtmltopdf` first. Our library can not help much in dealing with images. Thus I'm closing this. If you think there's a bug somewhere feel free to add another comment.
