### ISSUE TITLE
Setting options for phpwkhtmltoimage

### ISSUE THREAD

**Issue by RyanBlundell** [mikehaertl/phpwkhtmltopdf#301]
Thanks for sharing such a useful tool!

I am trying to reduce the filesize of output images but I am having problems setting options. The image is being saved but the image outputted is exactly the same as having no options set. I am guessing that I am doing something wrong here.

`$options = array(
   '--dpi 300',
   'no-outline',
   '--image-quality 10',);

$image = new Image('http://bl.ocks.org/mbostock/raw/7555321/', $options);
 $image->saveAs('output.png');
`

Cheers

**Comment by mikehaertl** [comment]
We don't do anything special with those arguments. Everything is passed down to `wkthtmltoimage`. So maybe first try on the command line to find the best options.

**Comment by RyanBlundell** [comment]
Ah yes, turns out we many of the functions are not available to wkhtmltoimage or have a different name (such as --quality)

I can get it to compress images via command prompt, however I am still struggling to get it to work via the phpwkhtmltoimage.

I have tried the following

use mikehaertl\wkhtmlto\Image;
$image = new Image('http://www.google.com');
$image->binary = '/path/bin/wkhtmltoimage';
$options = array(
'--quality 10');
$image->saveAs($output, 'output.png');


I also tried
$options = array(
'--quality 10','http://www.google.com','/pathtosaveimage/output.png');
$image = new Image($options); 
$image->binary = '/pathto/wkhtmltox/bin/wkhtmltoimage';

**Comment by RyanBlundell** [comment]
OK managed to figure it out ;)

Appreciate your help

$image = new Image('http://www.google.com');   // Set image options
$options = array('quality' => 20);
$image->setOptions($options);   // Set image options (alternative)

**Comment by mikehaertl** [comment]
If you want to set options, it's probably clearer to write it this way:

```
$image = new Image($options);
$image->addPage('http://...');
$image->saveAs(...);
```

**Comment by RyanBlundell** [comment]
Cheers

I actually tried that previously without results, I tried it again to double check

Strangely when I use $image->addPage(''); nothing happens and $image->getCommand()->getExecCommand() echos blank.

EG
```
$options = array('quality' => 20);
$image = new Image($options);
$image->binary = '/path/bin/wkhtmltoimage';
$image->addPage('http://bl.ocks.org/mbostock/raw/7555321/');
$image->saveAs('/path/public_html/output2.png');
echo $image->getCommand()->getExecCommand();

```

**Comment by mikehaertl** [comment]
Sorry, it should be `setPage()` instead of `addPage()`. The latter only works for pdf.

**Comment by RyanBlundell** [comment]
Bingo, works for me 🥇👍
