### ISSUE TITLE
Command failed error

### ISSUE THREAD

**Issue by Neobugu** [mikehaertl/phpwkhtmltopdf#302]
While trying to create a PDF, getting "Command failed" error:
any help would be apreciated

```
(
    [binary] => /home/u154548/public_html/../private_html/factura_tickets/wkhtmltox/bin/wkhtmltopdf
    [commandOptions] => Array
        (
            [useExec] => 1
        )

    [tmpDir] => 
    [ignoreWarnings] => 
    [version9] => 
    [_isCreated:protected] => 
    [_options:protected] => Array
        (
            [header-html] => mikehaertl\tmp\File Object
                (
                    [delete] => 1
                    [_fileName:protected] => /tmp/tmp_wkhtmlto_pdf_8fzH78.html
                )

            [footer-font-size] => 7
            [footer-left] => Este documento es una representaci�n de un CFDI versi�n 3.3
            [footer-right] => [page]
            [margin-top] => 33mm
            [page-size] => Letter
            [header-spacing] => 3
            [user-style-sheet] => /home/u154548/public_html/flp/php/lib/clases/../res/pdf/Body.css
        )

    [_objects:protected] => Array
        (
            [0] => Array
                (
                    [inputArg] => mikehaertl\tmp\File Object
                        (
                            [delete] => 1
                            [_fileName:protected] => /tmp/tmp_wkhtmlto_pdf_SsOVqx.html
                        )

                )

        )

    [_tmpPdfFile:protected] => mikehaertl\tmp\File Object
        (
            [delete] => 1
            [_fileName:protected] => /tmp/tmp_wkhtmlto_pdf_haEgKV.pdf
        )

    [_tmpFiles:protected] => Array
        (
            [0] => mikehaertl\tmp\File Object
                (
                    [delete] => 1
                    [_fileName:protected] => /tmp/tmp_wkhtmlto_pdf_SsOVqx.html
                )

        )

    [_command:protected] => mikehaertl\wkhtmlto\Command Object
        (
            [enableXvfb] => 
            [xvfbRunBinary] => xvfb-run
            [xvfbRunOptions] => -a --server-args="-screen 0, 1024x768x24"
            [escapeArgs] => 1
            [escapeCommand] => 
            [useExec] => 1
            [captureStdErr] => 1
            [procCwd] => 
            [procEnv] => 
            [procOptions] => 
            [locale] => 
            [_stdIn:protected] => 
            [_command:protected] => /home/u154548/public_html/../private_html/factura_tickets/wkhtmltox/bin/wkhtmltopdf
            [_args:protected] => Array
                (
                    [0] => --header-html '/tmp/tmp_wkhtmlto_pdf_8fzH78.html'
                    [1] => --footer-font-size '7'
                    [2] => --footer-left 'Este documento es una representacin de un CFDI versin 3.3'
                    [3] => --footer-right '[page]'
                    [4] => --margin-top '33mm'
                    [5] => --page-size 'Letter'
                    [6] => --header-spacing '3'
                    [7] => --user-style-sheet '/home/u154548/public_html/flp/php/lib/clases/../res/pdf/Body.css'
                    [8] => '/tmp/tmp_wkhtmlto_pdf_SsOVqx.html'
                    [9] => '/tmp/tmp_wkhtmlto_pdf_haEgKV.pdf'
                )

            [_execCommand:protected] => /home/u154548/public_html/../private_html/factura_tickets/wkhtmltox/bin/wkhtmltopdf --header-html '/tmp/tmp_wkhtmlto_pdf_8fzH78.html' --footer-font-size '7' --footer-left 'Este documento es una representacin de un CFDI versin 3.3' --footer-right '[page]' --margin-top '33mm' --page-size 'Letter' --header-spacing '3' --user-style-sheet '/home/u154548/public_html/flp/php/lib/clases/../res/pdf/Body.css' '/tmp/tmp_wkhtmlto_pdf_SsOVqx.html' '/tmp/tmp_wkhtmlto_pdf_haEgKV.pdf'
            [_stdOut:protected] => 
            [_stdErr:protected] => 
            [_exitCode:protected] => 139
            [_error:protected] => Command failed
            [_executed:protected] => 
        )

    [_error:protected] => Command failed
)
```

**Comment by crazymeeks** [comment]
Try this. Just make sure you install xvfb.
```
$pdf = new Pdf(array(
     'binary' => PDF_SYSTEM_PATH,
     'commandOptions' => array(
           'enableXvfb' => true,
     ),
));
```

**Comment by Neobugu** [comment]
Would be something like this?

      $pdf = new Pdf(array(
        'binary' => $_SERVER['DOCUMENT_ROOT'] . '/files/wkhtmltox/bin/wkhtmltopdf',
        'commandOptions' => array(
          'enableXvfb' => true,
        ),
        'header-html' => $headerHtml,
        'footer-font-size' => 7,
        'footer-left' => utf8_decode('Este documento es una representación de un CFDI versión 3.3'),
        'footer-right' => utf8_decode('[page]'),
        'margin-top' => "33mm",
        'page-size' => "Letter",
        'header-spacing' => 3,
        'user-style-sheet' => "{$rutaRecursos}/Body.css",
      ));

**Comment by crazymeeks** [comment]
Just wait a moment. let me check.

**Comment by crazymeeks** [comment]
Try this.
```
$pdf = new Pdf(array(
					'binary' => '/usr/bin/wkhtmltopdf',
					'commandOptions' => array(
						'enableXvfb' => true,
						'xvfbRunOptions' => ''
					),
				));
```

**Comment by mikehaertl** [comment]
@Neobugu I would not use xfvb unless you really need it. Also does the path to your binary file exist? Try `ls /home/u154548/public_html/../private_html/factura_tickets/wkhtmltox/bin/wkhtmltopdf` on the command line.

**Comment by Neobugu** [comment]
`ls: cannot access /home/u154548/public_html/../private_html/factura_tickets/wkhtmltox/bin/wkhtmltopdf: Permission denied`

but it exists, if it doesnt i wouldnt be able to throw command failed

**Comment by mikehaertl** [comment]
Well - no. The error you get usually indidcates that the command is either not found or has the wrong permission. So you need to fix this first. This is something I still need to improve in https://github.com/mikehaertl/php-shellcommand which is used to execute `wkhtmltopdf` in this library.

**Comment by Neobugu** [comment]
Uhmm, i tried moving folder to /home/u154548/public_html/files/wkhtmltox/bin/wkhtmltopdf but still get same error Permission denied

**Comment by mikehaertl** [comment]
I'm sorry, but I can't help you with your local setup. This library only works, if PHP can reach and execute the binary file. Try without this library using plain [exec()](http://php.net/manual/en/function.exec.php) in PHP or similar.

So far there's nothing to fix here. So I'm closing this for now. If you think, something is really broken, you can always send another comment with an example that demonstrates the issue.

**Comment by Neobugu** [comment]
I would like to add, binary is there and gets read & executable, if not it wouldnt reach the "command failed" string at function execute()

**Comment by mikehaertl** [comment]
Look closely. There's no check if the file exists. It just calls `exec()` which will have a non-zero return value if the command doesn't exist. Then it will throw the error above.

So far this is the only case I know of, that leads to this message. Otherwhise you'd see a different error message.

But whatever the reason: The execution of your `wkhtmltopdf` fails from PHP. I can't fix anything here.

**Comment by Neobugu** [comment]
Just to know, are there any php modules to make it work? Maybe I have something left to install

**Comment by Neobugu** [comment]
Ok just investigated deeper, there was missing libs at my server, wasnt at all phpwas libxrencer, libssl, libext and another for 32bits, and now it works

**Comment by mikehaertl** [comment]
No. Why don't you try what I suggested above? Use a simple PHP script, and use `exec('/your/path/to/wkhtmltopdf')` and see if that works.

**Comment by JTL1992** [comment]
@Neobugu but which libs you missed? i see the same error in my centos7 using wkhtmltopdf 0.12.5
