### ISSUE TITLE
Gateway Timeout when I want to send PDF on ovh server

### ISSUE THREAD

**Issue by JulienGuizot** [mikehaertl/phpwkhtmltopdf#305]
On the SSH console : 
I export PATH and LD_LIBRARY_PATH  :
```
$ export PATH=~/target/usr/local/bin:$PATH
$ export LD_LIBRARY_PATH=~/target/usr/local/lib:~/target/usr/lib:~/target/usr/lib/i386-linux-gnu
```

Then I execute :
```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.5 (with patched qt)
```
So `wkhtmltopdf` works fine on the server.

I use your mikehaertl/phpwkhtmltopdf repository to use wkhtmltopdf with php. 
In local, my code works fine but when I push it online, I have a `Gateway Timeout Error`...

The errors seems to be about `PATH` and `LD_LIBRARY_PATH`. I don't know how set well this variables in php..

The code which generate my pdf see below :

```
# Set PATH and LD_LIBRARY_PATH
# .... ????

# Get content of template
ob_start();
require $url_template;
$content = ob_get_clean();

# Initialize PDF options
$options = array("binary" => "../target/usr/local/bin/wkhtmltopdf");

# Create PDF
$pdf = new Pdf($options);
$pdf->addPage($content);

# Generate PDF
if (!$pdf->send()) {
    $error = $pdf->getError();
    var_dump($error);
}
``` 

I tried to modify `PATH` and `LD_LIBRARY_PATH` with `$_ENV`, `$_SERVER` and `putenv` function, but it don't work.

Does somebody know how to fix it ?

Thanks a lot ! and sorry for my english !

**Comment by mikehaertl** [comment]
Sorry, this has nothing to do with our library. Check the timeout settings in your server software. Google should help you find a solution.

**Comment by JulienGuizot** [comment]
Wkhtmltopdf works fine when i launch it in command line, on my ovh server `Debian GNU/Linux 8.11 (jessie)` : 
`$ wkhtmltopdf --version` 
and this :
`$ wkhtmltopdf toto.html toto.pdf`.

But when i use your library, the `$pdf->send()`method doesn't work. I have a `502 Gateway Timeout`.

It works fine on `localhost`

**Comment by mikehaertl** [comment]
Again: This is a setting in your webserver. This has nothing to do with the library. Your script is running too long, so that the webserver software closes the connection. We can't do anything about it in the library. You need to change this setting yourself.

**Comment by JulienGuizot** [comment]
I tried with this package : 
https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.jessie_i386.deb.

I don't know the settings to change for this issue.. I don't ask you that you change your library, i ask if you would be resolve my issue :) 

Thx

**Comment by mikehaertl** [comment]
This is not a support forum but for reporting bugs. Please check the usual sources: google, Stackoverflow, etc.
