### ISSUE TITLE
Footer with page number not showing in last page

### ISSUE THREAD

**Issue by federf** [mikehaertl/phpwkhtmltopdf#306]
I'm generating a pdf with page number on the footer of every page but the footer 
doesn't show in the last page.
It shows in every other page but the last one.
Any idea what can be causing this?
This are the settings I'm using to create the pdf.

```
$pdf = new Pdf([
    'page-size'        => 'Letter',
    'margin-top'       => 5,
    'margin-right'     => 0,
    'margin-bottom'    => 5,
    'margin-left'      => 0,
    'orientation'      => 'landscape',
    'footer-center'    => 'Page [page] of [toPage]',
    'footer-font-size' => 8,
	]
);
```

**Comment by mikehaertl** [comment]
I have no idea. This is probably rather a problem of `wkhtmltopdf` not our PHP wrapper here.
