### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by juliusgoh22** [mikehaertl/phpwkhtmltopdf#311]
Thanks mikehaertl for this wonderful and awesome tool.

I currently facing a problem that is my pdf file will have funny blank pages. Can you help me to resolve this ?
![Screenshot 2019-03-20 at 3 51 12 PM](https://user-images.githubusercontent.com/34125609/54667877-7bd76700-4b28-11e9-9e53-78f167c423b1.png)

**Comment by mikehaertl** [comment]
Sorry, I can't help. This is for reporting bugs. So unless something is broken and you can give a code example I'll close this.

Also note please, that question like these are better directed to wkhtmltopdf itself. We here only are a small PHP wrapper around it.

**Comment by juliusgoh22** [comment]
Oh okay thank you.
