### ISSUE TITLE
jQuery & script js

### ISSUE THREAD

**Issue by ArmandArthur** [mikehaertl/phpwkhtmltopdf#314]
Hello,

It's possible to load script with the command/options like this : 
`            $options = array(
                'no-outline',           
                'encoding' => 'UTF-8', 
                'run-script' => array(
                    __DIR__."/../../assets/js/jquery.js",
                    __DIR__."/../views/consultation/elements/consultation.js"
                )
            );`

Thanks your for your response.

**Comment by mikehaertl** [comment]
Ist this a question? Or what exactly is the problem?

**Comment by ArmandArthur** [comment]
Question, i need to know if i can execute JS script with jquery before to render the page?

**Comment by mikehaertl** [comment]
I have no idea, because this is just a wrapper for wkhtmltopdf. Your question is about wkhtmltopdf itself, you should ask there. Also note, that this is for reporting bugs and not for questions.
