### ISSUE TITLE
phpwkhtmltopdf behind proxy

### ISSUE THREAD

**Issue by Kru-x** [mikehaertl/phpwkhtmltopdf#315]
Hi,

Not sure if this is the right place to post this but I have successfully installed wkhtmltopdf and phpwkhtmltopdf on my development machine and it is working great using $pdf->send() as an output to the browser.

But when I use the same build on my production server the pdf won't be sent to the client, the only difference between the two systems is that my production server uses an nginx reverse proxy and I suspect that's where the problem is, 

Any ideas?

Kru-x

**Comment by mikehaertl** [comment]
If it's not even sent I have no idea except that I'd also look at the proxy to found out what it does. If it were "only" corrupted it could be because the proxy does some sort of compression (like `gzip on` in Nginx). There's no real fix except excluding `.pdf` from being compressed.

**Comment by Kru-x** [comment]
Hi Mike,
Figured out that it takes too long time to process and that's why NGINX times out, but don't know why as it is quick on my development server.  I upped the nginx timeout from 60 to 120 sec and the sent command worked and the pdf came through in about 65 sec.
It is definitely the NGINX server and I can close this "issue" will investigate further but maybe you can make more sense of the error log details.
`- upstream timed out (110: Operation timed out) while reading response header from upstream`

Guess it is just poorly formatted html from my side, 
Cheers
