### ISSUE TITLE
assign PDO result into rendered HTML

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#316]
**This is not a bug, but I do not know where I could ask.**
I use PDO and I would like to render the sql result as Table into the PDF.

firstly I create the table and store it into variable:

```
$prepared->execute();

		  $table =
			   $result = $prepared->fetchAll(PDO::FETCH_ASSOC);
			   echo "<table>";
			   foreach( $result as $row ) {
                 	      echo "<tr><td>" . $row['Letter'] . "</td><td>" . $row['Commission'] . "</td><td>" . row['DeliveryDate'] . </td>/tr>";
						      };
			   echo "</table>";
```
then I try pass the variable in HTML, which should be rendered:
```
$pdf->addPage('

		    <!DOCTYPE html>
		    <head>
		    <meta charset="UTF-8">
		    </head>
		    <body>
		    <div class="print-area">
		    '.$table .'
		    </div>
		    </body>
		    </html>

');
```
The PDF is rendered, but instead of the table is just shown 'Array'.
Could anybody point me how to render result from PDO as table?
Thank You

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but for reporting bugs. Your question is really about PHP basics and not related to this library at all. Please try PHP support forums or Stackoverflow instead.
