### ISSUE TITLE
break lines

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#318]
Hello,
In DB I have one column containing enter/break lines.
When I fill HTML form via PDO, so these "enters/break lines" are added.
When I add into rendered HTML same data, so these "enters/break lines" are not added.

Should I find something in PHP itself or is it something in wkhtmltopdf?
Thank YOu

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but for reporting bugs. Your question is about wkhtmltopdf itself, not our PHP class here. So you should look for support there.
