### ISSUE TITLE
sometimes no phpwkhtmltopdf pdf creation, although wkhtmltopdf pdf creation ok

### ISSUE THREAD

**Issue by ahjstone** [mikehaertl/phpwkhtmltopdf#32]
Hi,

Debian wheezy 7.3, localhost

1) WkHtmlToPdf (0.11.0 rc1) command

wkhtmltopdf --use-xserver --disable-javascript --no-background --no-images --grayscale --header-left "[webpage]" --footer-center "[page]/[topage]" --footer-right "[date]" http://github.com/mikehaertl/phpwkhtmltopdf README.pdf

generates the pdf

2) phpWkHtmlToPdf script (static version 1.2.1):

$pdf->addPage('http://google.com);
$pdf->send('README.pdf');

generates the pdf, however:

$pdf->addPage('http://github.com/mikehaertl/phpwkhtmltopdf');
$pdf->send('README.pdf');

does not generate the pdf

print_r($pdf) output:

WkHtmlToPdf Object ( [binPath:protected] => [binName:protected] => wkhtmltopdf [enableEscaping:protected] => 1 [version9:protected] => [options:protected] => Array ( [0] => grayscale [1] => no-images [2] => no-background [header-font-size] => 10 [header-left] => [webpage] [footer-center] => [page]/[topage] [footer-right] => [date] ) [pageOptions:protected] => Array ( ) [objects:protected] => Array ( [0] => Array ( [input] => http://github.com/mikehaertl/phpwkhtmltopdf ) ) [tmp:protected] => [tmpFile:protected] => [tmpFiles:protected] => Array ( ) [procEnv:protected] => [isWindows:protected] => [enableXvfb:protected] => [xvfbRunBin:protected] => [xvfbRunOptions:protected] => --server-args="-screen 0, 1024x768x24" [error:protected] => [localOptions:protected] => Array ( [0] => binName [1] => binPath [2] => tmp [3] => enableEscaping [4] => version9 [5] => procEnv [6] => enableXvfb [7] => xvfbRunBin [8] => xvfbRunOptions ) )

neither does
$pdf->addPage("\"http://github.com/mikehaertl/phpwkhtmltopdf\"");
$pdf->send('README.pdf');
generate the pdf

Cheers,
Alan

**Comment by harishannam** [comment]
I have been using it in 2 sub domains. I get this issue in one subdomain, but works very fine in other. Was there any solution for this ? @ahjstone / @mikehaertl

**Comment by ahjstone** [comment]
I stopped using phpwkhtmltopdf.
Using bash scripts now and is satisfactory... so far.
