### ISSUE TITLE
Pdf Network Error

### ISSUE THREAD

**Issue by tommhendrick** [mikehaertl/phpwkhtmltopdf#320]
When I try sending a PDF to a user with a filename it starts the download in the browser and then says Failed - Network error.

https://user-images.githubusercontent.com/484466/58211015-956b6b00-7c9f-11e9-9232-cf0a73c21b9a.png

However if I don't give it a filename then it loads in the browser fine. But when I click the download button in the browser pdf viewer it also fails. 

Any idea what is going on? I have the latest version of wkhtmltopdf and am using all the demo code.

**Comment by mikehaertl** [comment]
I'd try to download with a command line tool e.g. `wget` or `curl` and see what happens.

**Comment by tommhendrick** [comment]
when i dump the command from getExecCommand it returns this:

`wkhtmltopdf '/tmp/tmp_wkhtmlto_pdf_rbBbTD.html' '/tmp/tmp_wkhtmlto_pdf_kysBFC.pdf'`

and when I try running that on the server it returns this error. Seems like it's trying to grab it as a webpage?

```
Loading pages (1/6)
Error: Failed to load http://tmp/tmp_wkhtmlto_pdf_rbBbTD.html, with network status code 3 and http status code 0 - Host tmp not found
Error: Failed loading page http:///tmp/tmp_wkhtmlto_pdf_rbBbTD.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError
```

**Comment by mikehaertl** [comment]
Not sure, where you got this from but that's not supposed to work. I gave you some hints above. It's up to you if you want to try them.

I'm closing this for now as I can't see how our library could produce such a problem and I can't help debugging setup or network issues. If you think there's something to fix please provide a clear description what you think must be fixed.

**Comment by tommhendrick** [comment]
I'm not sure what you mean run wget or curl. Don't I need to run it on the tmp pdf file that is being created?

**Comment by mikehaertl** [comment]
Instead of opening the URL in your browser (where it fails) use wget or curl on the command line locally to download the file from the same URL and see if that works. Browser error messages are often not very helpful for debugging.
