### ISSUE TITLE
CSS - different behavior between versions

### ISSUE THREAD

**Issue by ZAJDAN** [mikehaertl/phpwkhtmltopdf#322]
Hello,
I am not sure where I should ask.
On one server I use:
**wkhtmltopdf 0.12.2.1 (with patched qt)
phpwkhtmltopdf 2.1.0**

On second one server I use:
**wkhtmltopdf 0.12.5 (with patched qt)
phpwkhtmltopdf 2.1.0**

each the server provide same web(clone) but CSS works not same...
on the server where is newer version of wkhtmltopdf 0.12.5 ...is layout shrinked

**Comment by mikehaertl** [comment]
This is an issue of wkhtmltopdf itself. You better report the issue there. This is only a wrapper for it in PHP. 

https://github.com/wkhtmltopdf/wkhtmltopdf
