### ISSUE TITLE
Error on centos7, trying to get http:// instead of /tmp

### ISSUE THREAD

**Issue by tsukasa1989** [mikehaertl/phpwkhtmltopdf#324]
I get the following error:

> [root@136-144-179-91 home]# wkhtmltopdf --no-outline --margin-top '0' --margin-right '0' --margin-bottom '0' --margin-left '0' '/tmp/tmp_wkhtmlto_pdf_Dn7rso.html' '/tmp/tmp_wkhtmlto_pdf_f9B726.pdf'
> Loading pages (1/6)
> Error: Failed to load http://tmp/tmp_wkhtmlto_pdf_Dn7rso.html, with network status code 3 and http status code 0 - Host tmp not found
> Error: Failed loading page http:///tmp/tmp_wkhtmlto_pdf_Dn7rso.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
> Exit with code 1 due to network error: HostNotFoundError
> 

I got an error when running and ran the command directly on the commandline.

It tries the /tmp/ file with http://. The /tmp/ should prefix the file with file://

**Comment by mikehaertl** [comment]
Hmm, are you sure, that PHP has write permissions for the `/tmp` directory? There are some extra restrictions on CentOS due to SELinux, see here: https://github.com/mikehaertl/phpwkhtmltopdf/issues/99#issuecomment-101675909

Prefixing everything with `file://` should not be necessary and is also not mentioned in the man page. It also works without for the majority of users.

**Comment by tsukasa1989** [comment]
Thank you for your prompt response.

It was indeed something with the /tmp directory.  I have SELinux configured correctly. The issue was the following. I changed the following files:

/usr/lib/systemd/system/httpd.service  
/usr/lib/systemd/system/php-fpm.service

And set PrivateTmp=false  

I did a touch("temp_xxxx") and did a `find / -name temp_xxx` which resulted in something like this: `/tmp/systemd-private-53d26428f7cb44bbaabf97a3d93d3a0b-php-fpm.service-69DybT/tmp/temp_xxx`

**Comment by mikehaertl** [comment]
So does it work now? I should probably add a note about SELinux to the README.

**Comment by tsukasa1989** [comment]
Yeah it is working after changing the service not to use it's own private tmp directory. Because the command uses the absolute path /tmp/filename, where php with file_put_contents puts the file in the service private directory, if privatetmp=true (default).
