### ISSUE TITLE
Not working for big files => fallback with passthru()

### ISSUE THREAD

**Issue by ThomasPerraudin** [mikehaertl/phpwkhtmltopdf#325]
The PDF generation fails without error message for big html files (and web server never send any response, web browser waiting indefinitely for a response).

I add to stop using this php wrapper and use passthru() to generate PDF contents.

My old code :
```
      $pdf->addPage($html);
      $content = $pdf->toString();
```

My new code :
```
      $tmpfname = tempnam(sys_get_temp_dir(), "tmp_pdf_");
      rename($tmpfname, $tmpfname .= '.html');
      $tmpfnameOut = tempnam(sys_get_temp_dir(), "tmp_pdf_");
      rename($tmpfnameOut, $tmpfnameOut .= '.pdf');
      $handle = fopen($tmpfname, "w");
      fwrite($handle, $html);
      fclose($handle);
      $cmd = "wkhtmltopdf $tmpfname $tmpfnameOut 2>&1"; // 2>&1 to output error messages
      ob_start();
      passthru($cmd, $retval);
      $result = ob_get_clean();
      if($retval){
        die("Error with command: $cmd<br />Error code '$retval'<br />". nl2br(htmlentities($result)));
      }
      unlink($tmpfname);
      $content = file_get_contents($tmpfnameOut);
      unlink($tmpfnameOut);
```

**Comment by mikehaertl** [comment]
I'm not sure if we can do anything about that. Catching issues with commands that never complete is not easy in PHP. Actually I wonder, why `passthru()` is any different to `proc_open()` or plain `exec()` when the command never completes. I couldn't find anything in the PHP manual. Can you point out, why this works better in your case?

**Comment by ThomasPerraudin** [comment]
I don’t know why I didn’t get errors from the wrapper and I didn’t look at how you implemented proc_open() or exec().
In any case it looks like the process died whitout returning any error or there may be an issue in the wrapper.

The main question is why the PDF is generated succesfuly with a passthru() command and not with the wrapper?

**Comment by mikehaertl** [comment]
I use my little [php-shellcommand](https://github.com/mikehaertl/php-shellcommand) library to execute `wkhtmltopdf`. It either uses `proc_open()` or `exec()`. The implementation is straightforward, as you can see here: https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L327

Maybe you can try these other two methods to manually execute your wkhtmltopdf command and see if it gives the same result? I'm still unsure though, if I should add `passthru()` as yet another execution method to the shellcommand library. The main goal there was to capture any stdout and stderr outputs. That's not possible with `passthru()` I think.

**Comment by mikehaertl** [comment]
@ThomasPerraudin Did you find out something here? If there's no news I will close this issue as most users don't seem to have a problem and I wouldn't even know what exactly to fix.

**Comment by mikehaertl** [comment]
@ThomasPerraudin If you're still around: I've meanwhile completely refactored the way we work with the I/O streams with `proc_open()`. If you have a chance to give it a try, this would be great.

You'd have to replace your copy of `vendor/mikehaertl/php-shellcommand` with the branch [20-add-stream_set_blocking-calls](https://github.com/mikehaertl/php-shellcommand/tree/20-add-stream_set_blocking-calls) from this PR: https://github.com/mikehaertl/php-shellcommand/pull/41.

I'm somewhat confident that the change should fix many hanging issues.

**Comment by mikehaertl** [comment]
I've now pushed the version constraints for php-shellcommand to 1.5.0 in release 2.4.1 which should hopefully also fix this issue.

As there was no further feedback I'm closing the issue for now. Still interested if things worked out well.
