### ISSUE TITLE
Permission denied using saveAs()

### ISSUE THREAD

**Issue by jaycee04** [mikehaertl/phpwkhtmltopdf#326]
![err](https://user-images.githubusercontent.com/13114082/62101991-dd26f800-b2c9-11e9-8ca6-f0717a3f47ca.JPG)
I have a problem and i am having really hard time to fix this.

Using ->send() command works perfectly but i wanted to put the file in the server,
so i used saveAs('/var/www/html/project/assets/pdf'). But i got a message with permission denied!

Project folder Owner: user,Group:apache
Project/pdf folder Owner: user,Group:apache

Please i am dying with this problem.

I installed my wkhtmltopdf in usr/lib/oracle folder. i dont know why it was installed there.
maybe because of $PATH variable was configured there.

**Comment by mikehaertl** [comment]
I'm sorry, but I can't help fix file permission related problems. I get reports like this almost every week and it *never* is caused by our library. Check with raw PHP if you can write to that dir and read from the temp directory, also check  SELinux.

**Comment by jaycee04** [comment]
@mikehaertl  Hi master, Yes i can write in /tmp folder also in my pdf folder using touch command in centos.  Do you have any solutions got from the others? if you are getting a tons of problems like this then there is something wrong with the library.. library should check folders read and write permissions or maybe some suggestions in errors so it is more explicit with the errors. Maybe there should like testFolderPath() function so we can make sure that everything will work if we ever set a path file parameter in saveAs(). Usually this problem occurs always in centos. I am sorry if im not very good in handling servers and cant figure it out. i am just a developer thats loves your library and works in my windows properly also in developer cloud using digital ocean as centos too and it is working fine but deploying in clients server got this error.

Thanks master!

**Comment by jaycee04** [comment]
also one more thing master, using toString() output. how can i use this function? it returns some strings also symbols.so how can i convert it back to pdf style? because if ever i can write that toString() to a pdf again, maybe i will rewrite my code so i wont use saveAs() as this took so long of my time and still cant fix
