### ISSUE TITLE
PDF not downloading sometimes (Network error)

### ISSUE THREAD

**Issue by asuri0n** [mikehaertl/phpwkhtmltopdf#328]
I'm using Symfony3.4

When i try to download a PDF generated with wkhtmltopdf, I have an error sometimes : 
`Unable to find template "" (looked into: /var/***/app/Resources/views, /var/***/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).`

It's working most of the time but some customers are complaining about this problem.

**Comment by mikehaertl** [comment]
Sorry, this has nothing to do with our library. You need to check your symfony related code.
