### ISSUE TITLE
Loading CSS or images with HTTPS

### ISSUE THREAD

**Issue by benjaminniess** [mikehaertl/phpwkhtmltopdf#330]
Hi,

I managed to export a HTML page to a pdf file, thank you for that :)

For some reason, if I load a css file under https, the css is not interpreted. I have the same issue with images. If I load the same assets with the classic http protocol, everything looks all right.

Do you have an idea of what could generate this behaviour? And how I could debug because I can't see any error.

Thank you.
Best,
Ben

**Comment by mikehaertl** [comment]
Sorry, this is a question about `wkhtmltopdf` itself. We only provide the PHP wrapper and have no influence on what wkhtmltopdf does when creating a PDF. You should better ask this kind of question on the [wkhtmltopdf project](https://github.com/wkhtmltopdf/wkhtmltopdf).

**Comment by benjaminniess** [comment]
Ok sorry.
