### ISSUE TITLE
html entities for UTF8 charcters in replace option 

### ISSUE THREAD

**Issue by ducciodiblasi** [mikehaertl/phpwkhtmltopdf#331]
Hi,
I've just resolved an issue with option `--replace` for your wrapper.
when i passed some special character (example `è`) to the `replace` parameter, i got it passed uncorrectly to the footer, so when I converted it to uppercase with css directive `text-transform: uppercase;`, the character disappeared.
Since `wkhtmltopdf` is just a browser under the hood, when you pass parameters in the `replace` parameter you have to convert special UTF8 characters to `html entities` if you want them to be passed correctly as POST when it makes `header` and `footer` calls.
I have derived your `pdf` class and overridden the following function:

```
public function setOptions($options = array()){
	if (isset($options['replace'])) {
		foreach ($options['replace'] as $key => $val) {
			$options['replace'][$key] = htmlentities($val);
		}
	}
	parent::setOptions($options);
}
```

hope this helps
regards

**Comment by mikehaertl** [comment]
I'm pretty sure, that with the right locale settings everything works.

Note to self: Add [pdfbox](https://pdfbox.apache.org/) to the test environment so we can extract texts from created PDF files and verify that UTF-8 works.

**Comment by mikehaertl** [comment]
Ok, I couldn't make it work either. But this seems to be a bug with wkthmltopdf itself: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2427

Here's a simple test:

```
wkhtmltopdf --header-left 'äö [x]' --replace 'x' 'üüü' index.html out.pdf
```

While the `äö` work fine, the `üüü` in the replace argument don't.
