### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by raykudo** [mikehaertl/phpwkhtmltopdf#333]
Hello there,

I don't have any problems to get screenshots except for specific websites. For instance, whenever I try to take screenshots for https://web.archive.org/, it always returns **libpng warning: iCCP: known incorrect sRGB profile** and the result comes as a blank picture. 

```
$ wkhtmltoimage --version
wkhtmltoimage 0.12.5 (with patched qt)

$ wkhtmltoimage --enable-javascript --width 1024  --height 1024 --custom-header Host 'web.archive.org' 'https://web.archive.org/' a.jpg
Loading page (1/2)
libpng warning: iCCP: known incorrect sRGB profile           ] 59%
Rendering (2/2)                                                    
Done
```

Did anybody manage to go through this error? Maybe this error has nothing to do with the outcome but the thing is screenshot turns to be a blank picture.

**Comment by mikehaertl** [comment]
Wrong repository. Please check https://github.com/wkhtmltopdf/wkhtmltopdf.
