### ISSUE TITLE
PDF Generation doesnt work

### ISSUE THREAD

**Issue by RobinTHOREL** [mikehaertl/phpwkhtmltopdf#334]
Hi all,

I am pretty new to this lib and I can't generate my PDF.

Is there a limit of DOM to the $html ? 

My $html is about ~700 lines and contain some tables and when I do 

```
$pdf = new Pdf;
$pdf->addPage($html);
```

My page is always loading (also with a set_time_limit) and when I stop serve I got the following message : 

```
Could not create PDF: Loading pages (1/6) [> ] 0% [======> ] 10% [===========> ] 19% [================> ] 27% [=================> ] 29% [=====================> ] 35% [======================> ] 38%
```

I've tried multiple page like documented in the README with 3 ->addPage() it's working fine but I am in troubles with my own html page.

Some guys solve this issue ? 

Thanks!

**Comment by mikehaertl** [comment]
Please first check if it works with `wkhtltopdf` with the same HTML on the command line. I assume that your html contains some CSS and Js assets which it will try to load. Otherwise it should not take that long. And are you maybe using this on Windows?

**Comment by RobinTHOREL** [comment]
Hi @mikehaertl thanks you for the reply.

My `wkhtmltopdf` command work well like when I want to dump google.com page. I don't know how to get the exact command who's generated from your lib. 

Yes, my HTML call external JS and I am on an Unix system.

Some documentation about JS including ?

**Comment by mikehaertl** [comment]
You should try the same HTML that you use to generate the PDF on the command line and see if that works. All we do is to call `wkthmltopdf` from PHP. If it hangs, then it's because of `wkhtmltopdf` hanging. In my experience the size of the HTML does not matter much here - but external scripts and CSS very much do.

**Comment by RobinTHOREL** [comment]
Ok @mikehaertl I'll try this.

What's the best practice so to import javascript ? Set it internal to my HTML ?
