### ISSUE TITLE
 Page break problem with table

### ISSUE THREAD

**Issue by alexandrebouttier** [mikehaertl/phpwkhtmltopdf#336]
Hello, I have a html template made with Bootstrap 4, which contains a long table with several pages, my problem is that I do not have a clean page break, it cuts my table

**Comment by mikehaertl** [comment]
Please report this to [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf). This here is only a PHP wrapper. We can't fix/add any features.
