### ISSUE TITLE
phpunit/phpunit needs to be a dev dependency

### ISSUE THREAD

**Issue by timwsuqld** [mikehaertl/phpwkhtmltopdf#337]
`phpunit/phpunit` should really be a dev dependency in `composer.json`. This way when trying to run the phpunit tests we can easily install the correct version.

For example, if you just try and use the latest phpunit you get the following error:
```
PHPUnit 8.5.1 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 13:
  - Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.

  Test results may not be as expected.
```

**Comment by mikehaertl** [comment]
@timwsuqld Hmm, I always was against adding this as composer will install `require-dev` packages by default and I hate bloated packages. But OK, that's more a composer issue. I'm not happy that you must remember to add the `--no-dev` if you need a lightweight installation (e.g. for docker images).

But I see your point and it seems other libraries are doing this as well. But then we also need to change the call to phpunit in our travis setup to `./vendor/bin/phpunit` to no longer use the globally installed phpunit, right? I wonder if we shouldn't also update the tests to use the latest phpunit version then. What do you think?

**Comment by timwsuqld** [comment]
@mikehaertl composer will only install the require-dev for the root package (https://getcomposer.org/doc/04-schema.md#require-dev) so it's only when someone working on your package does a `composer install` that they'll get the dev dependencies by default. Anyone who depends on `mikehaertl/phpwkhtmltopdf` will only get the `require` dependencies installed, not the `require-dev` dependencies.
This is the "best of both worlds", your default composer install is ready for development, while everyone who depends on the package just gets the runtime dependencies.

It looks like Travis is smart enough to detect the correct phpunit (https://docs.travis-ci.com/user/languages/php/#default-build-script). Looking at the build logs it appears to indeed be using phpunit 6 (https://travis-ci.org/mikehaertl/phpwkhtmltopdf/jobs/632115902#L630)

**Comment by mikehaertl** [comment]
Thanks for the insights. I really wonder now what made me struggle for so long with this `require-dev` confusion :smile: .

But now you got me started: I think we should also add a `autoload-dev` then and list the tests there. They'd need to be namespaced, though. As I understand it this would keep the tests out of the production package. At least that's what I've seen in other packages.

But maybe first resolve the phpunit issue here.

**Comment by timwsuqld** [comment]
There are plenty of people confused about `require-dev`. I second guessed myself the other day, and then spent a while rereading until I found what I was looking for, and realised it did work how I expected. I think the wording at https://getcomposer.org/doc/04-schema.md#require-dev could be better due to the "root package" part, which doesn't immediately make sense.

I've not used `autoload-dev`, so I might need to see what projects I should be using that on as well!

**Comment by mikehaertl** [comment]
> I've not used autoload-dev, so I might need to see what projects I should be using that on as well!

I just tried it and it really seems to work. The tests are excluded (used `--prefer-dist` with `:dev-master` constraint below as there's no new release yet):

```
$ composer require --prefer-dist mikehaertl/phpwkhtmltopdf:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing mikehaertl/php-shellcommand (1.6.1): Loading from cache
  - Installing mikehaertl/php-tmpfile (1.1.1): Loading from cache
  - Installing mikehaertl/phpwkhtmltopdf (dev-master fb2e18a): Downloading (100%)
Generating autoload files

$ ls -lah vendor/mikehaertl/phpwkhtmltopdf/
insgesamt 40K
drwxr-xr-x 3 mike mike 4,0K Jan  7 08:48 .
drwxr-xr-x 5 mike mike 4,0K Jan  7 08:48 ..
-rw-r--r-- 1 mike mike 2,8K Jan  7 08:38 CHANGELOG.md
-rw-r--r-- 1 mike mike  860 Jan  7 08:38 composer.json
-rw-r--r-- 1 mike mike 1,1K Jan  7 08:38 LICENSE
-rw-r--r-- 1 mike mike  13K Jan  7 08:38 README.md
drwxr-xr-x 2 mike mike 4,0K Jan  7 08:38 src
```
