### ISSUE TITLE
footer-html not rendered on production

### ISSUE THREAD

**Issue by francescoladdomada** [mikehaertl/phpwkhtmltopdf#344]
Hi, I'm having some issues with the general footer that I set through the footer-html option.
On my localhost is working fine but on our production server is not rendered at all.

What I have already tried and checked:
- insert the < ! DOCTYPE html >, < head > and < body > tags in the page html and in the footer html
- tried to change the page margins to 0 or 20, but the footer is not shown in any case
- tried to write the footer html as simplest as possible, also inline instead of loading it from the file
- the css file has no width: 100% and no height: 100% for body and html selectors
- no errors are shown, and also ignoreWarnings set to false doesn't help

That's the code, I don't know if it can help:
```

        $pdf_options = [
            'no-outline',         // Make Chrome not complain
            'margin-top' => 20,
            'margin-right' => 20,
            'margin-bottom' => 20,
            'margin-left' => 20,
            //'dpi' => 380,

            'footer-html' => '<!DOCTYPE html><head></head><body>Footer test</body></html>',
            // Default page options
            //'disable-smart-shrinking',

            'binary' => $this->config->item('wkhtmltopdf_path')
        ];

        $pdf = new Pdf($pdf_options);

        $pdf->addPage($pdf_data['html']);

        if ( ! $pdf->saveAs($pdf_data['filename_with_path'])) {
            die($pdf->getError());
        }
```

Any help? 
Thanks a lot in advance!

**Comment by mikehaertl** [comment]
Any error?

**Comment by mikehaertl** [comment]
Sorry, missed that you mentioned "no errors".

Hmm, I don't know then. Must be something with wkhtmltopdf itself. Maybe you have different version in production?

Actually there's not much we can do here. So I have to close this for now. If you feel something must be fixed, please provide a full example to reliably reproduce the issue.
