### ISSUE TITLE
Can't add low quality to options

### ISSUE THREAD

**Issue by JerryBels** [mikehaertl/phpwkhtmltopdf#348]
Hi, and thanks for the wrapper ! 

I'm having trouble generating a pdf with `--lowquality` option. Tried : 

```
$pdf = new Pdf(['--lowquality']);
$pdf->addPage($html);
```

Or : 

```
$pdf = new Pdf($html);
$pdf->setOptions(['--lowquality']);
```

It fails to generate the pdf in both cases. Did I miss something about how these options should be passed?

Thanks ahead.

**Comment by mikehaertl** [comment]
Try without `--`. Also in cases like this please always provide the full (minimal) code and what  error you get from `getError()`.

**Comment by JerryBels** [comment]
You're right, I simply needed to let out the `--`. The PDF is correctly generated now - but has no difference whatsoever in file size with or without the option. `getError()` is now empty.
