### ISSUE TITLE
Saved pdf's are generated with error

### ISSUE THREAD

**Issue by Dimrak** [mikehaertl/phpwkhtmltopdf#350]
Hi,

This is the current error received of the pdf's that are been saved.

![Screenshot from 2020-06-03 14-16-27](https://user-images.githubusercontent.com/29204770/83630673-e4cbc300-a5a4-11ea-891f-b61449bb6fc8.png)

Code used, first generating the pdf, with a content variable, below an excerpt of the file
![Screenshot from 2020-06-03 14-20-18](https://user-images.githubusercontent.com/29204770/83631058-8f43e600-a5a5-11ea-80a9-7168703411dd.png)

```
$pdf = new Pdf($content);
```

Then just saving the file, to the desired path;
../storage/app/tmp/1/282795/example-282795.pdf

```
if (!$pdf->saveAs($fullpath)) {
            $error = $pdf->getError();
        }
```
Any suggestions? Thanks

**Comment by mikehaertl** [comment]
The error sounds not related to our library at all. I think `$pdf->getError()` is never called. Make sure there's no syntax error somewhere in your code.

**Comment by Dimrak** [comment]
Hi,

As some of the html were created with comments, removing those made appear correctly the pdf.

```
// Remove unwanted HTML comments
function remove_html_comments($content = '') {
      return preg_replace('/<!--(.|\s)*?-->/', '', $content);
}
```
Thanks
