### ISSUE TITLE
[page] and [topage] are not replaced

### ISSUE THREAD

**Issue by jrausell** [mikehaertl/phpwkhtmltopdf#351]
Hello,
I'm using phpwkhtmltopdf with no problem to generate pdfs except that default variables as [title][page] or [topage] are not replaced.

 ```
require_once($_SERVER['DOCUMENT_ROOT'].'/classes/phpwkhtmltopdf-master/vendor/autoload.php');
use mikehaertl\wkhtmlto\Pdf;

$optionsPDF = array(
    'no-outline', 
    'encoding' => 'UTF-8',

    'page-size'        => 'A4',
    'orientation'      => 'Portrait',

    'header-html' => '<h1>[title]!</h1>',
    'footer-html'      => '<p>Page : [page] of [pageTo]</p>',
    'footer-font-size' => '10',

    'margin-top'    => $margintop,
    'margin-right'  => 7,
    'margin-bottom' => $marginbottom,
    'margin-left'   => 7,

    'replace' => array(
        'page' => $page++,
        '[page]' => $page++,
        '{page}' => $page++,
        'title' => $pageTitle,
    ),
      
   'commandOptions' => array(
        'useExec' => false
    ),

    'disable-smart-shrinking',
    'user-style-sheet' => '/css/styles.css',
);


$pdf = new Pdf($optionsPDF);



$pdf->addPage('<!DOCTYPE html>
<html>
<head>
</head>
<body>

    <div id="print-area">
        <div id="header">
            This is an example header.
        </div>
        <div id="content">
            <h1>Demo</h1>
            <p>This is example content</p>
        </div>
        <div id="footer">
            This is an example footer.
        </div>
    </div>

</body>
</html>');

```

Any idea?
Thanks

**Comment by mikehaertl** [comment]
Please understand that this is not a support forum but an issue tracker to report bugs. So I have to close this.

Your question is also more about wkhtmltopdf itself and not specific to our library. I never used the replace feature myself. From looking at our tests we use `{xyz}` as placeholder. But I think that's wrong and it should be `[xyz]` instead (it's not relevant for the test anyway).  But more important: `page` and others are *predefined* and you should *not* use them with `replace`.

I'm also not sure if the replacement works with HTML header/footer. There's an example using javascript in the man page. But for more information you should consult the man page of `wkhtmltopdf` or ask their support for help.

**Comment by melino** [comment]
Confirmed: If the header or footer is html, you must use the javascript solution which is documented very well on wkhtmltopdf.org.
