### ISSUE TITLE
wkhtmltopdf 0.12.6 pdf failure

### ISSUE THREAD

**Issue by TWithers** [mikehaertl/phpwkhtmltopdf#352]
I just upgraded from 0.12.5 to 0.12.6 on Windows and started getting the "Failed without error" message:
    
    Failed without error message: wkhtmltopdf "--encoding" "UTF-8" "C:\Users\timot\AppData\Local\Temp\tmp9A1.tmp.html" "C:\Users\timot\AppData\Local\Temp\tmp9B2.tmp

When I downgraded back to 0.12.5, no more errors and PDF generates flawlessly. Code is very simple:

    $pdf = new Pdf([
            'encoding'=>'UTF-8',
        ]);
    $pdf->addPage($html);
    if($output = $pdf->toString() === false){
        throw new ServiceUnavailableHttpException($pdf->getError());
    }

**Comment by mikehaertl** [comment]
I can't help you much here. An empty error message usually only happens if the command can't be found. So maybe the path to the executable is not in the PATH variable or there's a permission issue. You will have to debug this yourself a little. Maybe use a simple PHP script and try to call `exec('wkhtmltopdf')` there. Check for both versions.

**Comment by acha5066** [comment]
I'm also having problems since the binary was updated to 0.12.6 on our server. I'm not on windows, however, but I assume some flavour of Linux (PlatformSH). This is the error message: 

```
Error generating document: Failed to generate PDF: /app/.global/gems/wkhtmltopdf-binary-0.12.6/bin/wkhtmltopdf:28:in `': undefined method `match?' for /deepin/:Regexp (NoMethodError) Did you mean? match from /app/.global/bin/wkhtmltopdf:22:in `load' from /app/.global/bin/wkhtmltopdf:22:in `'
```

**Comment by mikehaertl** [comment]
@acha5066 That error message sounds unrelated to our library. The path with `.../gems/...` looks like your installed some ruby library instead of the `wkhtmltopdf` binary. I can not help you with that.

**Comment by acha5066** [comment]
Hey @mikehaertl apologies for not providing enough context with my comment. It is indeed a ruby gem but the gem installs the relevant wkhtmltopdf binary on the server. That's just how it needs to be installed on PlatformSH. 

Reverting back to 0.12.5.4 got things working again. Some more background, we are using the Drupal entity_print module which has a dependency on this library.

**Comment by eversionsystems** [comment]
I just tried this library for the first time.  Couldn't get the install wkhtmltox-0.12.6-1.msvc2015-win64.exe to work but I tried @acha5066 suggestion and installed wkhtmltox-0.12.5-1.msvc2015-win64.exe which ended up working for me.

The error returned is "Failed without error" which is very generic and not helpful at all.

Let me know what you come up with.

**Comment by mikehaertl** [comment]
> It is indeed a ruby gem ...

If you read the error message it contains a lot of information that looks like a ruby issue. I really can not help you here:

> undefined method `match?' for /deepin/:Regexp (NoMethodError) Did you mean? match from /app/.global/bin/wkhtmltopdf:22:in `load' from /app/.global/bin/wkhtmltopdf:22:in `'

@eversionsystems  Please read my comment above: Can you execute wkhtmltopf from a simple PHP script with `exec()`? I can not help you if it is not executable from PHP.  I don't use Windows and can only provide limited support here. If things don't work consider using Linux e.g. in a VM or a docker container. It would save you much trouble on the long run.

**Comment by eversionsystems** [comment]
Works fine from the command line with 0.12.5-1.  I couldn't get 0.12.6-1. to work.  Using the older version for now..

**Comment by mikehaertl** [comment]
Ok, if the binary is not executable from PHP I can't fix anything here. It's probably related to the peculiarities of Windows + PHP and that's beound the scope of this library.

**Comment by matthewknill** [comment]
I'm having the same issue on Ubuntu 20.04. I believe it may be due to the following which was added in 0.12.6-1:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4536
