### ISSUE TITLE
proc_open() has been disabled for security reasons

### ISSUE THREAD

**Issue by gustavocass** [mikehaertl/phpwkhtmltopdf#354]
Hi guys, I'm having a problem when generating PDF on production with laravel.
For some reason it returns with error proc_open() has been disabled for security reasons
I search all over google but couldn't find any solution. Could you guys help me out?

**Comment by mikehaertl** [comment]
This is not something we can fix here. If `proc_open()` is disabled, ask your system administrator, why that is or figure out how to enable it.

Alternatively try the `useExec` option as described here: https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options
