### ISSUE TITLE
hanging up with Loading pages (1/6) [========================================>                   ] 67%

### ISSUE THREAD

**Issue by hlf2016** [mikehaertl/phpwkhtmltopdf#357]
When I run

```
wkhtmltopdf https://www.washingtonpost.com/sports/olympics/list-24-of-sports-events-affected-by-coronavirus-pandemic/2020/07/27/09b677e2-d04c-11ea-826b-cc394d824e35_story.html page.pdf
```

will hanging up with

```
Loading pages (1/6)
[========================================>                   ] 67%
```

and  could never comleted

![image](https://user-images.githubusercontent.com/24551738/88622794-22952580-d0d6-11ea-86b4-9dce687841f1.png)

**Comment by mikehaertl** [comment]
Can you give some more details? Do you have the latest version? How did you configure the class and what is your OS?

**Comment by mikehaertl** [comment]
Wait a second: So you have this issue on the command line? Then it's not related to this class here. This is a PHP library to execute `wkthmltopdf`. You should report issues to their repository instead.

**Comment by hlf2016** [comment]
> Wait a second: So you have this issue on the command line? Then it's not related to this class here. This is a PHP library to execute `wkthmltopdf`. You should report issues to their repository instead.

Thanks sir ! It's the problem of  wkthmltopdf, I'm sorry for bother you
