### ISSUE TITLE
Is post parameter still working?

### ISSUE THREAD

**Issue by rxng** [mikehaertl/phpwkhtmltopdf#360]
I have been trying to use phpwkhtmltopdf with post params

'post email' => 'value'

But  I am getting hit with the error

Unknown long argument --post email 

Is post no longer supported?

**Comment by mikehaertl** [comment]
You have to check the help for your `wkhtmltopdf` version on the command line. This library does not know what options are supported, it only passes them on to the command line tool. Apart from that `post email` looks not like a valid option as they never contain a space character.
