### ISSUE TITLE
I don't found the class File

### ISSUE THREAD

**Issue by jhody** [mikehaertl/phpwkhtmltopdf#363]
hello, i need help you. I have the next issue:
**use mikehaertl\tmp\File;**  
The class file not found, can I help me please?

**Comment by mikehaertl** [comment]
This is probably issue with composer and autoloading. You somehow must have messed up your vendor directory or something. I can not help you with that. Maybe delete `vendor/` completely and reinstall all packages.

I'm closing this as this is not a bug in our library but rather a usage problem with composer.
