### ISSUE TITLE
PDF not rendering <img> tag.

### ISSUE THREAD

**Issue by Wiebbelling** [mikehaertl/phpwkhtmltopdf#364]
Hi all, first time user of the library,

I'm able to generate a HTML file with the correct content of the PDF I want to generate.

Running $pdf-> send($filename) ou $pdf->saveAs($filename) results in the same thing, the PDF is generated, but with no image.

Here is my code:

```php
...

file_put_contents(__DIR__ . '/test.html', $documentTemplate);

$html_file_url = __DIR__ . '/test.html'; // html file

use mikehaertl\wkhtmlto\Pdf;

$pdf = new Pdf(array(
    'binary' => '/usr/local/bin/wkhtmltopdf',
    'ignoreWarnings' => true,
    'commandOptions' => array(
        'useExec' => true,      // Can help on Windows systems
        'procEnv' => array(
            // Check the output of 'locale -a' on your system to find supported languages
            'LANG' => 'en_US.utf-8',
        ),
    ),
));

$pdf->addPage($html_file_url);

if (!$pdf->send($filename)) {
    $error = $pdf->getError();
    echo $error;
}
```
 
On the zip file there is the test.html that is the html generated and the PDF generated from the HTML.

[teste_files.zip](https://github.com/mikehaertl/phpwkhtmltopdf/files/5562485/teste_files.zip)

**Comment by mikehaertl** [comment]
This library is only a wrapper around the `wkhtmltopdf` command line tool. Your issue is nothing we can fix here. You can try to report the problem over at their repository. To verify try to create the PDF with `wkhtmltopdf` on the command line and see if it works there. If it does it must be related to the image paths that can't be found when rendering with our library.

**Comment by Wiebbelling** [comment]
Thanks for the return, I found an old thread on their repo about it that seams to solve my problem. 

Will link it below and close the thread here.

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4408
