### ISSUE TITLE
PDF doesn't show images

### ISSUE THREAD

**Issue by Samfromuwamai** [mikehaertl/phpwkhtmltopdf#365]
hi,
I'm using phpwkhtmltopdf since 3 years. It works fine. but since a few days, it doesn't put images (charts generated from Highcharts) in my PDF. I didm't change anythings in my code. Have you an idea ?

**Comment by mikehaertl** [comment]
This is a question for wkhtmltopdf itself, not our library. We provide only a thin wrapper around it for PHP.
