### ISSUE TITLE
Allow to send custom HTTP headers

### ISSUE THREAD

**Issue by mikehaertl** [mikehaertl/phpwkhtmltopdf#366]
See https://github.com/mikehaertl/php-tmpfile/issues/26.

We can add another arg `$headers` to the `send()` method in the `Pdf` and `Image` class, too.

**Comment by PedroPMS** [comment]
Great, I will do some tests like this I did in php-tmpfile.

**Comment by PedroPMS** [comment]
It worked really well too.

Pdf
![image](https://user-images.githubusercontent.com/48099126/109545924-42dff500-7aa8-11eb-9c5c-2b586b21b20a.png)
![image](https://user-images.githubusercontent.com/48099126/109545941-48d5d600-7aa8-11eb-8ca9-8b0af061bc7f.png)

Image
![image](https://user-images.githubusercontent.com/48099126/109546095-7e7abf00-7aa8-11eb-841c-9020a83f058c.png)
![image](https://user-images.githubusercontent.com/48099126/109546116-85093680-7aa8-11eb-9781-9a17df814959.png)

**Comment by mikehaertl** [comment]
Cool. I've just released 2.5.0 including this change. Thanks for the suggestion and your help!

**Comment by PedroPMS** [comment]
It was a pleasure to help. Thank you for your support!
