### ISSUE TITLE
Google Chart bars half the correct height

### ISSUE THREAD

**Issue by Ananicz** [mikehaertl/phpwkhtmltopdf#370]
I am attempting to convert a Google Charts bar chart to a PDF executing:

``wkhtmltopdf --javascript-delay 2000 --print-media-type chart_dummy.html chart_dummy.pdf``

However, the bars are half the height they should be in the PDF; also, the key at the bottom of the page is not rendered. 

I am using 0.12.5 (with patched qt).

I have attached a zipped copy of chart_dummy.html.

Can someone please enlighten me.

[chart_dummy.html.zip](https://github.com/mikehaertl/phpwkhtmltopdf/files/6166041/chart_dummy.html.zip)

**Comment by mikehaertl** [comment]
You are reporting to phpwkhtmltopdf. You should open an issue at https://github.com/wkhtmltopdf/wkhtmltopdf

**Comment by Ananicz** [comment]
Thanks Mike. I shall do.
