### ISSUE TITLE
Option Footer, Header not working

### ISSUE THREAD

**Issue by nop44** [mikehaertl/phpwkhtmltopdf#373]
Plop,
When i execute a web page with phpwkhtmltopdf component - Footer Page option not working. But if i take command that execute (after get command via dump($command->getExecCommand() ) that good - ie the Footer can see.
I try many action but always the same.
if nobody find solve .....
Thank,

dump($command->getExecCommand()) = wkhtmltopdf '--dpi' '300' '--footer-center' 'Footer Page comment' '/var/www/public/uploads/emargement_2021-04-18T140838.pdf607c3d662469c.html' '/tmp/tmp_wkhtmlto_pdf_Mqe3ud.pdf

**Comment by mikehaertl** [comment]
I don't really have an idea. The string you get from `getExecCommand()` is exactly the executed command. Could you play around without our library and just use `exec()` in a simple PHP script to see if you can make it work?

**Comment by nop44** [comment]
Oh nice man ..... thanks for your fast answer.... i'll test with exec() .... in simple php script.... 
I'd test yet with process lib and it's same.... 
I'll come back when i test your suggestion...
++

**Comment by mikehaertl** [comment]
@nop44 Any news here?

**Comment by nop44** [comment]
Hy man,
Sorry for my late answer.... it'snt nice .... :/....
With your suggestion it'snt work ..
After many test i take this composer package : h4cc/wkhtmltopdf-amd64": "^0.12.4" ... and it's good ....
Again i'm sorry Thanks you ....

**Comment by mikehaertl** [comment]
Ok, I will then close this issue as there's nothing to fix here.

**Comment by nop44** [comment]
Thanks for your work .... nice lib....
