### ISSUE TITLE
How to pass arguments to header-html via PHP 

### ISSUE THREAD

**Issue by saptha** [mikehaertl/phpwkhtmltopdf#374]
Hi Mike,
In the command line I'm able to pass arguments to header-html like below:

> wkhtmltopdf --margin-top 17.5mm --margin-bottom 17.5mm --header-html file:///Users/Desktop/header.html?author=Saptha --footer-html file:///Users/Desktop/footer.html --enable-local-file-access --user-style-sheet file:///Users/Desktop/style.css --disable-smart-shrinking /Users/Desktop/book.html /Users/Desktop/out.pdf

I tried like below from the PHP but it doesn't work. 

>  $pdf = new Pdf(array(
>             'no-outline',         // Make Chrome not complain
>             'margin-top'    => 17.5,
>             'margin-right'  => 14,
>             'margin-bottom' => 17.5,
>             'margin-left'   => 15,
>             // Default page options
>             'header-html' => $tmpDir."/header.html?author=Saptha",
>             'footer-html' => $tmpDir.'/pdf-footer.html',
>             'disable-smart-shrinking',
>             'enable-local-file-access',
>             'user-style-sheet' => $tmpDir.'/style.css',
>             'allow' => $tmpDir.'/images'
>         ));

I think its not taking the ? symbol. Can you please suggest.

**Comment by mikehaertl** [comment]
What you have should work. Did you make sure, that the file exists and is readable? Maybe check with `is_readable($tmpDir."/header.html?author=Saptha")`. The path should also be a normal file path without `file://`.

**Comment by saptha** [comment]
Yes, the file exists and is readable. But the below command still fails:

```
$tmpDir = '/Users/Desktop';
        if(!is_readable($tmpDir."/header.html?author=Saptha")) {
            $errorMessages = 'Cannot read header-html file at '.$tmpDir.'\n';
        }

Output: Cannot read header-html file at /Users/Desktop
```

**Comment by mikehaertl** [comment]
Well, the error tells it all: It can not read the file from PHP. That's not an issue of our library but with permissions on your system. PHP must be able to read the header files so you need to check your file permissions.
