### ISSUE TITLE
Docker containered wkhtmltopdf

### ISSUE THREAD

**Issue by samex** [mikehaertl/phpwkhtmltopdf#377]
Hi, just tried to change binary to a custom alias which I bound on my linux machine, but get blank pdf files. When I do this with existing binary its works fine.

alias wkhtmltopdfdocker='docker run -it wkhtmltopdf'

running then "wkhtmltopdfdocker" in terminal print out the helpinfo. With stdout I can generate then pdf files, in example:

wkhtmltopdfdocker -q https://www.google.de - | cat > test.pdf

I think the way your php wrapper is using wkhtmltopdf is not working with docker containers, any hint for a workarround?

**Comment by mikehaertl** [comment]
Are you sure that your alias is available from PHP?  Try `system('wkhtmltopdfdocker')` (without our library) and see if this produces any output.

**Comment by samex** [comment]
You're absolutly right, that issue is related to my environment thanks ;)
