### ISSUE TITLE
Blocked access to file

### ISSUE THREAD

**Issue by strtob** [mikehaertl/phpwkhtmltopdf#379]
Hi,

I'm new with wkhtmltopdf. 

Unfortunately, I'm suffering from this error:

`Loading pages (1/6) [> ] 0% [======> ] 10% Warning: Blocked access to file Warning: Blocked access to file Warning:`

I've tried to set the option "enable-local-file-access"  => true but phpwkhtmltopdf tell me, that this option not exist.

A helping idea, I would appreciate!

Thanks a lot...
Toby

**Comment by mikehaertl** [comment]
You must pass the options in a wrong way. The library does not restrict any options and `enable-local-file-access` works fine for me. You should not use `true` as value, though, but simply pass it like this:

```php
<?php
$pdf = new Pdf([
    'enable-local-file-access',
    // ...
]);
```
