### ISSUE TITLE
string(184) "Failed without error message: wkhtmltoimage "test123.html" "\AppData\Local\Temp\tmpB072.tmp.png" (Exit code: 1)"

### ISSUE THREAD

**Issue by Usama4745** [mikehaertl/phpwkhtmltopdf#380]
getting this issue while creating image. I am on windows string(184) "Failed without error message: wkhtmltoimage "test123.html" "\AppData\Local\Temp\tmpB072.tmp.png" (Exit code: 1)"

**Comment by mikehaertl** [comment]
I can not help you without any (short) code example. Your problem sounds like you forgot to configure the path to `wkhtmltopdf.exe`. See the second paragraph in the README:

> For Windows systems make sure to set the path to wkhtmltopdf.exe in the binary option. Alternatively you can add the wkhtmltopdf "bin" directory to the system PATH variable to allow wkhtmltopdf command available to Windows CMD.

**Comment by Usama4745** [comment]
do we also need to add this .exe file in linux server?

**Comment by mikehaertl** [comment]
You need to install `wkhtmltopdf`. But all  this is mentioned in the README. Please understand that this is not a support forum but for reporting bugs.
