### ISSUE TITLE
Png not generating from html when html have link tag in them

### ISSUE THREAD

**Issue by Usama4745** [mikehaertl/phpwkhtmltopdf#381]
Hey I am trying to create png of html which have link tags in it but the issue is png is not getting generated when it has link tag in it. When we remove link tag only then png got generated

**Comment by mikehaertl** [comment]
This is very likely an issue with `wkhtmltoimage` itself. We can not fix these kind of issues here, as this library is only a wrapper for PHP. You could open an issue at their project.

If you still think this is a problem with our library, then again: Please provide a minimal (!) code example to reproduce the issue.
