### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by Flobbos** [mikehaertl/phpwkhtmltopdf#384]
Hello,

I am facing a rather peculiar problem when generating PDFs. 

Cannot modify header information - headers already sent by (output started at /home/kyocerashop/live/releases/20220408104827/vendor/mikehaertl/php-tmpfile/src/File.php:129)

It seems like something is going wrong as soon as the PDF is being sent but I can't track down the problem. Do you have any idea what is causing this issue? 

Thanks.

**Comment by mikehaertl** [comment]
Sorry, this has nothing to do with our library. You probably have already sent some output somewhere in your app *before* you send the PDF. Could also be a trailing empty line or space after a `?>` somewhere in your project files.

If you still think it's a problem with our lib, please provide a *small* example script to help reproduce the problem.

**Comment by Flobbos** [comment]
Thank you for your reply. 

The issue is completely random which means that it will work flawlessly most of the time but sometimes I get this error message. I have tried to track down this issue for a while now but since it's completely random it's kinda tough. 

Also the error states that the output started from within your library and not some place else as mentioned in this issue #135 

`public function generateWebsitePdf($id)
    {
        $group = $this->groups->loadMaterials($id);

        $this->pdf->setOptions($this->options);

        $this->pdf->addPage(view('export.website')->with([
            'is_group' => true,
            'group' => $group,
        ])->render());

        $filename = strtoupper(preg_replace('/[^a-zA-Z0-9-+]/i', '', $group->name)) . '.pdf';

        if (!$this->pdf->send()) {
            throw new Exception('Could not create PDF: ' . $this->pdf->getError());
        }

        $content = $this->pdf->toString();
        if ($content === false) {
            throw new Exception('Could not create PDF: ' . $this->pdf->getError());
        }

        return $this->pdf->send();
    }`

None of the exceptions above the actual send() are being triggered here, otherwise I wouldn't even get to the point where the PDF is being sent.

**Comment by mikehaertl** [comment]
It's probably because your framework tries to send a header *after* `generateWebsite()` is called. You probably have to prevent this somehow.

But again: Nothing that requires a fix here.

**Comment by mikehaertl** [comment]
I also see that you call `send()` two times in your code. That's not how this library is meant to be used. Please refer to the README for valid examples.
