### ISSUE TITLE
Running the code example in instruction

### ISSUE THREAD

**Issue by parkho** [mikehaertl/phpwkhtmltopdf#387]
HI,
I'm new to this library so I installed on my website and created a page and copied the code to create a simple PDF from a url and save it on the server but when I run the page it gives me a blank page and no file is saved. Any suggestions?

```
<?php
require('wkhtmltopdf/vendor/autoload.php');
use mikehaertl\wkhtmlto\Pdf;
// You can pass a filename, a HTML string, an URL or an options array to the constructor
$pdf = new Pdf('https://www.bnfgallery.ir/mobl/listresid.php');

// On some systems you may have to set the path to the wkhtmltopdf executable
// $pdf->binary = 'C:\...';

if (!$pdf->saveAs('https://www.bnfgallery.ir/mobl/1.pdf')) {
    $error = $pdf->getError();
    // ... handle error here
}
```

**Comment by mikehaertl** [comment]
1. Is `wkhtmltopdf` installed and executable?
2. Can you execute it from PHP e.g. with a simple `system('wkhtmltopdf')`?
3. Have you checked your server logs? Is there any error?
4. Have you tried with a simpler example i.e. not using an external URL but some static HTML content?

**Comment by mikehaertl** [comment]
5. And most obvious: Is there something in `$error`?

**Comment by parkho** [comment]
I just uploaded the download to my server and used the codes, also tried the internal link like "residkala.php", didn't make any difference

**Comment by parkho** [comment]
> 5. And most obvious: Is there something in `$error`?

the page is blank and shows nothing!

**Comment by parkho** [comment]
> 5. And most obvious: Is there something in `$error`?

Could not run command wkhtmltopdf 'listresid.php' '/tmp/tmp_wkhtmlto_pdf_jne4BY.pdf'

**Comment by mikehaertl** [comment]
I'm sorry, but I can not really help you any further. It could be a certain server configuration or something similar. There are too many possible reasons but this is out of the scope of our library. It works fine with an unrestricted server. You need to do your own research on this.

Also again try with a string, not a URL (also not another PHP page) as I suggestd in step 4 above.

**Comment by parkho** [comment]
Have you looked at the error message above I sent you?

**Comment by parkho** [comment]
Hello again,
First off, I would like to thank you for your great work, it is much appreciated. Secondly, I changed the temp folder permission to 777 and stil get the same error. I was wondering if there would be a way to change the tmp directory to some newly created folder. Regards

**Comment by mikehaertl** [comment]
https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options
