### ISSUE TITLE
Remove TOC

### ISSUE THREAD

**Issue by SyahrirMbojo** [mikehaertl/phpwkhtmltopdf#389]
How to remove toc? and when I don't add $pdf->addToc(); then my data is empty. Why is that?

`$options = array(
            'page-size' => 'A4',
            'orientation' => 'landscape',
            'ignoreWarnings' => true,
            'disable-smart-shrinking',
            'margin-top'    => 10,
            'margin-right'  => 0,
            'margin-bottom' => 10,
            'margin-left'   => 0,
        );

        $pdf = new Pdf($options);
        $pdf->addPage($htmlView);
        $pdf->addToc();
        if (!$pdf->send($filename . '.pdf')) {
            $error = $pdf->getError();
            var_dump($error);
        }`

**Comment by mikehaertl** [comment]
Probably your `$htmlView` is empty or does not contain proper HTML or similar.

Please understand that this is not a support forum and your issue is not caused by a bug in the library.

**Comment by SyahrirMbojo** [comment]
I have an html view and also a list of data but I didn't include it in the question.
this is the full code

`$filename = 'List-Device - ' . time();
        $data = [
            'title_report' => $filename,
            'messageExport' => $subtitle,
            'listdevices' => $listDevices
        ];
        $htmlView = view('devices/pdfreport_devices', $data);

        $pdf = new Pdf($this->utils->wkhtmltopdfOptions());
        $pdf->addPage($htmlView);
        $pdf->addToc();
        if (!$pdf->send($filename . '.pdf')) {
            $error = $pdf->getError();
            var_dump($error);
        }`

**Comment by mikehaertl** [comment]
Like I said: I can not help you debug your code. Our library works. Maybe first try with some simple static HTML string in `addPage()`. If this doesn't work, try if `wkthmltopdf` really works correctly on the command line (without this library).
