### ISSUE TITLE
sh: wkhtmltopdf: command not found. Options 'binary' => '/usr/local/bin/wkhtmltopdf' Doesn't help

### ISSUE THREAD

**Issue by j238267431** [mikehaertl/phpwkhtmltopdf#392]
Hi Mike

I installed phpwkhtmltopdf using composer 'composer require mikehaertl/phpwkhtmltopdf'
But error occure while executing sh: wkhtmltopdf: command not found
I saw the issue concerned and add the options 
$options = array(
	'binary' => '/usr/local/bin/wkhtmltopdf'
);
$pdf->setOptions($options);
but the answer is sh: /usr/local/bin/wkhtmltopdf: No such file or directory
CentOS 8 
I tried to find wkhtmltopdf 'which wkhtmltopdf' but the answer is **/usr/bin/which: no wkhtmltopdf in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)**
So I stuck here
Kindly help to solve this issue

**Comment by mikehaertl** [comment]
I'm sorry, I can not help you with that. You have to find out how to install wkthmltopdf on your system and to find the location where it's installed. That's beound the scope of this library.
