### ISSUE TITLE
cannot open pdf file converted from html

### ISSUE THREAD

**Issue by j238267431** [mikehaertl/phpwkhtmltopdf#393]
Hello Mike,

I managed to get the pdf file from html but I can not open it. Error message is: The document “report (20).pdf” could not be opened. 
Some online sites like this https://www.ilovepdf.com/repair-pdf can repair so after that it could be opened
But I need to get pdf file which is ready to be opened without any manipulations
Kindly advise what could be the reason and is it possible to fix it somehow

**Comment by mikehaertl** [comment]
I'm sorry, I can not help you with this issue as it's related to `wkthmltopdf` itself, not our wrapper library here. We have not influence on the content of the PDF file. If the file is created but has issues when you open it that's a problem of `wkthtmltopdf` itself. You can try to recreate the problem on the command line and then report it as issue on their project site.
