### ISSUE TITLE
how can I use Arial or Arial Black

### ISSUE THREAD

**Issue by aboshhab12** [mikehaertl/phpwkhtmltopdf#394]
![1515gfd1g5df1g6df51gdf65g1](https://user-images.githubusercontent.com/112715149/207686209-72c81fda-627d-4249-b06f-32fd58979d57.PNG)
![1das5d1as51d5w](https://user-images.githubusercontent.com/112715149/207686332-630babc7-a073-4794-9300-b094a6100e49.PNG)

i use Arial Font in style but when I generate pdf file use this font family (DejaVuSansMono)

**Comment by mikehaertl** [comment]
Sorry, I can not provide help with support questions like this. Your question also rather is about wkhtmltopdf itself, not our library (which is only a PHP wrapper around wkhtmltopdf).
