### ISSUE TITLE
Not printing Properly

### ISSUE THREAD

**Issue by cpgb85** [mikehaertl/phpwkhtmltopdf#396]
Printing appears proper on the preview, everything is contained with the page on a landscape 8.5x11 paper.  But when actually printing, the left, right and bottom of the page content gets cut off, it's printing off of the page.  Has anyone encountered this issue with this library?

`$pdf = new Pdf([
    'page-size'=>'A4',
    'margin-top'    => 0,
    'margin-right'  => 0,
    'margin-bottom' => 0,
    'margin-left'   => 0,
    'no-outline', 
    'orientation'=>'landscape',
    // 'disable-smart-shrinking',
    'commandOptions' => array(
        'procEnv' => [
            'LANG' => 'en_US.utf-8',
        ],
    ),
]);`

**Comment by mikehaertl** [comment]
Please understand that this is not a support forum.

This is also not an issue with this library but rather a question about proper styling with wkhtmltopdf (independent of phpwkhtmltopdf). So maybe try Stackoverflow or Reddit or similar sites.
