### ISSUE TITLE
Glyph width inconsistent in the PDF font dictionaries

### ISSUE THREAD

**Issue by LoickMEYER** [mikehaertl/phpwkhtmltopdf#398]
Hello
I create my invoices width wkhtmltopdf with PHP library, my final goal is to create a factur-X with those PDFs. But when I try to audit my PDFs, I have this error :

Spec. ISO_19005_3 clause 6.2.11.5 For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent. Level: CosDocument

```
Context:
root/document[0]/pages[0](3 0 obj PDPage)/contentStream[0](4 0 obj PDContentStream)/operators[9]/xObject[0](5 0 obj PDXForm)/contentStream[0](5 0 obj PDContentStream)/operators[2027]/usedGlyphs[0](TimesNewRomanNormal 32 0 0)
root/document[0]/pages[0](3 0 obj PDPage)/contentStream[0](4 0 obj PDContentStream)/operators[9]/xObject[0](5 0 obj PDXForm)/contentStream[0](5 0 obj PDContentStream)/operators[2001]/usedGlyphs[0](TimesNewRomanNormal 15 0 0)
root/document[0]/pages[0](3 0 obj PDPage)/contentStream[0](4 0 obj PDContentStream)/operators[9]/xObject[0](5 0 obj PDXForm)/contentStream[0](5 0 obj PDContentStream)/operators[2017]/usedGlyphs[0](TimesNewRomanNormal 8 0 0)
root/document[0]/pages[0](3 0 obj PDPage)/contentStream[0](4 0 obj PDContentStream)/operators[9]/xObject[0](5 0 obj PDXForm)/contentStream[0](5 0 obj PDContentStream)/operators[1507]/usedGlyphs[0](TimesNewRomanNormal 59 0 0)
root/document[0]/pages[0](3 0 obj PDPage)/contentStream[0](4 0 obj PDContentStream)/operators[9]/xObject[0](5 0 obj PDXForm)/contentStream[0](5 0 obj PDContentStream)/operators[1172]/usedGlyphs[0](TimesNewRomanNormal 22 0 0)
```

Thank you for your Help

**Comment by mikehaertl** [comment]
This is nothing we can fix here as it rather seems to be an issue with `wkhtmltopdf` itself. Our class is only a wrapper. I suggest you try to recreate the issue on the command line and then try to report an issue at the wkhtmltopdf project.

**Comment by mikehaertl** [comment]
Then you're probably out of luck. Not sure, why you vote me down: We **can not fix this here** and I'm not responsible for wkhtmltopdf.
