### ISSUE TITLE
headerHTML

### ISSUE THREAD

**Issue by frwg** [mikehaertl/phpwkhtmltopdf#399]
it is very inconvenient that headerHTML must be provided as a URL, not as a simple HTML String. Great, if you could change that.

**Comment by mikehaertl** [comment]
That's already possible. You just need to pass a HTML string that starts with `<html>`, otherwhise it can not be detected. See this regex:

https://github.com/mikehaertl/phpwkhtmltopdf/blob/3f9c96656259712324eda99978ccd90c79227203/src/Pdf.php#L20-L21

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback. If you think there's still something to fix or improve feel free to add  another comment. But please provide a full (minimal) code example to reproduce the problem.
