### ISSUE TITLE
Error QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-www-data

### ISSUE THREAD

**Issue by Gabriel-Hen** [mikehaertl/phpwkhtmltopdf#401]
When I try to save or send or convert to string a pdf with multiples addPage(html), return this error. But if i try with only one addPage(html) the pdf is saved

**Comment by mikehaertl** [comment]
This error is not thrown by our library but rather by wkhtmltopdf itself. I found this:
* https://stackoverflow.com/questions/71588830/wkhtmltopdf-qstandardpaths-xdg-runtime-dir-not-set-defaulting-to-tmp-runtime
* https://stackoverflow.com/questions/71571296/can-i-silence-qstandardpaths-xdg-runtime-dir-not-set-defaulting-to-tmp-runti

I don't think there's much we can do about it here.

**Comment by mikehaertl** [comment]
You could also try to set that var to a writeable directory:

```php
<?php
$pdf = new Pdf(array(
    'commandOptions' => array(
        'procEnv' => array(
            // provide a path to a writeable dir here
            // sys_get_temp_dir() should usually work:
            'XDG_RUNTIME_DIR' => sys_get_temp_dir(),
        ),
    ),
));

**Comment by Gabriel-Hen** [comment]
Now the error changed for: "QStandardPaths: runtime directory '/tmp' is not owned by UID 33, but a directory permissions 0777 owned by UID 0 GID 0Error: This version of wkhtmltopdf is built against an unpatched version of QT, and does not support more than one input document.Exit with code 1, due to unknown error."

**Comment by Gabriel-Hen** [comment]
I re-installed wkhtmltopdf by following this and it worked: 
![image](https://github.com/mikehaertl/phpwkhtmltopdf/assets/67988799/1e5ef3b6-e661-4676-9eeb-1a86bb26b619)

Link: https://stackoverflow.com/questions/34479040/how-to-install-wkhtmltopdf-with-patched-qt

Thank's
