### ISSUE TITLE
External webpage issue

### ISSUE THREAD

**Issue by psmith104** [mikehaertl/phpwkhtmltopdf#52]
When I try to build a pdf from an external url I get this error.

PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not create PDF: Could not run command "wkhtmltopdf" --no-outline --margin-top "0" --margin-right "0" --margin-bottom "0" --margin-left "0" "http://google.com" --disable-smart-shrinking "C:\Windows\Temp\tmp58E1.tmp"

However when I run this command myself it works perfectly so I don't think it is a wkhtmltopdf issue. The error is thrown from line 334 which makes me think proc_close is passing an error along. The pdf file is also not created.

**Comment by mikehaertl** [comment]
Closing this as it's related to an older release. Maybe it's also the same issue as in #99.
