### ISSUE TITLE
Warning: proc_open(): CreateProcess failed, error code - 2

### ISSUE THREAD

**Issue by Bilna75** [mikehaertl/phpwkhtmltopdf#56]
Hi,
I'm currently trying to use your wkhtmltopdf but I cannot get passed a Warning call saying :

Warning: proc_open() [<a href='function.proc-open'>function.proc-open</a>]: CreateProcess failed, error code - 87 in Path/To/WkHtmlToPdf.php on line 325

I tried with a basic code given in the tutorial but it doesn't work.

$pdf = new WkHtmlToPdf;
$pdf->addPage('http://google.com');
$pdf->send();
 
The error code 87 stands for invalid parameter.
Anyone can help me ?

Thank you

**Comment by tivie** [comment]
@mikehaertl I've created a command exec library that address inconsistencies between linux and windows environments. You might wanna consider using it to build your lib commands. 

https://github.com/tivie/command

If you wish, I can help you implement this.

**Comment by mikehaertl** [comment]
@tivie That looks nice. Maybe something to consider for a 3.0 release. On the other hand, from looking at the code I couldn't actually find a big difference in the core part (`proc_open()`). If you have some hints how to improve my php-shellcommand, I'm happy to include those changes. Your class makes sense for more advanced scenarios (method chaining, etc.). But our use case here is pretty simple. And I still believe in my own php-shellcommand implemenation ;).

BTW you may also hit this problem: https://github.com/mikehaertl/php-shellcommand/issues/6. Maybe worth adding to your class, too?

**Comment by tivie** [comment]
@mikehaertl thanks. 

The only big difference is in the automatic selection of `proc_open` or `exec` based on OS (in windows it uses `exec`, otherwise uses `proc_open`.)

> If you have some hints how to improve my php-shellcommand, I'm happy to include those changes

Maybe add this:
 - Automatic fallback to `exec` in windows environments
 - A way to change the produced command before executing it

Those two would be awesome.

> BTW you may also hit this problem: mikehaertl/php-shellcommand#6. Maybe worth adding to your class, too?
Yeah, that's worth adding as an opt-in option when dealing with long outputs. Thanks for the suggestion. =)

**Comment by doshu** [comment]
use the bypass_shell options of proc_open to make it works on windows
