### ISSUE TITLE
rename(,.pdf): No such file or directory

### ISSUE THREAD

**Issue by ViktorShinova** [mikehaertl/phpwkhtmltopdf#63]
Hi there,

I set this up in Laravel 4 through composer:
    "require": {
        "laravel/framework": "4.0.*",
        "mikehaertl/phpwkhtmltopdf": "dev-master",
        "h4cc/wkhtmltopdf-i386": "dev-master"
    },

did composer update..

code it in my Controller:
public function getDownload() {
    $pdf =  new Pdf('http://google.com');
    die(var_dump($pdf->saveAs(public_path().'/uploads/testtest.pdf')));
}

and I got this error:
rename(,.pdf): No such file or directory.

![screen shot 2014-08-04 at 1 56 11 pm](https://cloud.githubusercontent.com/assets/1889730/3793080/64155130-1b8b-11e4-8527-79e27f19ef5a.png)

Any idea where I could have done wrong?

I'm running on Mac OSX, php 5.4.19, XAMPP.

Thanks!

**Comment by melino** [comment]
Hi Mike,

I have exactly the same error message like Viktor, but on OS X and couldn't fix it with Viktor's solution. wkhtmltopdf works within the terminal.
Can you name me a way how to check if the path is correct? Maybe some error_log()?

Thanks!

**Comment by melino** [comment]
Alright, fixed this. In my case it was a permission issue with the tmp folder.
I have changed the folder with `$pdf->tmpDir = '/tmp/';` and now it works.
