### ISSUE TITLE
PDF generation process fail

### ISSUE THREAD

**Issue by yekver** [mikehaertl/phpwkhtmltopdf#7]
I have html date (table with 32 cols and 135 rows in it) on 6 pages of A4 page.

80% of my attempts trying to generate pdf file from this html - fails with an error:
Fatal error: Uncaught exception 'Exception' with message 'Could not create PDF: Could not run command '/var/www/site/bin/wkhtmltopdf-amd64' --footer-center '[page]/[topage]' --dpi '250' --orientation 'landscape' --user-style-sheet '/var/www/site/htdocs/css/pdf.css' --footer-font-size '9' --outline-depth '0' /tmp/tmp_WkHtmlToPdf_qX3Waz.html /tmp/tmp_WkHtmlToPdf_gi862w: ' in /var/www/site/includes/functions/system.php:122 Stack trace: #0 /var/www/site/htdocs/index.php(201): topdf('??? ?

I've commented ```__destructor()``` to keep tmp files alive and try to reproduce this error via console, but in console everything works perfect (I'm executing the same command, that shows in error)

With other html data your script works fine for me!

How to find where the problem is?

**Comment by mikehaertl** [comment]
Closing this issue, as it  referred to an old release of this class. I also couldn't really reproduce it, so unless there's new information, there's not much I can do here.

If the issue really persists, please drop a note here and I will consider reopening it.

**Comment by tivie** [comment]
@mikehaertl The cyrilic bug was fixed a while ago in wkHtmlToPdf binary, so this problem should be fixed. =)
