### ISSUE TITLE
Requested package is  mikehaertl/phpwkhtmltopdf 1.0.0 could be found

### ISSUE THREAD

**Issue by sathishbabu007** [mikehaertl/phpwkhtmltopdf#70]
When I am trying to install via composer, I am getting following error.

Requested package mikehaertl/phpwkhtmltopdf 1.0.0 could be found error.

I cannot able install this package

Please let me know for the same.

Thanks

**Comment by bbdhaval** [comment]
I am also facing same issue while running following command

composer require mikehaertl/phpwkhtmltopdf

It will shows following error

The requested package mikehaertl/phpwkhtmltopdf No version set (parsed as 1.0.0) is satisfiable by mikehaertl/phpwkhtmltopdf[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
