### ISSUE TITLE
how it work

### ISSUE THREAD

**Issue by youssefsimon** [mikehaertl/phpwkhtmltopdf#71]
i know php good but i dont know how should i use this he always tell me there a file or he cant found class not there should i use framework or somthing

**Comment by se8820726** [comment]
hi @mikehaertl 
I installed mikehaertl/phpwkhtmltopdf by composer on my centos server.
and add autoload.php file to my code.
but give me thie error yet:

Fatal error: Class 'mikehaertl\wkhtmlto\Pdf' not found in /directoryOfFile/_a.php on line 10

this is list tree of files after install by composer:
vendor
├── autoload.php <-- I added this file to my code: require_once 'vendor/autoload.php';
├── composer
│   ├── autoload_classmap.php
│   ├── autoload_namespaces.php
│   ├── autoload_psr4.php
│   ├── autoload_real.php
│   ├── ClassLoader.php
│   ├── installed.json
│   └── LICENSE
└── mikehaertl
    ├── php-shellcommand
    │   ├── CHANGELOG.md
    │   ├── composer.json
    │   ├── LICENSE
    │   ├── phpunit.xml.dist
    │   ├── README.md
    │   ├── src
    │   │   └── Command.php
    │   └── tests
    │       └── CommandTest.php
    └── php-tmpfile
        ├── composer.json
        ├── LICENSE
        ├── phpunit.xml.dist
        ├── README.md
        ├── src
        │   └── File.php
        └── tests
            ├── FileTest.php
            └── test.txt

now how I must solve the problem ?

**Comment by mikehaertl** [comment]
@se8820726 This is a composer problem and not related to my library. Obviously something went wrong, when you installed it, because the `vendor/mikehaertl` directory is empty.

**Comment by tejastank** [comment]
Shift to other lib, https://github.com/KnpLabs/snappy

As @mikehaertl weak with documentation

**Comment by tejastank** [comment]
@se8820726 You correct, big issues, even @mikehaertl your code base don't have all listed items

Well document it, where I should follow and all must exact work, their should be best example needed how to use after install.

As install working fine.

**Comment by mikehaertl** [comment]
Not sure what more you would expect. It's all there in the README: Installation with composer, quickstart example, details on configuration.

If that's already to complicated for you and you found something easier - well, great. Maybe this library here really is not for you then.

**Comment by tejastank** [comment]
Hi @se8820726

In case use ubuntu,

//create director
mkdir  /var/www/html/snippetbucket/

// than run composer 
composer require mikehaertl/phpwkhtmltopdf

# once it run gives output something like & also create vendor folder inside /var/www/html/snippetbucket/
----------------------------------------------------------
Using version ^2.2 for mikehaertl/phpwkhtmltopdf
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
  - Installing mikehaertl/php-shellcommand (1.2.5)
    Downloading: 100%         

  - Installing mikehaertl/php-tmpfile (1.1.0)
    Downloading: 100%         

  - Installing mikehaertl/phpwkhtmltopdf (2.2.1)
    Downloading: 100%         

Writing lock file
Generating autoload files


-------------------------------------------------------------------
Their is vendor folder in case correct installed, after that inside vendor folder their autoload.php 
Once you checked all above details than test below code.

<?php
error_reporting(1);  // AVOID THIS CODE INCASE YOU DONT WANT
ini_set('display_errors', 1);
error_reporting(E_ALL);

require_once 'vendor/autoload.php'; // NEED TO INCLUDE THIS 

use mikehaertl\wkhtmlto\Image; 

// You can pass a filename, a HTML string, an URL or an options array to the constructor
$image = new Image('http://tejaskumartank.com/');

$image->saveAs('website2png.png');

// ... or send to client for inline display
//$image->send();

// ... or send to client as file download
#$image->send('page.png');

?>
// YOU MIGHT SAVE THIS AS testtejas.PHP
// THAN RUN IT like via command line.

php7.0 -f testtejas.php
// AFTER THIS, YOU WILL FIND IN YOUR FOLDER NEW IMAGE CREATED SUCCESSFUL

**Comment by mikehaertl** [comment]
Not sure what you try to tell me. But please use snappy if you find that easier.

**Comment by tejastank** [comment]
@mikehaertl  I success to run your lib with php7.0 -f testtejas.php as command line.
but it does not work with apache2 and php7.0, it run not throw any error on page or in apache2-error log file too. But nothing output.

# code sample
<?php 
require_once 'vendor/autoload.php';
use mikehaertl\wkhtmlto\Image;

// You can pass a filename, a HTML string, an URL or an options array to the constructor
$image = new Image('https://www.xxxxxxxreplaceyourURL.com/bedroom/arms-reach-clear-vue-co-sleeper-review/');


// ... or send to client as file download
$image->send('page.png');

?>
