### ISSUE TITLE
Warning: proc_open(): CreateProcess failed, error code - 2

### ISSUE THREAD

**Issue by stoopkid1** [mikehaertl/phpwkhtmltopdf#8]
First, thanks for taking to time to write this PHP wrapper class.

I'm in a bit of a bind and don't have a clue on how to fix this issue. My server is running Windows Server 2008 R2, PHP 5 and Tomcat Apache.

The error cites line 300 in the WkHtmlToPdf.php file: 
$process = proc_open($command, $descriptors, $pipes, null, null,barray('bypass_shell'=>true));

I'm not quite sure what this error means, and after googling it there were no viable answers. I think this is more a Windows error than PHP error, but no idea how to resolve it. Any help is greatly appreciated.

Michael

**Comment by zealfire** [comment]
Hi,
    I am facing the same error even after when I have configured the bin option.Is there a way to solve this issue.Thanks.

**Comment by mikehaertl** [comment]
Try to use `exec()` instead of `proc_open()`. You can set the `useExec` option:

```
$pdf = new Pdf(array(
    'commandOptions' => array(
        'useExec' => true,
    ),
));
```

**Comment by zealfire** [comment]
Hi,
   Thanks for the reply.Sorry for not properly elaborating my problem but now I have updated my problem.Actually I am still using version 1.2.6 on windows and facing this problem.

**Comment by mikehaertl** [comment]
I think I can't help you with 1.2.6 version. Why don't you upgrade to the latest release?

**Comment by zealfire** [comment]
Yeah I understand but the problem is that I had used the old release of wrapper in a module which I had developed some time back but now I need to upgrade module but still don't want to upgrade wrapper because it worked perfectly earlier.
Btw: In old release at present $pdf->saveAs("xyz.pdf"); is working perfectly but $pdf->send(); is causing a problem.Can you please atleast give me hint?
Thanks

**Comment by mikehaertl** [comment]
I have no idea, sorry, so you have to find out for yourself. But please keep me updated, if you find something to fix.

**Comment by zealfire** [comment]
Hi,
   I decided to move to newer release but I am facing this error:

Fatal error: Uncaught exception 'Exception' with message 'Could not create PDF: 'wkhtmltopdf' is not recognized as an internal or external command, operable program or batch file.' in C:\xampp\htdocs\project\testpdf.php:27 Stack trace: #0 {main} thrown in C:\xampp\htdocs\project\testpdf.php on line 27

when I am using this code:


use mikehaertl\wkhtmlto\Pdf;
$pdf = new Pdf;
$pdf->addPage('<html>....</html>');
$pdf->saveAs('google.pdf');
if (!$pdf->send()) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
}

Thanks

**Comment by mikehaertl** [comment]
`wkhtmltopdf` is not in your search PATH. You should configure the full path to the binary in the `binary` configuration option. See https://github.com/mikehaertl/phpwkhtmltopdf#special-global-options.

**Comment by zealfire** [comment]
Hi, thanks for your previous reply.Sorry for constantly asking questions now the $pdf->saveAs() is working but if I try to do $pdf->send("save.pdf") the pdf is downloaded but when I try to open it says:
"failed to load pdf document ". Same thing is happening if try to load pdf as inline.
I tried to debug and I am facing this warning:

<em class="placeholder">Warning</em>: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\project\core\vendor\mikehaertl\php-tmpfile\src\File.php:77) in <em class="placeholder">mikehaertl\tmp\File-&gt;send()</em> (line <em class="placeholder">69</em> of <em class="placeholder">C:\xampp\htdocs\project\core\vendor\mikehaertl\php-tmpfile\src\File.php</em>)

Line 77 says this: readfile($this->_fileName);
Thanks.

**Comment by mikehaertl** [comment]
@zealfire Discussed here: #74. One note: Please keep the issues free of discussion and focussed on one problem only.

**Comment by Capoeirista** [comment]
I have such a problem was because .xml configuration file had specified an incorrect path to the Far

**Comment by immikhan6** [comment]
I am getting this error while creating arc diff  EXCEPTION: (Exception) Failed to passthru proc_open(): proc_open(): CreateProcess failed, error
 code - 5 at [<phutil>\src\future\exec\PhutilExecPassthru.php:103].
Can any one please help
