### ISSUE TITLE
Using stdin for pdf generation

### ISSUE THREAD

**Issue by kitensei** [mikehaertl/phpwkhtmltopdf#82]
Hey,
I would like to know if it's possible with the current version of the lib, to use stdin instead of temporary files for pdf generation like told here: http://stackoverflow.com/questions/21864382/any-wkhtmltopdf-option-to-convert-html-text-rather-than-file

I have a batch generation to do (> 1000pdf) and after profiling with xhprof, I found out that the open/write/close tmp file process is waaaaaaaaaaaaaay too long.

Apparently with the proc_open you can input in a shell command from php  (http://stackoverflow.com/questions/5443250/writing-to-stdin-from-php) and since your command line tool use proc_open/ close, I was curious to know if it's actually possible to do that or if it can be implemented

**Comment by kitensei** [comment]
Sorry for late answer,
I am trying to do a batch processing of pdf (1000+ pdfs) and I am trying to tune up the speed

**Comment by mikehaertl** [comment]
I understand that - but why do you want to do this from PHP? I think a simple shell script would be much easier for this task.

**Comment by kitensei** [comment]
I am working on a php web app that have to export invoices for many
customers.
The invoices are generated on january and the work is done once for all
yearly subscriptions, and then regularly when a normal invoice is generated.
The yearly subscriptions are 1000+ and are growing each year.

For now I have done a simple php generation, but I'll try to write a shell
script doing the pdf generation and invoke it from php to see if I notice a
speed boost.

2015-01-05 13:45 GMT+01:00 Michael Härtl <notifications@github.com>:

> I understand that - but why do you want to do this from PHP? I think a
> simple shell script would be much easier for this task.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikehaertl/phpwkhtmltopdf/issues/82#issuecomment-68703237>
> .
>



-- 

*K*.

**Comment by mikehaertl** [comment]
Ok. This is a very specific problem which I think it out of the scope of this project. So I'll close this issue for now. If you think, there's an easy way to integrate stdin support feel free to reopen - but I can't really think of any.
