### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by codesmith55** [mikehaertl/phpwkhtmltopdf#86]
I use your simple page example and get no response. When i run the wkhtmltopdf command at command line it works fine, but i don't get any output using your plugin.

**Comment by mikehaertl** [comment]
Which code did you use? Did you check `$pdf->getError()`? Did you check you server logs?

**Comment by codesmith55** [comment]
Thank you, checking pdf->geterror lead me to how wkhtmltopdf wasn't properly installed on the virtual machine. Then with (again thank you!!) your article https://delboy1978uk.wordpress.com/2014/11/24/html-to-pdf-using-wkhtmltopdf/ it got me most of the way there. 

The error code still reads "Failed without error message: xvfb-run --server-args="-screen 0, 1024x768x24" wkhtmltopdf 'temp.html' '/tmp/tmp_wkhtmlto_pdf_XZMA8o.pdf'". 

But through the article and some xvfb supplemented installation help that wasn't covered by the article, shell_exec wkhtmltopdf is working, which will carry me through until DOMPDF is updated for laravel5.
