### ISSUE TITLE
Unable to use phpwkhtmltopdf Debian 7

### ISSUE THREAD

**Issue by sevenup30** [mikehaertl/phpwkhtmltopdf#88]
Hi, 
i'm trying to use your classes, but i'm unable to :/

I installed with "php composer.phar require mikehaertl/phpwkhtmltopdf"

But in my project when i just put "use mikehaertl\wkhtmlto\Pdf;"

i have this error : 

Fatal error: Class 'mikehaertl\wkhtmlto\Pdf' not found in /home/seven/webserver/devis/lettre_devis.php on line 21

I so tried to copy the vendor folder to my project, same issue,

i then tried to include the Pdf.php file but then i got this : 

Fatal error: Class 'mikehaertl\wkhtmlto\Command' not found in /home/seven/webserver/devis/mikehaertl/wkhtmlto/Pdf.php on line 205

I tried to include command.php into Pdf.php but it result in blank page, i'm pretty sure it's something so easy that i can't see it, but well i can't see it -_-.

Could you help me?

Thanks,
Regards,
Martial.

**Comment by mikehaertl** [comment]
This sounds like you did not include the composer autoloader.

https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by sevenup30** [comment]
Yeah thanks, that was it.

But now it do not save my pdf :/

$pdf = new Pdf('http://localhost/devis/testpdf.html');
$pdf->saveAs('./public/uploads/new.pdf'); (i also tried /tmp/ - /home/user/ ../../public/uploads/)

**Comment by mikehaertl** [comment]
You should really check the README, which will answer your questions. About your error, check the error message you get from `getError()`.

**Comment by asmabelhadj123** [comment]
I'm on a managed cloud server from infomaniak, I installed wkhtmltopdf (supported by infomaniak)

but during the execution of the code always I have this error message: "Fatal error: Uncaught Error: Class 'mikehaertl \ wkhtmlto \ Pdf' not found"
`require_once __DIR__.'/vendor/autoload.php';
   
use mikehaertl\wkhtmlto\Pdf;
 
 
$pdf = new \mikehaertl\wkhtmlto\Pdf();
$pdf->addPage('/pdf_p1.html');
 
 
$pdf->send();`

Thank you

**Comment by mikehaertl** [comment]
@asmabelhadj123 Something is wrong with the autoloading of composer in your setup. This has nothing to do with our library.

**Comment by asmabelhadj123** [comment]
> @asmabelhadj123 Something is wrong with the autoloading of composer in your setup. This has nothing to do with our library.

I resolved my problem 
the root of wkhtmltopdf is **"/usr/local/bin/wkhtmltopdf"**
