### ISSUE TITLE
functionality replace  does not work

### ISSUE THREAD

**Issue by sebastos13** [mikehaertl/phpwkhtmltopdf#91]
Hello,
I use phpwkhtmltopdf 0.12.2.1 with PHP Zend Framework. I have a problem I can't to solve.
In array Options, i want use "replace" to send value for my header.html, but it does not work.
I followed the manual and examples but it does not work.

In my options array, i put   'replace' => array('{datejour}' => '10/12/15'),	
and in my header html i put span class="date_jour"></span>.

When I generates pdf , value is not replaced.

I tried to integrate the example in the PDFTest.php :    
'replace' => array( '{x}' => 'a','{y}' => 'b',),
with
'header-center' => 'test {x} {y}',

but does not work.

**Comment by mikehaertl** [comment]
Hmm, not sure if I can help much. There's a test case for this, that makes sure, that the command string is generated correctly: https://github.com/mikehaertl/phpwkhtmltopdf/blob/master/tests/PdfTest.php#L218

You could maybe verify with `echo $pdf->getCommand()` if that's the case for you. If it's correct, then it's a problem of `wkhtmltopdf`. You could ask there to get further help.

**Comment by mikehaertl** [comment]
Oh and i see two problems in your code:

 * You wrote `datejour` but replace `date_jour`
 * You didn't surround it with `{ }` in your header. 

So it should be `{date_jour}` in your header.

**Comment by sebastos13** [comment]
thank you for your reply, 
In my php
'replace' => array('{date_jour}' => '10/12/15'),
In my Header.html
<tr><td class="title_info_general">DATE</td><td>: {date_jour}</td></tr>

changes had no effect, nothing appears

C:\wkhtmltopdf\bin\wkhtmltopdf --no-outline --encoding "UTF-8" --margin-top "20" --margin-right "5" --margin-bottom "15" --margin-left "5" --footer-font-size "6" --header-html "C:/Program Files (x86)/PostgreSQL/EntrepriseDB-Apache/Php/apache/www/poli/application/views/scripts/wkhtmltopdf/header.html" --footer-html "C:/Program Files (x86)/PostgreSQL/EntrepriseDB-Apache/Php/apache/www/poli/application/views/scripts/wkhtmltopdf/footer.html" --disable-smart-shrinking --user-style-sheet "C:/Program Files (x86)/PostgreSQL/EntrepriseDB-Apache/Php/apache/www/poli/public/css/devis.css" --replace "{date_jour}" "10/12/15" "C:\Windows\Temp\tmpCDAC.tmp.html" "C:\Windows\Temp\tmpCDAD.tmp.pdf"

--replace "{date_jour}" "10/12/15"

I can't find the problem

**Comment by mikehaertl** [comment]
As far as I know, you can't use `replace` with an external footer file. In any case, this is not a problem of phpwkhtmltopdf. In other words: Your example wouldn't work either if you use `wkhtmltopdf` on the command line.

**Comment by sebastos13** [comment]
I found another solution

**Comment by newpen** [comment]
@sebastos13 , What is the solution? :)

**Comment by dpayne0220** [comment]
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2427 << this guy has a good implementation of what you're trying to do
