### ISSUE TITLE
send() outputs a corrupted pdf

### ISSUE THREAD

**Issue by bcreeves** [mikehaertl/phpwkhtmltopdf#92]
When I use `saveAs()` a pdf is saved and works perfectly. When I try to use `send()` it outputs a broken pdf. 

Below is a screenshot of the first few lines of the corrupted pdf.

![screen shot 2015-03-16 at 5 23 37 pm](https://cloud.githubusercontent.com/assets/815334/6676850/5d6b4868-cc01-11e4-9960-16d5b3536d5a.png)

**Comment by bcreeves** [comment]
I figured it out. I'm an idiot. After looking at error logs they showed a lot of  `Cannot modify header information - headers already sent... ` errors.

I moved the pdf generation code to before any html is written in my php file and it worked.

**Comment by mikehaertl** [comment]
IMO you should not write any HTML at all when you send the file.
