### ISSUE TITLE
command does not finish

### ISSUE THREAD

**Issue by krampstudio** [mikehaertl/phpwkhtmltopdf#94]
When I run the PDF generation from this wrapper, the process never finish but from the command line it works.
If I `ps` I can see the process that is still running:
```
www-data   544  0.0  0.0   4444   800 ?        S    13:46   0:00 sh -c /usr/local/bin/wkhtmltopdf --window-status 'runner-ready' --no-stop-slow-scripts --print-media-type --cookie 'tao_fKDDh87R' 'b2kqu9tsmg7of1d228ripv0mp1' 'https://tao.localdomain/taoBooklet/PrintTest/render?uri=http%3A%2F%2Fbertao%2Ftao.rdf%23i1427720467942465' '/tmp/tmp_wkhtmlto_pdf_saXgPE.pdf'
www-data   545  0.0  0.1 328368 23404 ?        Sl   13:46   0:00 /usr/local/bin/wkhtmltopdf --window-status runner-ready --no-stop-slow-scripts --print-media-type --cookie tao_fKDDh87R b2kqu9tsmg7of1d228ripv0mp1 https://tao.localdomain/taoBooklet/PrintTest/render?uri=http%3A%2F%2Fbertao%2Ftao.rdf%23i1427720467942465 /tmp/tmp_wkhtmlto_pdf_saXgPE.pdf
```

And when I run the command manually, everything goes well and the pdf is generated in a few seconds:

```sh
/usr/local/bin/wkhtmltopdf --window-status runner-ready --no-stop-slow-scripts --print-media-type --cookie tao_fKDDh87R b2kqu9tsmg7of1d228ripv0mp1 https://tao.localdomain/taoBooklet/PrintTest/render?uri=http%3A%2F%2Fbertao%2Ftao.rdf%23i1427720467942465 /tmp/tmp_wkhtmlto_pdf_saXgPE.pdf
Loading pages (1/6)
Warning: SSL error ignored                                        
Warning: SSL error ignored                                         
Counting pages (2/6)
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done
```

**Comment by krampstudio** [comment]
It seems the issue comes from tha way I declare options to set a cookie: 
```php
$pdf->setOptions(array(
           'cookie' => array(session_name() => session_id())
));
```

So it leads me to 2 questions:
1. what's the way to declare the cookie value 
2. Is there a way to timeout the process, so it kills instead of running indefinitely

**Comment by mikehaertl** [comment]
1. Your way to define the cookie option should be fine. You also see it in the command in your `ps` output.
2. No and this would be very hard to implement and make it work in all scenarios.

You could try to use the `useExec` option (which uses `exec()` instead of `proc_open()` when executing `wkhtmltopdf`): https://github.com/mikehaertl/phpwkhtmltopdf/issues/56#issuecomment-61456283

If that doesn't help I can't really tell what's wrong. But if you find out more, please keep me updated. Maybe we can find a fix for your problem.

**Comment by krampstudio** [comment]
Sorry this 100% my fault and your wrapper behaves as expect. The usual suspect: I've forgotten `session_write_close()`.

**Comment by miclaus** [comment]
Happened that I stumbled upon this issue as well.

I saved some data in `$_SESSION`, then `session_write_close()`, then created the `Pdf` instance and and passed `'cookie' => [ session_name() => session_id() ]` as option.
