### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by darrensw** [mikehaertl/phpwkhtmltopdf#96]
When I try: `php composer.phar require mikehaertl/phpwkhtmltopdf`

I get the following error:

    Using version ~2.0 for mikehaertl/phpwkhtmltopdf
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

    Problem 1
    - The requested package mikehaertl/phpwkhtmltopdf 1.0.0 could not be found.

    Potential causes:

    A typo in the package name
    The package is not available in a stable-enough version according to your min imum-stability setting see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f or more details.

    Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

    Installation failed, reverting ./composer.json to its original content.`

What am I doing wrong?

**Comment by mikehaertl** [comment]
Problem solved? What was it?

**Comment by darrensw** [comment]
Hi Mike

TBH your composer.JSON file for this project is a little confusing - I'm brand new to composer and so was advised to run `composer init` - when it asked for project name, I looked at you JSON file and saw `mikehaertl/phpwkhtmltopdf` in the name field, when actually I should have been entering: `phpwkhtmltopdf` - it's all a learning curve!

**Comment by mikehaertl** [comment]
I don't understand. I nowhwere said, you should enter `composer init` anywhere. And the `composer.json` file is just fine. Here's what happens, if I install this package with composer:

```
$ composer require mikehaertl/phpwkhtmltopdf
Using version ~2.0 for mikehaertl/phpwkhtmltopdf
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mikehaertl/php-shellcommand (1.0.5)
    Loading from cache

  - Installing mikehaertl/php-tmpfile (1.0.5)
    Loading from cache

  - Installing mikehaertl/phpwkhtmltopdf (2.0.3)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

**Comment by darrensw** [comment]
Hmmm - didn't work for me like that - It wasn't you who said to run `composer init`, I asked a question on stackoverflow, here: http://stackoverflow.com/questions/29868879/composer-not-composing-saying-file-not-found - this is how my `composer.json file` looks after running it:

    {
      "name": "phpwkhtmltopdf",
      "description": "html to pdf",
      "require-dev": {
      },
      "authors": [
          {
            "name": "Michael Haertl",
            "email": "haertl.mike@gmail.com"
          }
      ],
      "minimum-stability": "dev",
      "require": {
        "mikehaertl/phpwkhtmltopdf": "~2.0"
      }
    }

**Comment by mikehaertl** [comment]
You don't need `composer init` at all. If you didn't install any composer packages before, just go to an empty directory (or to your project directory) and use `composer require mikehaertl/phpwkhtmltopdf`. That's all. You should **not** create any `composer.json` file. 

Apart from that the issue is really related to composer, not to this package.

**Comment by darrensw** [comment]
Yeah, totally agree on that - thanks for that info, good to know
